### ISSUE TITLE
QUERY: how to resolve System.TypeLoadException: Method 'get_SerializationSettings' in Fluent Management SDK

### ISSUE THREAD

**Issue by daveoshinsky** [Azure/azure-libraries-for-net#1016]
I am seeing the following exception when adding logic to query for Cosmos DB credentials, using Fluent Management SDK's.  I don't see it in a simpler test program, and believe that this has to do with two different versions of Newtonsoft.Json loaded at once (6.0.8 and 12.0.3, from different portions of the complex logic).  I did include the following assembly redirect in app.config for the DLL using Fluent SDK API's, but it did not help:

      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-13.0.0.0" newVersion="12.0.3" />
      </dependentAssembly>

The exception:
:Exception- System.AggregateException: One or more errors occurred. ---> System.TypeLoadException: Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Sql.Fluent.SqlManagementClient' from assembly 'Microsoft.Azure.Management.Sql.Fluent, Version=1.0.0.64, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
   at Microsoft.Azure.Management.Sql.Fluent.SqlManager..ctor(RestClient restClient, String subscriptionId, String tenantId)
   at Microsoft.Azure.Management.Sql.Fluent.SqlManager.Authenticate(RestClient restClient, String subscriptionId)
   at Microsoft.Azure.Management.Fluent.Azure..ctor(RestClient restClient, String subscriptionId, String tenantId, IAuthenticated authenticated)
   at Microsoft.Azure.Management.Fluent.Azure.Authenticated.WithSubscription(String subscriptionId)
   at AzureSDKWrapper.AzureResourceStorage.<GetAuthenticationInfoAsync>d__17.MoveNext() in C:\11.0Batch340\vaultcx\Source\CommClient\VirtualServer\AzureSDKWrapper\AzureResourceManager\AzureResourceStorage.cs:line 265
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at AzureSDKWrapper.AzureResourceStorage.GetAuthenticationInfo(String storageAccountName, String& tableStorageUrl, String& accessKey, Boolean cosmosDBFlag) in ......\AzureSDKWrapper\AzureResourceManager\AzureResourceStorage.cs:line 206
---> (Inner Exception #0) System.TypeLoadException: Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Sql.Fluent.SqlManagementClient' from assembly 'Microsoft.Azure.Management.Sql.Fluent, Version=1.0.0.64, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
   at Microsoft.Azure.Management.Sql.Fluent.SqlManager..ctor(RestClient restClient, String subscriptionId, String tenantId)
   at Microsoft.Azure.Management.Sql.Fluent.SqlManager.Authenticate(RestClient restClient, String subscriptionId)
   at Microsoft.Azure.Management.Fluent.Azure..ctor(RestClient restClient, String subscriptionId, String tenantId, IAuthenticated authenticated)
   at Microsoft.Azure.Management.Fluent.Azure.Authenticated.WithSubscription(String subscriptionId)
   at AzureSDKWrapper.AzureResourceStorage.<GetAuthenticationInfoAsync>d__17.MoveNext() in .......\AzureSDKWrapper\AzureResourceManager\AzureResourceStorage.cs:line 265<---

Any ideas would be greatly appreciated.

**Comment by daveoshinsky** [comment]
The assembly redirect appeared to be left out.  It is:

      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-13.0.0.0" newVersion="12.0.3" />
      </dependentAssembly>

**Comment by weidongxu-microsoft** [comment]
After quick read, I guess this might be helpful
https://github.com/Azure/azure-libraries-for-net/issues/934#issuecomment-567754899

The redirectly in dll seems not working for final exe in above case (not sure whether this is same issue on your case).

**Comment by daveoshinsky** [comment]
Thanks Weidong, that is an excellent insight.  So the app.config for my DLL is somehow not taking effect for the EXE within which it runs.  That EXE is a very complex one, which involves Native code bridging into Managed code in a number of places, using multiple underlying .NET frameworks.

Once I made the change you suggested, the problem morphed into a different one.  I suspect that this has to do with out-of-date Managed DLL's from other parts of the EXE.  I've tried updating to latest versions of Microsoft.Rest.ClientRuntime and Microsoft.IdentityModel.Clients.ActiveDirectory, but the following exception still occurs.  If you have any insight, that would be greatly appreciated.

  :Exception- System.AggregateException: One or more errors occurred. ---> System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Rest.ServiceClientCredentials> Microsoft.Rest.Azure.Authentication.UserTokenProvider.LoginSilentAsync(System.String, System.String, System.String, System.String, Microsoft.Rest.Azure.Authentication.ActiveDirectoryServiceSettings, Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache)'.
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.<ProcessHttpRequestAsync>d__24.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.CosmosDB.Fluent.DatabaseAccountsOperations.<GetWithHttpMessagesAsync>d__5.MoveNext()

**Comment by daveoshinsky** [comment]
I observed under the debugger where it is throwing the latest MissingMethodException, at the StartNew() line in this Extensions.cs method:

        public static TResult Synchronize<TResult>(Func<Task<TResult>> function)
        {
            return Task.Factory.StartNew(function, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default)
                .Unwrap().GetAwaiter().GetResult();
        }

The function argument contains the method that was not found, enclosed in JSON as "Method = {value}".  What is going on?  I assume it's something out-of-sync in the referenced assemblies, but what?

**Comment by daveoshinsky** [comment]
After copying all of the DLL's from a working standalone test program, everything matches and it works.
