### ISSUE TITLE
[BUG] SDK creates a lot of HttpClient causing connection starvation

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-libraries-for-net#1046]
**Describe the bug**
When using the SDK for long-running processes, we've noticed that it's causing Linux workloads to run out of connections (https://github.com/tomkerkhove/promitor/issues/798).

After digging deeper, we thought we were not using the SDK correctly so we've POCed a refactoring where we only authenticate once and re-use it for the rest of the processing (https://github.com/tomkerkhove/promitor/pull/844).

After digging deeper, [@maartenba found that the SDK is creating a lot of HttpClients ](https://github.com/tomkerkhove/promitor/pull/844#issuecomment-577135547) and not re-using them.

Is this on purpose or is this a bug?

***Exception or Stack Trace***
```
System.Net.Http.HttpRequestException: Too many open files in system ---> System.Net.Sockets.SocketException: Too many open files in system
   at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
   at System.Net.Sockets.DualSocketMultipleConnectAsync..ctor(SocketType socketType, ProtocolType protocolType)
   at System.Net.Sockets.Socket.ConnectAsync(SocketType socketType, ProtocolType protocolType, SocketAsyncEventArgs e)
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
```

**To Reproduce**
- Authenticate client
- Have look how many clients are created

**Expected behavior**
Re-use of one HttpClient rather than 70+

**Setup (please complete the following information):**
 - OS: Linux
 - IDE : Visual Studio
 - Version of the Library used: 1.30.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by qub1n** [comment]
I have been following [this guideline](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests) for .NET core and injected this HttpClientfactory to the new GraphServiceClient and it seems that it works. 

It will be better if this is the default behaviour of this SDK.

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help to have a look?

**Comment by tomkerkhove** [comment]
> @tomkerkhove
> 
> I have been following [this guideline](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests).
> 
> Furthermore in that guide, they mention socket exhaustion which you can face if you use standard old HttpClient.
> 
> I solved this by injecting this HttpClientfactory to the new GraphServiceClient and it seems that it works.
> 
> I can see at least the difference using dottrace that the REST API is no more parsed by Newtonsoft JSON which was one of the reasons I made this performance improvement.
> 
> It will be better if this is the default behaviour of this SDK.

@qub1n You're saying that you do this on top of the SDK or have written your own or? I'm not really following, sorry!

**Comment by xccc-msft** [comment]
@tomkerkhove Can you share the code snippet which API used for authentication?

**Comment by tomkerkhove** [comment]
This is what we are doing:
```csharp
private IAzure CreateAzureClient(AzureEnvironment azureCloud, string tenantId, string subscriptionId, string applicationId, string applicationSecret, IOptions<AzureMonitorLoggingConfiguration> azureMonitorLoggingConfiguration, ILoggerFactory loggerFactory, IRuntimeMetricsCollector runtimeMetricsCollector)
{
    var credentials = _azureCredentialsFactory.FromServicePrincipal(applicationId, applicationSecret, tenantId, azureCloud);

    var monitorHandler = new AzureResourceManagerThrottlingRequestHandler(...);

    var azureClientConfiguration = Azure.Configure()
        .WithDelegatingHandler(monitorHandler);
    var azureMonitorLogging = azureMonitorLoggingConfiguration.Value;
    if (azureMonitorLogging.IsEnabled)
    {
        azureClientConfiguration = azureClientConfiguration.WithDelegatingHandler(new HttpLoggingDelegatingHandler())
            .WithLogLevel(azureMonitorLogging.InformationLevel);
    }

    return azureClientConfiguration
        .Authenticate(credentials)
        .WithSubscription(subscriptionId);
}
```

**Comment by xccc-msft** [comment]
@tomkerkhove Thanks for sharing. It looks the root cause comes from [FluentServiceClientBase](https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/ResourceManager/Core/FluentServiceClientBase.cs#L33) and [ServiceClient](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/mgmtcommon/ClientRuntime/ClientRuntime/ServiceClient.cs#L330-L359). We might need time to figure out if it was on purpose for some reason.

cc: @hovsepm

**Comment by tomkerkhove** [comment]
No problem, take your time! Happy to wait for a good fix rather than rushing to regret it later on!

/cc @adam-resdiary

**Comment by xccc-msft** [comment]
@tomkerkhove BTW, how many resource providers you are using via the authenticated Azure client?

**Comment by tomkerkhove** [comment]
Interesting, is there a doc page with all the options?

Might want to dig in to that, but the original issue remains; right?

**Comment by xccc-msft** [comment]
@tomkerkhove Here is the [source code](https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/Azure.Fluent/Azure.cs#L649-L671) to initialize all service managers when user authenticate Azure client. If you only use some of them, you might use the managers of them instead.

**Comment by tomkerkhove** [comment]
Sorry for the delay - I've had a look and it looks like I just need Azure Monitor ([initialized here](https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/Azure.Fluent/Azure.cs#L670)) but it's a private constructor called by [`WithSubscription`](https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/Azure.Fluent/Azure.cs#L862) so I can't access all the info I need.

Feels like it should be opened up some how before I can use it.

**Comment by tomkerkhove** [comment]
Bump

**Comment by xccc-msft** [comment]
@tomkerkhove Sorry I missed this. For your case, if you only need Azure Monitor. Then you can create ServiceBusManager directly instead of Azure client.
```csharp
ServiceBusManager.Authenticate(restClient, subscriptionId);
```
