### ISSUE TITLE
[BUG] FunctionApp WithExistingStorageAccount results in BadRequest

### ISSUE THREAD

**Issue by a-vishar** [Azure/azure-libraries-for-net#1057]
**Describe the bug**
When setting up (or updating) a function with an existing storage account, if there are IP restrictions in place on the storage account, the update fails.

***Exception or Stack Trace***
```
{"Code":"BadRequest","Message":"There was a conflict. The remote server returned an error: (403) Forbidden.","Target":null,"Details":[{"Message":"There was a conflict. The remote server returned an error: (403) Forbidden."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"01020","MessageTemplate":"There was a conflict. {0}","Parameters":["The remote server returned an error: (403) Forbidden."],"Code":"BadRequest","Message":"There was a conflict. The remote server returned an error: (403) Forbidden."}}],"Innererror":null}
```

```
   at Microsoft.Azure.Management.AppService.Fluent.WebAppsOperations.<UpdateApplicationSettingsWithHttpMessagesAsync>d__20.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.AppService.Fluent.WebAppsOperationsExtensions.<UpdateApplicationSettingsAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.AppService.Fluent.AppServiceBaseImpl`6.<UpdateAppSettingsAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.AppService.Fluent.WebAppBaseImpl`5.<SubmitAppSettingsAsync>d__282.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.AppService.Fluent.FunctionAppImpl.<SubmitAppSettingsAsync>d__217.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.AppService.Fluent.WebAppBaseImpl`5.<CreateResourceInternalAsync>d__279.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.AppService.Fluent.WebAppBaseImpl`5.<CreateResourceAsync>d__280.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.<Microsoft-Azure-Management-ResourceManager-Fluent-Core-ResourceActions-IResourceCreator<IResourceT>-CreateResourceAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.<ExecuteAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.<ExecuteNodeTaskAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.AppService.Fluent.FunctionAppImpl.<CreateAsync>d__219.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.Create()
   at MarketFinance.InfrastructureAsCode.AzureExtensions.CreateWithDeleteLock[T](ICreatable`1 resourceToCreate, IAzure azure) in C:\dev\InfrastructureAsCode\src\InfrastructureAsCode\AzureExtensions.cs:line 12
   at MarketFinance.InfrastructureAsCode.FunctionApp.FunctionAppConfiguration.CreateFunctionApp() in C:\dev\InfrastructureAsCode\src\InfrastructureAsCode\FunctionApp\FunctionAppConfiguration.cs:line 87
   at MarketFinance.InfrastructureAsCode.FunctionApp.FunctionAppConfiguration.Deploy() in C:\dev\InfrastructureAsCode\src\InfrastructureAsCode\FunctionApp\FunctionAppConfiguration.cs:line 51
   at ApplyService.Infrastructure.Runner.Program.Main(String[] args) in C:\dev\ApplyService\src\Infrastructure.Runner\Program.cs:line 62
```

**To Reproduce**

- Create a storage account which allows access from:
  - Selected networks (Add current IP)
  - Trusted Microsoft services
- Run the code snippet
- See failure

***Code Snippet***
```
azure.AppServices.FunctionApps
    .Define(FunctionAppName)
    .WithExistingAppServicePlan(AppServicePlan)
    .WithExistingResourceGroup(ResourceGroup)
    .WithExistingStorageAccount(StorageAccount);
```

**Expected behavior**
No error

**Setup (please complete the following information):**
Windows
Visual Studio 2019
Microsoft.Azure.Management.Fluent 1.33.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X] Bug Description Added
- [ X] Repro Steps Added
- [ X] Setup information Added

**Comment by a-vishar** [comment]
Any update on this?

**Comment by weidongxu-microsoft** [comment]
From doc, function app seems not one of the trusted microsoft service?
https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security#exceptions

**Comment by a-vishar** [comment]
The issue here is that I have permission to modify the function app and the storage account, but when I try to add the storage account to the function app it fails.  

Are you saying that to have the configuration I outlined above I would need to:

1) Create the storage account
2) Create the function app
3) Give the function app a managed identity
4) Add the function apps manage identity to the storage account
5) Add the storage account to the function app

If this is true for an update, why isn't this true when I create the resource in the first place?  I can configure all of the above with a new function app and storage account, why does this issue only occur for pre-existing storage accounts?

**Comment by a-vishar** [comment]
Any update on this?

**Comment by weidongxu-microsoft** [comment]
@a-vishar 

I still not get your steps. Is it possible for you to provide code snippet to clarify your config and help reproduce the issue?

The above snippet about function app does not have any configure on the storage account at all. Hence I am not able to understand the different of "It works with a new function app and storage account" and "this issue only occur for pre-existing storage accounts".
I am sure that "It works with a new function app and storage account" because a new storage account created with the function app does not have IP restriction in place. I believe if you have pre-existing storage account without IP restriction, the function app will also work, is it?

**Comment by a-vishar** [comment]
Going the managed identity route I outlined above resolved this issue.  It's still a bug IMHO, we just have a workaround.
