### ISSUE TITLE
IResourceManager GenericResources.CheckExistenceAsync deadlock

### ISSUE THREAD

**Issue by abhi1509** [Azure/azure-libraries-for-net#106]
Both the Sync and Async version of API GenericResources.CheckExistenceAsync deadlock call gets stuck and finally fails with:

System.Threading.Tasks.TaskCanceledException: A task was canceled.
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourcesOperations.<CheckExistenceWithHttpMessagesAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourcesOperationsExtensions.<CheckExistenceAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.GenericResourcesImpl.<CheckExistenceAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

**Comment by hovsepm** [comment]
@abhi1509 what is the version of `Microsoft.Azure.Management.ResourceManager.Fluent` package in your project?

**Comment by abhi1509** [comment]
1.3. 
Tried 1.4 but can’t install. It says system.runtime missing from GAC.

**Comment by hovsepm** [comment]
@abhi1509 what is your dev box configuration? I'll need to have a repro locally to investigate. Did you check fiddler logs?

**Comment by abhi1509** [comment]
Windows 10
VS 15 update 3

**Comment by hovsepm** [comment]
@abhi1509 Target framework? Do you install rollup package or just ResourceManager.Fluent?

**Comment by hovsepm** [comment]
@abhi1509 I have a repro. Seems like nuget manager is broken on VS2015. I've opened the same project in VS2017 and was able to add v1.4 reference.

**Comment by abhi1509** [comment]
target framework is 4.5.2

What about the deadlock? is it fixed in 1.4?

**Comment by hovsepm** [comment]
I'll need a repro for that as well. Could you post your code here (excluding sensitive data if any)?

**Comment by abhi1509** [comment]
https://github.com/abhi1509/fluentSdkRmGenericResourceDeadlock/tree/master/WebApplicationRepro.Tests
run the test TestStuckGenericResourcesCheckExistence

**Comment by hovsepm** [comment]
No repro.
On my dev box (win10, VS2015) Your solution actually checks in a loop that SimpleWinVM is created but constantly receives 404 back. 

it hangs here - https://github.com/abhi1509/fluentSdkRmGenericResourceDeadlock/blob/master/WebApplicationRepro/AzureResourceManager.cs#L110 

sends `/resourcegroups/temp1234/providers/Microsoft.Compute//virtualMachines/SimpleWinVM?api-version=2016-04-30-preview HTTP/1.1`
receives `HTTP/1.1 404 Not Found`
and never exits the while loop.

**Comment by abhi1509** [comment]
given that we started a deployment, the VM should eventually exist and then we should exit the loop. once the VM is there, this gets stuck. I have noticed that it works fine if resource is not there.

**Comment by abhi1509** [comment]
@hovsepm Please let me know if you can't repro it. Basically if you query for a resource **which already exists**, it gets deadlocked.

**Comment by hovsepm** [comment]
@abhi1509 ok I got the repro and it is not a dead lock. SDK 3 times tries to query existence while Azure responds "503 Service Unavailable". Each retry has it's own wait time so that is why you see delays. This has nothing to do with the SDK but with the back end service.

**Comment by hovsepm** [comment]
@abhi1509 I've contacted service team for clarification.

**Comment by abhi1509** [comment]
Thanks. How long is the wait time. I modified the sample template so it now generates random dns names. otherwise the resource would never be created as there was a DNS conflict.

With the change, even when the VM is created, i still get TaskCancelledException after a long wait.

**Comment by hovsepm** [comment]
@abhi1509 it seems to be not supported by Compute Service. Their suggested workaround for now is use Get instead of Head (CheckExistence) operation. 
FYI, I've published v.1.4.1 with VS2015 issue fix.
