### ISSUE TITLE
[BUG]  Cannot communicate with server. No authentication token available for 'https://vault.azure.net/'.

### ISSUE THREAD

**Issue by Rookian** [Azure/azure-libraries-for-net#1072]
I created an _Azure Key Vault_ and defined _Access Policies_ for a group of which I am a member of.
In the Azure Portal I can see that the _Access Policies_ are defined correctly (All Access to Keys, Secrets and Certificates). The whole authentication is using `AzureServiceTokenProvider `with `RunAs=Developer; DeveloperTool=AzureCli`.

After I created Azure Key Vault successfully, I wanted to add a Key.
```
await vault.Keys.Define("XYZ")
    .WithKeyTypeToCreate(JsonWebKeyType.Rsa)
    .WithKeyOperations(JsonWebKeyOperation.Decrypt, JsonWebKeyOperation.Encrypt)
    .CreateAsync(cancellationToken);
```
This fails with 

> Microsoft.Rest.RestException: Cannot communicate with server. No authentication token available for 'https://vault.azure.net/'

I tried to create a separate instance of `KeyVaultManager`, but I am not allowed to use https://vault.azure.net/ as a resource.

```
var azureServiceTokenProvider = new AzureServiceTokenProvider("RunAs=Developer; DeveloperTool=AzureCli");
var token = await azureServiceTokenProvider.GetAccessTokenAsync("https://vault.azure.net/", cancellationToken: cancellationToken);

var keyVaultManager = KeyVaultManager.Authenticate(
    new AzureCredentials(new TokenCredentials(token), new TokenCredentials(token), vault.TenantId, AzureEnvironment.AzureGlobalCloud), api.SubscriptionId);

var byId = (await keyVaultManager.Vaults.ListByResourceGroupAsync(resourceGroup)).SingleOrDefault();
```

I could create a `Key` by hand using the _Azure Portal_ and by using the _Azure CLI_ directly without any problems.

`az keyvault key create --name xyz123 --vault-name $keyVaultName -o none`

***Exception or Stack Trace***

> Microsoft.Rest.RestException: Cannot communicate with server. No authentication token available for 'https://vault.azure.net/'.
>    at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Azure.KeyVault.KeyVaultClient.CreateKeyWithHttpMessagesAsync(String vaultBaseUrl, String keyName, String kty, Nullable`1 keySize, IList`1 keyOps, KeyAttributes keyAttributes, IDictionary`2 tags, String curve, Dictionary`2 customHeaders, CancellationToken cancellationToken)
>    at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.CreateKeyAsync(IKeyVaultClient operations, String vaultBaseUrl, String keyName, String kty, Nullable`1 keySize, IList`1 keyOps, KeyAttributes keyAttributes, IDictionary`2 tags, String curve, CancellationToken cancellationToken)
>    at Microsoft.Azure.Management.KeyVault.Fluent.KeyImpl.CreateRawAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.Management.KeyVault.Fluent.KeyImpl.CreateResourceAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.IResourceCreator<IResourceT>.CreateResourceAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.ExecuteAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.ExecuteNodeTaskAsync(DAGNode`1 node, CancellationToken cancellationToken)
>    at Deployment.PreProvisioning.HostedService.<>c__DisplayClass5_0.<<CreateAzureKeyVault>b__1>d.MoveNext() in C:\git\xyz123\src\release\Deployment.PreProvisioning\Program.cs:line 206
> --- End of stack trace from previous location where exception was thrown ---
>    at Deployment.Core.ConsoleEx.LabeledAction(String label, Func`1 action) in C:\git\xyz123\src\release\Deployment.Core\ConsoleEx.cs:line 75
> Microsoft.Rest.RestException: Cannot communicate with server. No authentication token available for 'https://vault.azure.net/'.
>    at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Azure.KeyVault.KeyVaultClient.CreateKeyWithHttpMessagesAsync(String vaultBaseUrl, String keyName, String kty, Nullable`1 keySize, IList`1 keyOps, KeyAttributes keyAttributes, IDictionary`2 tags, String curve, Dictionary`2 customHeaders, CancellationToken cancellationToken)
>    at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.CreateKeyAsync(IKeyVaultClient operations, String vaultBaseUrl, String keyName, String kty, Nullable`1 keySize, IList`1 keyOps, KeyAttributes keyAttributes, IDictionary`2 tags, String curve, CancellationToken cancellationToken)
>    at Microsoft.Azure.Management.KeyVault.Fluent.KeyImpl.CreateRawAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.Management.KeyVault.Fluent.KeyImpl.CreateResourceAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.IResourceCreator<IResourceT>.CreateResourceAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.ExecuteAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.ExecuteNodeTaskAsync(DAGNode`1 node, CancellationToken cancellationToken)
>    at Deployment.PreProvisioning.HostedService.<>c__DisplayClass5_0.<<CreateAzureKeyVault>b__1>d.MoveNext() in C:\git\xyz123\src\release\Deployment.PreProvisioning\Program.cs:line 206
> --- End of stack trace from previous location where exception was thrown ---
>    at Deployment.Core.ConsoleEx.LabeledAction(String label, Func`1 action) in C:\git\xyz123\src\release\Deployment.Core\ConsoleEx.cs:line 75
>    at Deployment.PreProvisioning.HostedService.CreateAzureKeyVault(IAzure api, Environment environment, String resourceGroup, String resourceSuffix, String location, Dictionary`2 tags, CancellationToken cancellationToken) in C:\git\xyz123\src\release\Deployment.PreProvisioning\Program.cs:line 170
>    at Deployment.PreProvisioning.HostedService.StartAsync(CancellationToken cancellationToken) in C:\git\xyz123\src\release\Deployment.PreProvisioning\Program.cs:line 108

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : VS 2010
 - Version of the Library used: Microsoft.Azure.Management.Fluent/Microsoft.Azure.Management.ResourceManager.Fluent 1.33.0

Any help is appreciated :)

**Comment by weidongxu-microsoft** [comment]
@Rookian 

I think the cause is here.

KeyVault data-plane client actually need a different `adSettings.TokenAudience` from management/graphrbac. If credential of service principal is provided, it will use it to obtain a token for KeyVault data-plane client. But if in the code, `managementToken` and `graphToken` is provided instead, code here cannot auth correctly.

One way to solve is e.g. using `Microsoft.Azure.KeyVault` lib directly, when handling key/secret after keyvault is created in Fluent SDK.
