### ISSUE TITLE
[BUG] IAzure.PolicyDefinitions.GetByNameAsync does not find an existing Policy

### ISSUE THREAD

**Issue by ThomasManson** [Azure/azure-libraries-for-net#1096]
When using IAzure.PolicyDefinitions.GetByNameAsync with the guid for a policy, I get the following exception:

Microsoft.Rest.Azure.CloudException
  HResult=0x80131500
  Message=The policy definition '871b6d14-10aa-478d-b590-94f262ecfa99' could not be found.
  Source=Microsoft.Azure.Management.ResourceManager.Fluent
  StackTrace:
   at Microsoft.Azure.Management.ResourceManager.Fluent.PolicyDefinitionsOperations.<GetWithHttpMessagesAsync>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.PolicyDefinitionsOperationsExtensions.<GetAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.PolicyDefinitionsImpl.<GetByNameAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AzurePolicyTests.Program.<Main>d__0.MoveNext() in C:\Users\xxxx\source\repos\AzurePolicyTests\AzurePolicyTests\Program.cs:line 20

  This exception was originally thrown at this call stack:
    [External Code]
    AzurePolicyTests.Program.Main(string[]) in Program.cs

However, when I use this, I can get the policy:
            var list = await azure.PolicyDefinitions.ListAsync();
            var def = list.FirstOrDefault(l => l.Name == "871b6d14-10aa-478d-b590-94f262ecfa99");

***Repo Steps***
I see this error with a custom policy created through the Portal. Not sure if there is anything specific about the policy that makes this happen.

***Code Snippet***
.NET Core 3.1 with the following packages referenced:
    <PackageReference Include="Microsoft.Azure.Management.Fluent" Version="1.34.0" />
    <PackageReference Include="Microsoft.Azure.Management.ResourceManager.Fluent" Version="1.34.0" />

            var clientId = "xxx";
            var tenantId = "xxxx";
            var subscriptionId = "xxxx";
            var clientSecret = "xxxx";

            var credentials = SdkContext.AzureCredentialsFactory.FromServicePrincipal(clientId, clientSecret, tenantId, AzureEnvironment.AzureGlobalCloud);
            var azure = Microsoft.Azure.Management.Fluent.Azure
                .Configure()
                .Authenticate(credentials)
                .WithSubscription(subscriptionId);

           // this line fails
            var def1 = await azure.PolicyDefinitions.GetByNameAsync("871b6d14-10aa-478d-b590-94f262ecfa99");

           // these succeed
            var list = await azure.PolicyDefinitions.ListAsync();
            var def = list.FirstOrDefault(l => l.Name == "871b6d14-10aa-478d-b590-94f262ecfa99");

**Expected behavior**
Expect the GetByName to return the policy definition

**Setup (please complete the following information):**
 - OS: Windows 10 2004
 - IDE : Visual Studio 2019
 - 1.34.0

**Comment by kenieva** [comment]
This doesn't seem to be a policy issue. We would need more information to be able to triage. Please create a support ticket for us to get more information and debug the issue. Thank you.
