### ISSUE TITLE
[QUERY]how to get role assignment with scope "/"

### ISSUE THREAD

**Issue by Emma0727** [Azure/azure-libraries-for-net#1122]
**Query/Question**
A clear and concise ask/query.
Query/Question
How can we help?
how to get role assignment with scope "/".
It seems .RoleAssignments.ListByScopeAsyncor other method are not support scope “/”.

```
var tokenCredentials = new TokenCredentials(armToken);
                var authenticated = Azure
                    .Configure()
                    .WithLogLevel(HttpLoggingDelegatingHandler.Level.Basic)
                    .Authenticate(new AzureCredentials(
                        tokenCredentials,
                        tokenCredentials,
                        organizationId,
                        AzureEnvironment.AzureGlobalCloud));

                var roledefinition = await authenticated.RoleDefinitions.GetByScopeAndRoleNameAsync("/", BuiltInRole.UserAccessAdministrator.ToString());
                var roleAssignments = await authenticated.RoleAssignments.ListByScopeAsync("/");
```
now I can only get that from api:
https://management.azure.com/providers/Microsoft.Authorization/roleAssignments?api-version=2015-07-01&$filter=principalId eq '***'
***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by Emma0727** [comment]
I try to use another method to get role assginment:
var roleAssignments = await authenticated.RoleAssignments.GetByIdAsync(roledefinition.Id);
But it failed like ther viersion api version used 2018-09-01-preview, is not suitable.
Any one can help?

[2020_08_12_08_52_30.968] [LogException], AzureResourceService, GetAzureClientAynsc, 13be6b52-e8b1-4622-afd3-e8bcc5f3709e, exception:Microsoft.Rest.Azure.CloudException: The resource type 'roleDefinitions' could not be found in the namespace 'Microsoft.Authorization' for api version '2018-09-01-preview'. The supported api-versions are '2014-04-01-preview,2014-07-01-preview,2014-10-01-preview,2015-05-01-preview,2015-06-01,2015-07-01,2016-07-01,2017-05-01,2017-09-01,2018-01-01-preview,2018-07-01'.
   at Microsoft.Azure.Management.Graph.RBAC.Fluent.RoleAssignmentsOperations.GetByIdWithHttpMessagesAsync(String roleId, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Graph.RBAC.Fluent.RoleAssignmentsOperationsExtensions.GetByIdAsync(IRoleAssignmentsOperations operations, String roleId, CancellationToken cancellationToken)

**Comment by yungezz** [comment]
hi @xccc-msft do you have a quick answer for this?

**Comment by xccc-msft** [comment]
@Emma0727 What's the response you get when sending scope `/`?

For below line, you should pass role assignment id instead of role definition id. 
`var roleAssignments = await authenticated.RoleAssignments.GetByIdAsync(roledefinition.Id);`

**Comment by Emma0727** [comment]
> GetByIdAsync

It throw exception:
82a13973-2c06-4162-8b13-71686f111362, exception:Microsoft.Rest.Azure.CloudException: **The role assignments query at '/' scope is not allowed without any filters.**
   at Microsoft.Azure.Management.Graph.RBAC.Fluent.RoleAssignmentsOperations.ListForScopeWithHttpMessagesAsync(String scope, ODataQuery`1 odataQuery, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Graph.RBAC.Fluent.RoleAssignmentsOperationsExtensions.ListForScopeAsync(IRoleAssignmentsOperations operations, String scope, ODataQuery`1 odataQuery, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Graph.RBAC.Fluent.RoleAssignmentsImpl.<>c__DisplayClass10_0.<<ListByScopeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.PagedCollection`2.LoadPageWithWrapModelAsync(Func`2 listInnerAsync, Func`3 listInnerNext, Func`3 wrapModelAsync, Boolean loadAllPages, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.PagedCollection`2.LoadPage(Func`2 listInnerAsync, Func`3 listInnerNext, Func`2 wrapModel, Boolean loadAllPages, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Graph.RBAC.Fluent.RoleAssignmentsImpl.ListByScopeAsync(String scope, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Graph.RBAC.Fluent.RoleAssignmentsImpl.Microsoft.Azure.Management.Graph.RBAC.Fluent.IRoleAssignments.ListByScopeAsync(String scope, CancellationToken cancellationToken)

**Comment by xccc-msft** [comment]
@Emma0727 Thanks for sharing. You may try
`authenticated.RoleAssignments.Inner.ListByScopeAsync` instead of `authenticated.RoleAssignments.ListByScopeAsync`. It would allow you to send with filters.

**Comment by Emma0727** [comment]
Is there any method have the same results with the below API:
GET https://management.azure.com/{scope}/providers/Microsoft.Authorization/roleAssignments?api-version=2015-07-01&$filter=assignedTo('{objectId}')
List role assignments for a specified user, including ones inherited from groups.

**Comment by xccc-msft** [comment]
@Emma0727 I only find [ListForScope](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/authorization/resource-manager/Microsoft.Authorization/stable/2015-07-01/authorization-RoleAssignmentsCalls.json#L450), [ListForResource](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/authorization/resource-manager/Microsoft.Authorization/stable/2015-07-01/authorization-RoleAssignmentsCalls.json#L42), [ListForResourceGroup](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/authorization/resource-manager/Microsoft.Authorization/stable/2015-07-01/authorization-RoleAssignmentsCalls.json#L120).
