### ISSUE TITLE
[BUG]System.NullReferenceException when calling IsResourceGroupExistsAsync

### ISSUE THREAD

**Issue by korensiso** [Azure/azure-libraries-for-net#1124]
**Describe the bug**
From time to time we got NullReferenceException from the SDK when calling to IsResourceGroupExistsAsync (also for other resources when calling to their "IsExists" API)

***Exception or Stack Trace***
Failed checking name availability for context 'ResourceType = ResourceGroup, ResourceName = small-to4_2'","System.NullReferenceException Void MoveNext() System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Rest.RetryDelegatingHandler.<SendAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ProviderRegistrationDelegatingHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Zerto.Zvm.Platform.PublicCloud.AzureProxy.Implementation.HttpTracer.<RunAndTraceRequest>d__7.MoveNext() in E:\glenlivet_u3\dev\system\Zvm\Platform\PublicCloud\AzureProxy\Implementation\HttpTracer.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.HttpLoggingDelegatingHandler.<SendAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.UserAgentDelegatingHandler.<SendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourceGroupsOperations.<CheckExistenceWithHttpMessagesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourceGroupsOperationsExtensions.<CheckExistenceAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourceGroupsImpl.<ContainAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Zerto.Zvm.Platform.PublicCloud.AzureProxy.Accessors.ResourceManagementAccessor.<IsResourceGroupExistsAsync>d__4.MoveNext() in 

**To Reproduce**
Steps to reproduce the behavior: nothing to di, it just happens randomly but not frequently.

***Code Snippet***
        public async Task<bool> IsResourceGroupExistsAsync(string resourceGroupName, CancellationToken cancellationToken = default(CancellationToken))
        {
            Debug.Assert(!string.IsNullOrEmpty(resourceGroupName));

            bool exists = await m_azure.ResourceGroup.ContainAsync(resourceGroupName, cancellationToken);
            return exists;
        }

**Expected behavior**
return true or false

**Setup (please complete the following information):**
 - OS: windows server 2016
 - IDE: visual studio
 - Version 1.26.0 (Azure C# fluent SDK)

**Comment by weidongxu-microsoft** [comment]
The bug is already fixed in 1.34
