### ISSUE TITLE
[QUERY] Problem listing Cosmos DB accounts with MSI

### ISSUE THREAD

**Issue by daveoshinsky** [Azure/azure-libraries-for-net#1125]
I'm encountering an exception like this in logic that is attempting to expand the list of Cosmos DB accounts, with MSI and Fluent SDK v1.31.1:

System.ArgumentNullException: Value cannot be null.
Parameter name: MSI_ENDPOINT
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.MSITokenProvider.<GetAuthenticationHeaderForAppServiceAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.MSITokenProvider.<GetAuthenticationHeaderAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.TokenCredentials.<ProcessHttpRequestAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.<ProcessHttpRequestAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.CosmosDB.Fluent.DatabaseAccountsOperations.<ListWithHttpMessagesAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.CosmosDB.Fluent.DatabaseAccountsOperationsExtensions.<ListAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.CosmosDB.Fluent.CosmosDBAccountsImpl.<>c__DisplayClass6_0.<<ListAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.PagedCollection`2.<>c__DisplayClass14_0.<<LoadPage>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.PagedCollection`2.<LoadPageWithWrapModelAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.PagedCollection`2.<LoadPage>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.PagedCollection`2.<LoadPage>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.CosmosDB.Fluent.CosmosDBAccountsImpl.<ListAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)
   at Microsoft.Azure.Management.CosmosDB.Fluent.CosmosDBAccountsImpl.List()
   at Microsoft.Azure.Management.CosmosDB.Fluent.CosmosDBAccountsImpl.Microsoft.Azure.Management.ResourceManager.Fluent.Core.CollectionActions.ISupportsListing<Microsoft.Azure.Management.CosmosDB.Fluent.ICosmosDBAccount>.List()
   at CloudSDKWrapper.AzureResourceStorage.GetDatabaseAccountInfoList(String location, UInt64 nBasicPropFlags, Int32 nExPropFlags)
   at CloudSDKWrapper.AzureStorage`2.GetDatabaseAccountInfoList(String location, UInt64 nBasicPropFlags, Int32 nExPropFlags)
   at CloudSDKWrapper.CAzureResourceWrapper.GetDatabaseAccountInfoList(String resourceGroup, UInt64 nBasicPropFlags, Int32 nExPropFlags)
   at CloudSDKCppBridge.CCloudSDKCppBridge.GetDatabaseAccountInfoList(CCloudSDKCppBridge* , basic_string<char\,std::char_traits<char>\,std::allocator<char> >* strResourceGroup, CosmosDBAccountBrowseType browseType, vector<CloudSDKCppBridge::SStorageAccountInfo\,std::allocator<CloudSDKCppBridge::SStorageAccountInfo> >* storageAccountList)

I'm currently using code like this to obtain fluent credentials in the MSI scenario, but have also tried the FromMSI() resulting in a different exception:

             m_fluentCredentials = Microsoft.Azure.Management.ResourceManager.Fluent.SdkContext.AzureCredentialsFactory.FromSystemAssignedManagedServiceIdentity(
                           MSIResourceType.AppService, m_azureEnvironment);
....
            Microsoft.Azure.Management.Fluent.Azure.IAuthenticated authenticatedResourceManager = Microsoft.Azure.Management.Fluent.Azure.Configure().Authenticate(m_fluentCredentials);
            Microsoft.Azure.Management.Fluent.IAzure resourceManagerCosmos = authenticatedResourceManager.WithSubscription(m_connection.GetSubscriptionId());
            var cosmosAccounts = resourceManagerCosmos.CosmosDBAccounts;
            var cosmosList = cosmosAccounts.List();
            foreach (var account in cosmosList)   // exception is thrown in this line, iterating through the list
            {
            ...

With MSI, what is the proper way to obtain the list of Cosmos DB accounts?  If it's just a matter of missing MSI_ENDPOINT, what does the code look like to set that value?

**Comment by weidongxu-microsoft** [comment]
@daveoshinsky 

Is it MSI in web or virtual machine?

`MSI_ENDPOINT` env variable should be set by the Azure on that webapp or vm. It is enabled like this https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/qs-configure-portal-windows-vm#enable-system-assigned-managed-identity-on-an-existing-vm

**Comment by daveoshinsky** [comment]
Hi Weidong,It's MSI on a virtual machine.  I've added my co-workers at Commvault in case they have more details on the VM setup.
GitHub issue with full details is here.
Thanks,Dave Oshinsky
    On Thursday, August 13, 2020, 09:57:30 PM EDT, Weidong Xu <notifications@github.com> wrote:  
 
 


@daveoshinsky

Is it MSI in web or virtual machine?

MSI_ENDPOINT env variable should be set by the Azure on that webapp or vm. It is enabled like this https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/qs-configure-portal-windows-vm#enable-system-assigned-managed-identity-on-an-existing-vm

**Comment by daveoshinsky** [comment]
MSI_ENDPOINT is not set in the environment on this Azure VM, which is setup for MSI.  Should that environment variable be set?

C:\Users\admin>set
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\admin\AppData\Roaming
CLIENTNAME=CVDV112FB4R
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=pjcappsql2019az
ComSpec=C:\windows\system32\cmd.exe
CV_Instance001=C:\Program Files\Commvault\ContentStore\Base
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
HOMEDRIVE=C:
HOMEPATH=\Users\admin
LOCALAPPDATA=C:\Users\admin\AppData\Local
LOGONSERVER=\\pjcappsql2019az
NUMBER_OF_PROCESSORS=2
OS=Windows_NT
Path=C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Users\admin\AppData\Local\Microsoft\WindowsApps;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=5504
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\PowerShell\Modules\
PUBLIC=C:\Users\Public
SESSIONNAME=RDP-Tcp#1
SystemDrive=C:
SystemRoot=C:\windows
TEMP=C:\Users\admin\AppData\Local\Temp\2
TMP=C:\Users\admin\AppData\Local\Temp\2
USERDOMAIN=pjcappsql2019az
USERDOMAIN_ROAMINGPROFILE=pjcappsql2019az
USERNAME=admin
USERPROFILE=C:\Users\admin
windir=C:\windows

C:\Users\admin>

**Comment by daveoshinsky** [comment]
We have 2 Azure VM's, both with MSI configured.  One is the VM used above to yield the environment.  Both VM's do NOT have MSI_ENDPOINT in the environment.  This issue looks relevant:  https://github.com/Azure/azure-functions-host/issues/2038

It appears that either:
1) I cannot use MSI credentials with Fluent API's on such a VM without MSI_ENDPOINT set
OR
2) I'm using the wrong SDK calls to do all of this.

Can you either:
1) Provide a clue as to how I can fix the problem where MSI_ENDPOINT isn't set on a VM with MSI configured
OR
2) Provide an alternative code sample showing how I'm supposed to do this.  The beginning of the issue describes the current code we're using.


The current code:
         m_fluentCredentials = Microsoft.Azure.Management.ResourceManager.Fluent.SdkContext.AzureCredentialsFactory.FromSystemAssignedManagedServiceIdentity(
                       MSIResourceType.AppService, m_azureEnvironment);

....
Microsoft.Azure.Management.Fluent.Azure.IAuthenticated authenticatedResourceManager = Microsoft.Azure.Management.Fluent.Azure.Configure().Authenticate(m_fluentCredentials);
Microsoft.Azure.Management.Fluent.IAzure resourceManagerCosmos = authenticatedResourceManager.WithSubscription(m_connection.GetSubscriptionId());
var cosmosAccounts = resourceManagerCosmos.CosmosDBAccounts;
var cosmosList = cosmosAccounts.List();
foreach (var account in cosmosList) // exception is thrown in this line, iterating through the list
{
...


Is this code wrong?  Or is the lack of MSI_ENDPOINT on a VM with MSI configured wrong?  How do I proceed using MSI on this VM with Fluent SDK?

**Comment by daveoshinsky** [comment]
The problem is in this code:
m_fluentCredentials = Microsoft.Azure.Management.ResourceManager.Fluent.SdkContext.AzureCredentialsFactory.FromSystemAssignedManagedServiceIdentity(
                       MSIResourceType.AppService, m_azureEnvironment);

Changing MSIResourceType.AppService to MSIResourceType.VirtualMachine is the fix.  This program is using the credentials to lookup Cosmos DB accounts, which soulds more like an AppService than a VirtualMachine.  But the credentials are being applied on a VirtualMachine.

**Comment by weidongxu-microsoft** [comment]
@daveoshinsky 
Oh yes, MSIResourceType.AppService is for webapp, the other option is for VirtualMachine. Glad it is solved.
