### ISSUE TITLE
Attempting to apply certificate for WebApp fails with 'NotFound' error

### ISSUE THREAD

**Issue by MaximG1234** [Azure/azure-libraries-for-net#1140]
**Describe the bug**
Attempting to apply a certificate to a WebApp will fail unless the original resource-group on which the AppService resided is used regardless of its current resource-group location. 

Using the following code I can successfully bind an SSL certificate to a WebApp as such: 

 ```

var webApp = await azure.WebApps.GetByIdAsync(request.WebAppId);

var createdCertificate = await azure
    .AppServices
    .AppServiceCertificates
    .Define($"{certificate.Thumbprint}##{webApp.Region.Name}#")
    .WithRegion(webApp.Region)
    .WithExistingResourceGroup(webApp.ResourceGroupName) 
    .WithPfxByteArray(certificate.Data)
    .WithPfxPassword(defaultPwd)
    .CreateAsync();

await webApp
    .Update()
    .DefineSslBinding()
    .ForHostname(request.Domain)
    .WithExistingCertificate(createdCertificate.Thumbprint)
    .WithSniBasedSsl()
    .Attach()
    .ApplyAsync();
```

however if I now move my AppService to a new resource-group this code will fail.

**To Reproduce**
Imagine the following scenario:

1. I have a WebApp hosted in Resource-Group [MyResourceGroup].
2. I move the WebApp from Resource-Group [MyResourceGroup] to [MyNewResourceGroup]
3. I now attempt to reissue certificate using above code and it will fail with 'NotFound' error.
4. If I now change the resource-group to which I upload the certificate as such: `.WithExistingResourceGroup("MyResourceGroup")` the SslBinding will succeed. 

***Exception or Stack Trace***

Operation returned an invalid status code 'NotFound'

   at Microsoft.Azure.Management.AppService.Fluent.WebAppsOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__352.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.AppService.Fluent.WebAppsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.AppService.Fluent.WebAppsOperationsExtensions.<CreateOrUpdateAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.AppService.Fluent.AppServiceBaseImpl`6.<CreateOrUpdateInnerAsync>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.AppService.Fluent.WebAppBaseImpl`5.<CreateResourceInternalAsync>d__279.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.AppService.Fluent.WebAppBaseImpl`5.<CreateResourceAsync>d__280.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.<Microsoft-Azure-Management-ResourceManager-Fluent-Core-ResourceActions-IResourceCreator<IResourceT>-CreateResourceAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.<ExecuteAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.<ExecuteNodeTaskAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.CreatableUpdatable`5.<ApplyAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WebTail.Cloud.Controllers.SSLController.<BindSSL>d__7.MoveNext() in C:\SourceControl\WebTail.Cloud\WebTail.Cloud\Controllers\SSLController.cs:line 204

**Comment by weidongxu-microsoft** [comment]
@MaximG1234 

Which version is the SDK? I remember it is fixed in latest version.

**Comment by MaximG1234** [comment]
My apologies, you're absolutely correct. I didn't see there was a newer version available. 

After updating the problem has resolved.

**Comment by MaximG1234** [comment]
Hmmm, unfortunately looks like I run into the issue again with the latest binaries.

I am now using versions 1.34 of Microsoft.Azure.Management.Fluent.dll and Microsoft.Azure.Management.AppService.Fluent.dll and can reproduce error. I can provide reproducible example if that helps.

**Comment by weidongxu-microsoft** [comment]
@MaximG1234

I got no problem with 1.34. I can run 

```
await webApp
   .Update()
   .DefineSslBinding()
   .ForHostname(request.Domain)
   .WithExistingCertificate(createdCertificate.Thumbprint)
   .WithSniBasedSsl()
   .Attach()
   .ApplyAsync();
```

successfully in resource group "javacsmrg2367", while certificate in group "rgnemv_39602c57eb3".

I didn't do any **moving** of the webapp before hand. I just created it in a different resource group.

If you still having issue, you can send detail to my email weidxu@microsoft.com

**Comment by MaximG1234** [comment]
@weidongxu-microsoft 

Thanks for the confirmation that you cannot reproduce.

I can definitely confirm that I ran into this problem running the latest versions of the assembly. I checked this by looking at `AppDomain.CurrentDomain.GetAssemblies();`.

I will have time to create a working example that I can send to you in the next few weeks. 

If you'd like to close the issue in the meantime that's fine, I can reopen if I am able to provide an example.
