### ISSUE TITLE
[BUG] Creating SQL Database by ImportFrom bacpac storage fails.

### ISSUE THREAD

**Issue by akrobet** [Azure/azure-libraries-for-net#1144]
**Describe the bug**
It's trying to find the resource instead of creating it.

***Exception or Stack Trace***
Microsoft.Rest.Azure.CloudException
  HResult=0x80131500
  Message=The Resource 'Microsoft.Sql/servers/testenv-westeurope/databases/CopierTest-03' under resource group 'testenv-westeurope' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
  Source=Microsoft.Azure.Management.Sql.Fluent
  StackTrace:
   at Microsoft.Azure.Management.Sql.Fluent.DatabasesOperations.<GetWithHttpMessagesAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.Sql.Fluent.DatabasesOperationsExtensions.<GetAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.Sql.Fluent.SqlDatabaseImpl.<GetInnerAsync>d__269.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.Sql.Fluent.SqlDatabaseImpl.<RefreshAsync>d__284.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.Sql.Fluent.SqlDatabaseImpl.<CreateResourceAsync>d__271.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.Sql.Fluent.SqlDatabaseImpl.<CreateAsync>d__282.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Portal.Copier.Infrastructure.DatabaseProvisioningService.<CreateFromPrincipalBackup>d__3.MoveNext() in C:\Workspace\portal-copier\Portal.Copier.Infrastructure\DatabaseProvisioningService.cs:line 61

  This exception was originally thrown at this call stack:
    [External Code]
    Portal.Copier.Infrastructure.DatabaseProvisioningService.CreateFromPrincipalBackup(string, string) in DatabaseProvisioningService.cs

`

**To Reproduce**
Run the snippet e.g. as a UnitTest.

***Code Snippet***

`            var database = await sqlServer.Databases.Define(databaseName)
                .ImportFrom(principalStorage)
                .WithStorageAccessKey(principalDatabaseStorageProvider.GetAccessKey())
                .WithSqlAdministratorLoginAndPassword("redacted", "password")
                .WithPremiumEdition(SqlDatabasePremiumServiceObjective.P1, SqlDatabasePremiumStorage.Max20Gb)
                .WithTags(new Dictionary<string, string>
                {
                                { "db_copy_state", "provisioning" },
                                { "dbrequester", requesterEmail },
                                { "dbcreated", DateTime.UtcNow.ToString("yyyy-MM-dd") }
                })
                .CreateAsync();`

**Expected behavior**
I expect the database to be created.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Visual Studio Professional 2019
 - Microsoft.Azure.Management.Fluent Version="1.34.0"
   Microsoft.Azure.Management.Sql.Fluent" Version="1.34.0"

**Additional context**
The creation works if I just create the empty database first, and Import data from the bacpac afterwards, however that way I cannot set the proper Collation.

**Comment by sbest-gcm** [comment]
Any update on this?

**Comment by ChenTanyi** [comment]
@akrobet @sbest-gcm I've tried with this flow. It seems there is a problem for import due to it will directly return rather than wait until the import done.
Here is some of the work around you could first try.
```csharp
try
{
// create flow
}
catch
{
    while (true)
    {
        db = server.Databases.Get("databaseName");
        if (db != null)
        {
            break;
        }
        Thread.Sleep(10 * 1000);
    }
}
```

Some information about this workaround. 
* Make sure your request parameters are correct. Otherwise the import request will fail, but not be reported.
* [The Import API](https://docs.microsoft.com/en-us/rest/api/sql/databases%20-%20import%20export/import#request-body) doesn't contain tags, which means the tags in creation don't take effect.


If you want to check about the import request, you could use the following method currently.
```csharp
var db = server.Databases.Define()
    .WithPremiumEdition()
    .Create()

db.ImportBacpac()
    .WithStorageAccessKey()
    .WithSqlAdministratorLoginAndPassword()
    .Execute();
```

**Comment by sbest-gcm** [comment]
@ChenTanyi I actually had the opposite problem. I wanted it to return immediately because one of our databases takes over an hour to restore and the request times out. That's the behavior I was seeing when I used `db.ImportBacpac().ExecuteAsync()` like in your example. 

I switched over to the methods listed in this issue and I get the behavior I want (creating the DB asynchronously) but it only works if the database has already been created:

```
await targetServer
    .Databases
    .Define(args.TargetDatabaseName)
    .CreateAsync();

await targetServer
    .Databases
    .Define(args.TargetDatabaseName)
    .ImportFrom(uri.ToString())
    .WithSharedAccessKey(sasToken)
    .WithSqlAdministratorLoginAndPassword(login.username, login.password)
    .CreateAsync();
```

So the bug I thought was what @akrobet mentioned, that you have to call `CreateAsync()` twice because `ImportFrom()` assumes the database you're "defining" already exists.

Doesn't help that the documentation doesn't describe expected behavior.

**Comment by ChenTanyi** [comment]
@sbest-gcm If you want to only call the import API and return, you could use `azure.SqlServers.Manager.Inner.Databases.BeginImportAsync` to do so.

Actually the `ImportFrom` doesn't need database are already exists. It would call the `import` API, and then the server will create the database after the import successful, which mean during that time, we could not check the DB import status, so the definition will fail due to it would need to return the DB.
