### ISSUE TITLE
[BUG] problem: PolicyAssignmentImpl does not expose .Inner.Parameters object. effect: cannot assign built in Azure Policies which take parameters

### ISSUE THREAD

**Issue by scottgorlick** [Azure/azure-libraries-for-net#1155]
**Describe the bug**
Simple Azure Policy Definitions that are built into Azure are not assignable with this SDK (trivially) because Policy Parameters are not exposed through the PolicyAssignmentImpl.

***Exception or Stack Trace***
```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Microsoft.Azure.Management.ResourceManager.Fluent.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Management.ResourceManager.Fluent.PolicyAssignmentsOperations.CreateWithHttpMessagesAsync(String scope, String policyAssignmentName, PolicyAssignmentInner parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.PolicyAssignmentsOperationsExtensions.CreateAsync(IPolicyAssignmentsOperations operations, String scope, String policyAssignmentName, PolicyAssignmentInner parameters, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.PolicyAssignmentImpl.CreateResourceAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.IResourceCreator<IResourceT>.CreateResourceAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.ExecuteNodeTaskAsync(DAGNode`1 node, CancellationToken cancellationToken)
   at My Code Entry Points Here...
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Hosting.HostingExtensions.<>c__DisplayClass1_0.<<UseHost>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass24_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__21_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseExceptionHandler>b__0>d.MoveNext()
```
**To Reproduce**
``` C#
var name = "name";
var policyDefinitionId = "/providers/Microsoft.Authorization/policyDefinitions/1e30110a-5ceb-460c-a204-c1c3969c6d62";
var scope = "/subscriptions/000 your sub id / etc... arm ID of policy assignment scope";

var assignment = await Azure!.PolicyAssignments.Define(name)
                .ForScope(scope)
                .WithPolicyDefinitionId(policyDefinitionId)
                .WithDefaultMode()
                .CreateAsync();
```

***Code Snippet***
above code reproduces the error... update to Impl object would allow proper fluent api use

**Expected behavior**
``` C#
var name = "name";
var policyDefinitionId = "/providers/Microsoft.Authorization/policyDefinitions/1e30110a-5ceb-460c-a204-c1c3969c6d62";
var scope = "/subscriptions/000 your sub id / etc... arm ID of policy assignment scope";
var parametersObject = new Dictionary<string, object>  // not sure which object type would be best here... the .Inner object takes object.
{
  { "paramName1", "value" }, 
  { "paramName2", "value" } 
};

var assignment = await Azure!.PolicyAssignments.Define(name)
                .ForScope(scope)
                .WithPolicyDefinitionId(policyDefinitionId)
                .WithDefaultMode()
                .WithParameters(parametersObject)
                .CreateAsync();
```

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] OS Independent (currently on Windows 10)
 - IDE : [e.g. IntelliJ] IDE Independent (using Visual Studio 2019)
 - Version of the Library used - Microsoft.Azure.Management.Fluent nuget pkg version 1.34

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Bug Description Added
- [ x] Repro Steps Added
- [ x] Setup information Added

**Comment by yungezz** [comment]
hi @scottgorlick thanks for reporting the issue. .net fluent sdk in maintain mode. new generation of .NET SDK is available at https://github.com/azure/azure-sdk-for-net . cc @nickzhums .

**Comment by nickzhums** [comment]
@scottgorlick Hi Scott, .NET Fluent SDK is currently in maintenance mode and development focus shifted to new generation of .NET SDK which can be found here: https://azure.github.io/azure-sdk/releases/latest/mgmt/dotnet.html

**Comment by scottgorlick** [comment]
Shouldn't the nuget paid packages be marked deprecated, then?

Please close... Will use other packages.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by scottgorlick** [comment]
Can you please point me to a migration path away from the deprecated libraries.  Documenation as current as 6/2020 show s how to use the Fluent Libraries:
https://docs.microsoft.com/en-us/dotnet/azure/authentication

**Comment by nickzhums** [comment]
@scottgorlick Scott sorry for not providing a clear message. As of right now the .NET Fluent SDK is not officially deprecated, that's why the packages are not yet marked as deprecated. Since we are moving towards the next generation of the SDK, this repo is in a low maintenance mode. Please look at the following doc that uses the new package to see if it's helpful for you
http://aka.ms/azsdk/dotnet/mgmt

Let us know if you have more questions
