### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vinuvinod** [Azure/azure-libraries-for-net#1157]
**Describe the bug**
I am trying trying to deploy the .war file to the appservice using azureInstance.WebApps.GetById(webAppId).Deploy().WithPackageUri(packageUrl)			.WithExistingDeploymentsDeleted(true).Execute(); but it always returns same error as pasted below.

***Exception or Stack Trace***
Source: Microsoft.Rest.ClientRuntime
Message: The operation was canceled.
InnerException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<<FillBufferAsync>g__InternalFillBufferAsync|215_0>d`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslStream.<ReadAsyncInternal>d__214`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpConnection.<FillAsync>d__87.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Http.HttpConnection.<ReadNextResponseHeaderLineAsync>d__84.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpConnection.<SendAsyncCore>d__53.MoveNext()
at Microsoft.Rest.RetryDelegatingHandler.<SendAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ProviderRegistrationDelegatingHandler.<SendAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.UserAgentDelegatingHandler.<SendAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__70.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.AppService.Fluent.WebAppsOperations.<BeginCreateMSDeployOperationWithHttpMessagesAsync>d__355.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.AppService.Fluent.WebAppsOperations.<CreateMSDeployOperationWithHttpMessagesAsync>d__67.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.AppService.Fluent.WebAppsOperationsExtensions.<CreateMSDeployOperationAsync>d__62.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.AppService.Fluent.AppServiceBaseImpl`6.<CreateMSDeploy>d__50.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.AppService.Fluent.WebDeploymentImpl`5.<ExecuteAsync>d__29.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Executable`1.Execute()

**To Reproduce**

***Code Snippet***
azureInstance.WebApps.GetById(webAppId).Deploy().WithPackageUri(packageUrl)			.WithExistingDeploymentsDeleted(true).Execute();

**Comment by weidongxu-microsoft** [comment]
@vinuvinod 

Would you try `WarDeploy`?

If you still fail, could you give us more details like SDK version, web app OS (windows or linux), sample of the link to war (it need public visible, you can redact it if needed).

**Comment by vinuvinod** [comment]
Hi @weidongxu-microsoft  I am using Windows as webapp OS and the sdk version is 1.34, and the war file is am taking it from storage account with a sas provided, and i have tried using IWebApp.WarDeploy am getting the same issue.

**Comment by weidongxu-microsoft** [comment]
@vinuvinod 

Would you re-check on the accessibility of the package? I seems having no trouble doing this:

```
            var webapp = azure.WebApps.Define("wa1-weidxu")
                .WithRegion(Region.USCentral)
                .WithExistingResourceGroup("rg-weidxu")
                .WithNewWindowsPlan(PricingTier.BasicB1)
                .WithJavaVersion(JavaVersion.V8Newest)
                .WithWebContainer(WebContainer.Tomcat8_5Newest)
                .WithHttpsOnly(true)
                .Create();

            webapp.Deploy()
                .WithPackageUri("https://sa1weidxu.blob.core.windows.net/container1/helloworld.war?sp=REDACT")
                .WithExistingDeploymentsDeleted(true)
                .Execute();
```

Also, if you can enable [logging](https://github.com/Azure/azure-libraries-for-net#logging) and attach the log, it will help a lot. Please have the bearer token redacted.
