### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by bjuraga** [Azure/azure-libraries-for-net#1189]
**Describe the bug**
Without a code change on our side, using v1.33.0 and calling .Refresh() on a WebApplication (IWebApp) we started to get the exception listed below. Updating to the latest version, v1.36.1 now throws the same exception but sooner, when getting the list of WebApps. 

***Exception or Stack Trace***
ArgumentException: Requested value 'ServiceTag' was not found.

**To Reproduce**
Steps to reproduce the behavior: Load the webapps in a subscription

***Code Snippet***
                var data = azure.WebApps.List().ToList();

**Expected behavior**
As in previous versions - get a list of web apps without a crash

**Screenshots**

**Setup (please complete the following information):**
 - OS: Win 10
 - IDE : VS2019 - latest
 - Version of the Library used: 1.36.1

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by weidongxu-microsoft** [comment]
@bjuraga 

Would you add some logging to let us know the last of few requests and responses?
https://github.com/Azure/azure-libraries-for-net#logging

We suspect some of your webapp might have certain configure that caused the bug, but our usual webapp in test env cannot reproduce.

**Comment by bjuraga** [comment]
I doubt anything outside of the sdk would be capable of influencing the sdk
and to which version of the azure rest api it is talking to. However, what
might be influencing versions is that my setup is using DRM and i
authenticate on one tenant but consume resources from another tenant. Is it
possible that tenants respond in different versions? i.e. the first tenant
is ahead and instructs your sdk to use v2 that expects a non nullable
service tag but the end tenant that lists web apps is returning v1 webapps
without a service tag?

**Comment by weidongxu-microsoft** [comment]
We would like to understand what's wrong of the webapp with service tag.

When you call `List`, it sends 3 types of REST API.
```
/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{name}
/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{name}/config/web
/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{name}/config/logs
```
None of above seems to have any issue with service tag. And we tried calling `var data = azure.WebApps.List().ToList();` on our test site (without any network security configured), and it works fine.

The service tag appears to be a virtual network / security feature. Hence we'd like to know the configure on your webapp (with networking) so we can try to reproduce on our site. Or you can get some logging and show us what might be the problem.

**Comment by bjuraga** [comment]
Here is the stack trace i get:

```
Microsoft.Rest.SerializationException
  HResult=0x80131500
  Message=Unable to deserialize the response.
  Source=Microsoft.Azure.Management.AppService.Fluent
  StackTrace:
   at Microsoft.Azure.Management.AppService.Fluent.WebAppsOperations.<GetConfigurationWithHttpMessagesAsync>d__42.MoveNext() in D:\a\1\s\src\ResourceManagement\AppService\Generated\WebAppsOperations.cs:line 7638
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.AppService.Fluent.WebAppsOperationsExtensions.<GetConfigurationAsync>d__37.MoveNext() in D:\a\1\s\src\ResourceManagement\AppService\Generated\WebAppsOperationsExtensions.cs:line 1086
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.AppService.Fluent.WebAppsImpl.<PopulateModelAsync>d__7.MoveNext() in D:\a\1\s\src\ResourceManagement\AppService\WebAppsImpl.cs:line 98
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.AppService.Fluent.WebAppsImpl.<<ListAsync>b__3_1>d.MoveNext() in D:\a\1\s\src\ResourceManagement\AppService\WebAppsImpl.cs:line 58
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.PagedCollection`2.<>c__DisplayClass21_0.<<AddCollection>b__0>d.MoveNext() in D:\a\1\s\src\ResourceManagement\ResourceManager\Core\PagedCollection.cs:line 126
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.PagedCollection`2.<AddCollection>d__21.MoveNext() in D:\a\1\s\src\ResourceManagement\ResourceManager\Core\PagedCollection.cs:line 126
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.PagedCollection`2.<LoadPageWithWrapModelAsync>d__16.MoveNext() in D:\a\1\s\src\ResourceManagement\ResourceManager\Core\PagedCollection.cs:line 74
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.AppService.Fluent.WebAppsImpl.<ListAsync>d__3.MoveNext() in D:\a\1\s\src\ResourceManagement\AppService\WebAppsImpl.cs:line 55
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function) in D:\a\1\s\src\ResourceManagement\ResourceManager\Core\Extensions.cs:line 53
   at Microsoft.Azure.Management.AppService.Fluent.WebAppsImpl.List() in D:\a\1\s\src\ResourceManagement\AppService\WebAppsImpl.cs:line 50
   --- MY CODE REMOVED ---
  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
JsonSerializationException: Error converting value "ServiceTag" to type 'System.Nullable`1[Microsoft.Azure.Management.AppService.Fluent.Models.IpFilterTag]'. Path 'properties.ipSecurityRestrictions[1].tag', line 1, position 3264.

Inner Exception 2:
ArgumentException: Requested value 'ServiceTag' was not found.
```

**Comment by bjuraga** [comment]
Noticing this (IpFilterTag) in the stack trace, it reminded me that we have few apps with ip filter for access restriction. Running my code against few different subscriptions that dont have any apps with access restrictions works as expected.
Hope this helps your repro.

**Comment by weidongxu-microsoft** [comment]
@bjuraga 

Thanks for your help. I think I get the cause. `IpFilterTag` added an additional enum value of `ServiceTag` in later service versions, which is not synced into SDK.

Preparing a fix.

**Comment by bjuraga** [comment]
Thanks for the fix, what is usually the timeframe to this fix being available on NuGet?

**Comment by weidongxu-microsoft** [comment]
Next release would be about 3 weeks later (around 29th Jan.).

**Comment by kolendomichal** [comment]
@weidongxu-microsoft when can we expect the release? 😄 
FunctionApp has an identical issue with ServiceTags
https://github.com/Azure/azure-cli/issues/16661|
That might be stupid questions, but it still worth asking.
Does the release of new azure-libraries-for-net fix a similar issue in function apps?
I know that Python is used there, but maybe it is correlated somehow?

**Comment by weidongxu-microsoft** [comment]
@kolendomichal 

Sorry for the delay, we are cranking some last minute change into the release (since in maintenance mode the release cycle is pretty long, so we try to get more into one).

1.37.0 is just released.

Yes, same issue existed for FunctionApp. It would be fixed by the PR as well.
