### ISSUE TITLE
[BUG] Forbidden Azure.AccessManagement.ActiveDirectoryApplications.GetByName

### ISSUE THREAD

**Issue by BartNetJS** [Azure/azure-libraries-for-net#1198]
When i call above function I got a Forbidden exception.
The ad client application has the following rights:

![image](https://user-images.githubusercontent.com/4865355/105865186-f4e05900-5ff2-11eb-8183-6b85f12b29de.png)

Access to other resources is fine (e.g. Vault, AppService,...)

***Exception or Stack Trace***

"Operation returned an invalid status code 'Forbidden'"

at Microsoft.Azure.Management.Graph.RBAC.Fluent.ApplicationsOperations.<ListWithHttpMessagesAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.Graph.RBAC.Fluent.ApplicationsOperationsExtensions.<ListAsync>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.Graph.RBAC.Fluent.ActiveDirectoryApplicationsImpl.<GetByNameAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)
   at Microsoft.Azure.Management.Graph.RBAC.Fluent.ActiveDirectoryApplicationsImpl.GetByName(String spn)

***Code Snippet***
var credentials = AzureCliCredentials.Create();

var azure = Azure
	.Configure()
	.WithLogLevel(HttpLoggingDelegatingHandler.Level.Basic)
	.Authenticate(credentials)
	.WithSubscription(subscritptionId);

azure.AccessManagement.ActiveDirectoryApplications.GetByName("[application name as registererd in AAD]");

**Comment by weidongxu-microsoft** [comment]
For .NET, the development focus has shifted to the next generation of Azure SDKs which follows the new SDK guideline and introduces a set of important new featuers. Those new packages are currently in preview state and we are actively working on making it production ready. You can visit this link here to see the latest .NET packages:

We have also published a few blog posts on why we are doing this: https://devblogs.microsoft.com/azure-sdk/october-2020-management-ga/ https://devblogs.microsoft.com/azure-sdk/introducing-new-previews-for-azure-management-libraries/

With this background, .NET Fluent is currently in a low maintenance mode, and we mostly do security and bug fixes. It is subject to deprecation in the future when the new set of .NET packages become Generally Available (GA). Please let us know if there are further questions, thanks!


This SDK still uses AAD Graph, hence you need to use the (legacy) Azure Active Directory permission (should be at the end of the Portal).

**Comment by BartNetJS** [comment]
Thanks for the quick response.
Does it mean that there will be also fluent implementation for the new sdk in the future?

**Comment by weidongxu-microsoft** [comment]
@BartNetJS 

This is not finalized, but the new Management SDK will likely not be fluent flavor, though it will still have good convenience layer over raw REST API to help user with resource provisioning.

For Microsoft Graph API, I think this is the most recent SDK https://github.com/microsoftgraph/msgraph-sdk-dotnet
(MS Graph is not part of Azure Management SDK. Current fluent SDK includes it mostly for user experience, i.e., it helps to use AAD to find the object ID of a service principal and then do RBAC with this object ID)

**Comment by BartNetJS** [comment]
That's too bad. I found that fluent API very nice and productive.

**Comment by nickzhums** [comment]
@BartNetJS we hear you, we will take this into account when we are designing the new API. The new SDK will be previewed around early this year at github.com/Azure/azure-sdk-for-net.

Question for you: what aspects of the fluent API do you like? and anything you don't like? this will help us in our product design , thanks!

**Comment by BartNetJS** [comment]
@nickzhums thank for taking this into account.

What I really like in the fluent API is after every operation dotting into possibilities and finally when you can create and return the resource. 
The fluent API is very verbose to understand what is possible.
In code you just 'read' what it is doing. It is also very easy for other developers to understand my code.

For example

          var webAPI = Azure.WebApps.Define(...)
                .WithExistingLinuxPlan(...)
                .WithExistingResourceGroup(...)
                .WithPrivateRegistryImage(...)
                .WithCredentials(...)
                .WithAppSettings(...)
                .WithSystemAssignedManagedServiceIdentity()
                .Create();

You can also explore the Azure... entry for example to see what's is in the box and play with it.
What I also like is the possibility to search for a azure resource in a resource group by name.

I'm using the Azure fluent API together with Cake to build and deploy applications via azure pipelines.
The benefit here is the local debugging possibility with [cake frosting](https://cakebuild.net/docs/running-builds/runners/cake-frosting) in C# together with the fluent azure api.
It makes me very productive and also able to debug pipelines locally (and makes my bosses happy ;-) )

Of course, there are a few things missing:
For example the access to Azure AD Applications (issue mentioned above).
Provisioning Application Insights.
using the 'az login' token from a aad personal account (currently this is only possible for a service principle (and the need for a client secret). It would be interesting to see the same possibilities we have now in  Azure.Identity like this:

        private static readonly TokenCredential _credential = new ChainedTokenCredential(
            new ManagedIdentityCredential(),
            new EnvironmentCredential(),
            new VisualStudioCredential(),
            new AzureCliCredential()) ;
Were you can choose which credential mechanisme to use.

**Comment by nickzhums** [comment]
@BartNetJS the new version of .NET SDK we are developing will be integrated with Azure Identity so you will be able to use the cred chain in the new .NET SDK.

Regarding fluent API, we are thinking of introducing a builder pattern in the SDK which is similar to Fluent but also follow the .NET conventions, might this be something you are looking for>?

**Comment by BartNetJS** [comment]
@nickzhums great to hear that the cred chain will be available in the new sdk.
And yes the builder pattern is also a fluent way to write code.
I'm happy to see this evolving. 
What is currently the timeframe for the SDK?

**Comment by nickzhums** [comment]
@BartNetJS  we are looking for previewing in the March, and officially GA in July/August

what kind of resource management scenarios are you guys current doing? (e.g. what are you using the SDK for ?)

**Comment by BartNetJS** [comment]
I'm using it in azure pipeline together with Cake (see [above](https://github.com/Azure/azure-libraries-for-net/issues/1198#issuecomment-769158231)).
We found that using ARM templates and yaml pipelines was very error prone and difficult to debug.
In the current implementation we can just debug regular C# code in Visual Studio for the azure pipelines on our local development machine.
It is very verbose and productive.

We are also providing an API platform (together with APIM) for internal API providers and are looking to provide CI/CD as a service to those API providers.
The Cake Frosting (C# implementation) together with azure resource sdk's is a good starting point for us.

**Comment by nickzhums** [comment]
@BartNetJS thanks for the detailed explanation! :) 

Yes definitely we are seeing more and more people have now turned to the SDK to manage the resources
