### ISSUE TITLE
 Operation returned an invalid status code 'Forbidden' when calling serviceprincipals from SDK

### ISSUE THREAD

**Issue by dondeetan** [Azure/azure-libraries-for-net#1212]
Using the following SDK:
Microsoft.Azure.Management.Graph.RBAC.Fluent
Microsoft.Azure.Management.Fluent.Azure.IAuthenticated

Whenever I call either:
  var spn = await _authenticated.ServicePrincipals.GetByNameAsync(name);
var spns = await _authenticated.ServicePrincipals.ListAsync();

**Microsoft.Azure.Management.Graph.RBAC.Fluent.Models.GraphErrorException: Operation returned an invalid status code 'Forbidden'**
   at Microsoft.Azure.Management.Graph.RBAC.Fluent.ApplicationsOperations.ListWithHttpMessagesAsync(ODataQuery`1 odataQuery, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Graph.RBAC.Fluent.ApplicationsOperationsExtensions.ListAsync(IApplicationsOperations operations, ODataQuery`1 odataQuery, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Graph.RBAC.Fluent.ActiveDirectoryApplicationsImpl.<ListAsync>b__14_0(CancellationToken cancellation)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.PagedCollection`2.LoadPageWithWrapModelAsync(Func`2 listInnerAsync, Func`3 listInnerNext, Func`3 wrapModelAsync, Boolean loadAllPages, CancellationToken cancellationToken)
 
Note sure what's going. The service principal that I use to make the call (IAuthenticated) has directory.readWrite.All and application.Readwrite.all to the azure tenant. Also calls to subscriptions and resource groups works: 

 var azure = await _authenticated.WithSubscription(subscription.id).ResourceGroups.ListAsync(); - WOrks! 
 var results =  await _authenticated.Subscriptions.ListAsync(); - Works! 

Thank you in advance

**Comment by dondeetan** [comment]
So, I figured out the problem. Essentially the SPN I'm using has all appropriate rights at the graph apis. However, I don't have the rights on Azure Active Directory APIs when adding api permissions. After I added these rights I no longer see the problem.

**Comment by weidongxu-microsoft** [comment]
Yes, it uses the legacy AAD graph API, not the MS graph.

**Comment by dondeetan** [comment]
Yes, I used that. The main issue is that for some reason, I can’t get service principal role assignments using the graph sdk. I can get all service principals but no role assignments. I had to call the azure management apis separately. Preferably, I would like to use just one sdk. 

Thank you
