### ISSUE TITLE
[BUG] `IWithMetricsQueryExecute` returns Bad Request

### ISSUE THREAD

**Issue by devdeer-alex** [Azure/azure-libraries-for-net#1232]
**Describe the bug**
Using the metrics query against an existing storage account always returns a "Bad Request" exception althoug the metric is found and the storage account has values in it.

***Exception or Stack Trace***
Exception message: "Operation returned an invalid status code 'BadRequest'"
Stack trace:
```
at Microsoft.Azure.Management.Monitor.Fluent.MetricsOperations.<ListWithHttpMessagesAsync>d__5.MoveNext() in D:\a\1\s\src\ResourceManagement\Monitor\Generated\MetricsOperations.cs:line 278
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
	at Microsoft.Azure.Management.Monitor.Fluent.MetricsOperationsExtensions.<ListAsync>d__0.MoveNext() in D:\a\1\s\src\ResourceManagement\Monitor\Generated\MetricsOperationsExtensions.cs:line 71
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	at Microsoft.Azure.Management.Monitor.Fluent.Models.MetricDefinitionImpl.<ExecuteAsync>d__52.MoveNext() in D:\a\1\s\src\ResourceManagement\Monitor\MetricDefinitionImpl.cs:line 90
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	at Microsoft.Azure.Management.Monitor.Fluent.Models.MetricDefinitionImpl.<Microsoft-Azure-Management-Monitor-Fluent-IWithMetricsQueryExecute-ExecuteAsync>d__25.MoveNext() in D:\a\1\s\src\ResourceManagement\Monitor\Domain\InterfaceImpl\Models\MetricDefinitionImpl.cs:line 199
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

**To Reproduce**

***Code Snippet***
```csharp
IAzure azureHandler = ...   
IStorageAccount resource = ...
// at this point I'm authenticated and I got the storage account handler
var definitions = await azureHandler.MetricDefinitions.ListByResourceAsync(resource.Id);
var metric = definitions.FirstOrDefault(d => d.Name.LocalizedValue.Equals("transactions", StringComparison.InvariantCultureIgnoreCase));
// write metric properties
Trace.WriteLine($"Id: {metric.Inner.Id}");
Trace.WriteLine($"Resource id: {metric.Inner.ResourceId}");
Trace.WriteLine($"Dimension required: {metric.Inner.IsDimensionRequired}");
Trace.WriteLine($"Dimensions: {string.Join(',', metric.Inner.Dimensions.Select(s => s.Value))}");
Trace.WriteLine($"Primary aggregation type: {metric.Inner.PrimaryAggregationType}");
Trace.WriteLine($"Supported aggregation types: {string.Join(',', metric.SupportedAggregationTypes.Select(s => s))}");
Trace.WriteLine($"Unit: {metric.Inner.Unit}");
Trace.WriteLine($"Supported retentions: {metric.Inner.MetricAvailabilities.Select(m => m.Retention)}");
Trace.WriteLine($"Supported time grains: {metric.Inner.MetricAvailabilities.Select(m => m.TimeGrain)}");
// at this point I retrieve a metric instance
var start = DateTime.Now.AddDays(-1);
var end = DateTime.Now;
var query = metric.DefineQuery()
	.StartingFrom(start)
	.EndsBefore(end)
	.WithAggregation(nameof(AggregationType.Total))
	.WithInterval(TimeSpan.FromMinutes(5));
// the next line results in an exception telling me "Operation returned an invalid status code 'BadRequest'"
await query.ExecuteAsync();
```

**Expected behavior**
According to the sample under [this link](https://github.com/Azure/azure-libraries-for-net/blob/master/Samples/Monitor/QueryMetricsAndActivityLogs.cs) this should work just fine.

**Screenshots**
Not applicable.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Visual Studio 2019 + NuGet
 - Version of the Library used 1.37.1

**Additional context**
Output of metric-properties:
```
Id: /subscriptions/[SUBID]/resourceGroups/rg-tim-probetag/providers/Microsoft.Storage/storageAccounts/stoddtimprobetag/providers/microsoft.insights/metricdefinitions/Transactions
Resource id: /subscriptions/[SUBID]/resourceGroups/rg-tim-probetag/providers/Microsoft.Storage/storageAccounts/stoddtimprobetag
Dimension required: False
Dimensions: ResponseType,GeoType,ApiName,Authentication
Primary aggregation type: Total
Supported aggregation types: Total
Unit: Count
Supported retentions: 93.00:00:00,93.00:00:00,93.00:00:00,93.00:00:00,93.00:00:00,93.00:00:00,93.00:00:00,93.00:00:00
Supported time grains: 00:01:00,00:05:00,00:15:00,00:30:00,01:00:00,06:00:00,12:00:00,1.00:00:00
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by weidongxu-microsoft** [comment]
@devdeer-alex A quick solution would be to use `DataTime.ToUniversalTime()` to `start` and `end`. It appears that service only recognize UTC without timezone.
