### ISSUE TITLE
Trying to authenticate - documentation links broken, options unclear

### ISSUE THREAD

**Issue by kierenj** [Azure/azure-libraries-for-net#124]
I'm trying to authenticate with Azure to dynamically scale SQL Azure databases.

There's a `FromUser` method on `AzureCredentialsFactory`, but the parameters are not explained and there are no examples (should qualify: that I can find).  I've guessed that Client ID in this case is some unique string, similar in function to a User-Agent header.  All I get when calling `Azure.Authenticate(...).WithDefaultSubscription()` on the returned object is:

```
Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in System.Private.CoreLib.dll: 'The given key was not present in the dictionary.'
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.<ProcessHttpRequestAsync>d__25.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.SubscriptionsOperations.<ListWithHttpMessagesAsync>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.SubscriptionsOperationsExtensions.<ListAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)
   at Microsoft.Azure.Management.ResourceManager.Fluent.SubscriptionsImpl.List()
   at Microsoft.Azure.Management.Fluent.Azure.Authenticated.WithDefaultSubscription()
```

Unfortunately, the documentation:

https://github.com/Azure/azure-libraries-for-net/blob/master/AUTH.md

1. Doesn't explain this method or params
2. Suggests `FromServicePrincipal`, then links to https://github.com/Azure/azure-libraries-for-net/blob/master/AUTH.md#creating-a-service-principal-in-azure which doesn't exist

If I don't want to use the file-based approach ("an experimental feature that may or may not be available in later releases"), please, any tips?

**Comment by hovsepm** [comment]
@kierenj you can find authentication information on here - https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-authentication-scenarios

**Comment by hovsepm** [comment]
@jianghaolu could you take a look to number 2 above? this is also broken in Java auth.md file.

**Comment by jianghaolu** [comment]
@kierenj 
The client ID is the standard oauth2 client identifier. If you create an application in the Active Directory, you have the client ID and the secret, just like any other oauth2 service you've used.
Tenant ID is the unique ID matching your email domain - the easiest way to find the ID for me is to use the graph explorer: https://developer.microsoft.com/en-us/graph/graph-explorer and run query "https://graph.microsoft.com/v1.0/organization/".

I'll add more explanations to the auth file. Thanks for your feedback.

**Comment by kierenj** [comment]
Ok - so out of interest is there a way to authenticate with standard portal user credentials?

**Comment by jianghaolu** [comment]
At this moment (Jan 2018) you will need to create an auth file - which can be done in the Cloud Shell in the portal.

A solution is being developed here https://github.com/AzureAD/microsoft-authentication-library-for-dotnet to enable unified login - as long as you are logged in Visual Studio, Azure PowerShell, *or* Azure CLI, you are logged in the SDK locally. Managed service identities will take over the authentication when the application is deployed to Azure.

**Comment by kierenj** [comment]
Just a quick note that the "service principal registration" link is still linking nowhere.
