### ISSUE TITLE
[BUG] Key Vault update is failing. The 'PublicNetworkAccess' property can not be empty

### ISSUE THREAD

**Issue by r4hulp** [Azure/azure-libraries-for-net#1258]
**Description**
When you get a key vault resource (using `client.GenericResources.GetById(resourceId);`) and try to update it, it throws the following error. 
`The 'PublicNetworkAccess' property can not be empty. Please specify an authorized value.`

This has been happening with **Microsoft.Azure.Management.Fluent** library as well as the REST API endpoint to update the Azure Key Vault. After fiddling around in network traces, I managed to figure out the exact reason why is it failing. The culprit is the new `api-version=2021-06-01-preview`

**Steps to reproduce**

#### 1. With REST API - 

Try to update the key vault with `api-version=2021-06-01-preview`

URL - `PUT https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/sample-resource-group/providers/Microsoft.KeyVault/vaults/sample-vault?api-version=2021-06-01-preview`

Example Body - 
```
{
"properties": {
"sku": {
"family": "A",
"name": "standard"
},
"tenantId": "<tenant_id>",
"accessPolicies": [],
"enabledForDeployment": true,
"enabledForTemplateDeployment": true,
"vaultUri": "https://<vault_id>.vault.azure.net/",
"provisioningState": "Succeeded"
},
"location": "westeurope",
"tags": {
"Custom_Tag": "Value",
"Status": "Active",
}
}
```

the API endpoint will return 400 Bad Request with the following error - 

```
{
    "error": {
        "code": "BadRequest",
        "message": "The 'PublicNetworkAccess' property can not be empty. Please specify an authorized value."
    }
}
```

But when you send the exact same HTTP request with any previous `api-version`. e.g. `2021-04-01-preview`, the endpoint works just fine. 

#### 2. With Azure Resource Manager Fluent API - 

1. Get a Key Vault Resource
`IGenericResource resource = client.GenericResources.GetById(resourceId);` - Notice the API Version (`resource.ApiVersion`) being returned by this method, it is set to **`2021-06-01-preview`**
2. Update the Key Vault (e.g. in my case, I updated with set of custom tags).
```
 var result = await resource.Update()
							.WithApiVersion(resource.ApiVersion)
							.WithProperties(resource.Properties)
							.WithTags(resourceNewTags).ApplyAsync();

```

***Exception or Stack Trace***
 ```
at Microsoft.Azure.Management.ResourceManager.Fluent.ResourcesOperations. 
 <BeginCreateOrUpdateWithHttpMessagesAsync>d__22.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourcesOperations. 
 <CreateOrUpdateWithHttpMessagesAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourcesOperationsExtensions. 
 <CreateOrUpdateAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.GenericResourceImpl.<CreateResourceAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.<Microsoft-Azure-Management- 
 ResourceManager-Fluent-Core-ResourceActions-IResourceCreator<IResourceT>-CreateResourceAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.<ExecuteAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1. 
 <ExecuteNodeTaskAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.CreatableUpdatable`5.<ApplyAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at SensitiveInformation.ClassName.<AddOrUpdateResourceTags>d__6.MoveNext() in C:\hidden_sensitive_information\class_name.cs:line 204
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SensitiveInformation.ClassName.<Method_Name>d__14.MoveNext() in C:\hidden_sensitive_information\class_name.cs:line 201
```

***Code Snippet***
```
await resource.Update()
.WithApiVersion(resource.ApiVersion)
.WithProperties(resource.Properties)
.WithTags(resourceNewTags).ApplyAsync();

```

**Expected behavior**
The latest endpoint with `2021-06-01-preview` should work exactly like the previous API version for Fluent API

**Setup (please complete the following information):**
Library - **Microsoft.Azure.Management.Fluent** v 1.37.1
Rest API - **api-version=2021-04-01-preview**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by weidongxu-microsoft** [comment]
Loop in service on question of why `PublicNetworkAccess` now becomes a required property (while it is not required in either `VaultProperties` nor `VaultPatchProperties` in swagger https://github.com/Azure/azure-rest-api-specs/blob/main/specification/keyvault/resource-manager/Microsoft.KeyVault/preview/2021-06-01-preview/keyvault.json#L1312-L1321).

**Comment by weidongxu-microsoft** [comment]
Generally it is suggested to fix the `api-version` when interacting with `GenericResource`. Though in theory service is backward compatible, but in many case it does not.

**Comment by r4hulp** [comment]
@weidongxu-microsoft  - not sure if these comments are directed towards me or your team.

**Comment by weidongxu-microsoft** [comment]
@r4hulp It is about the usage of the `GenericResource`.

BTW, new .NET SDK will get previewed at https://azure.github.io/azure-sdk/releases/latest/mgmt/dotnet.html, about the end of August.

**Comment by r4hulp** [comment]
I don't understand one thing though, why is the property `publicNetworkAccess` not being set by default while creating the Key Vault resource if it is supposed to be a required field?

**Comment by weidongxu-microsoft** [comment]
@r4hulp If you create the vault on Portal, and in last step click "download template", you can see it is created via "2018-02-14" api-version, which does not contain this `publicNetworkAccess ` in the first place.

```
{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "name": {
            "type": "string"
        },
        "location": {
            "type": "string"
        },
        "sku": {
            "type": "string"
        },
        "accessPolicies": {
            "type": "array"
        },
        "tenant": {
            "type": "string"
        },
        "enabledForDeployment": {
            "type": "bool"
        },
        "enabledForTemplateDeployment": {
            "type": "bool"
        },
        "enabledForDiskEncryption": {
            "type": "bool"
        },
        "enableRbacAuthorization": {
            "type": "bool"
        },
        "enableSoftDelete": {
            "type": "bool"
        },
        "softDeleteRetentionInDays": {
            "type": "int"
        },
        "networkAcls": {
            "type": "object"
        }
    },
    "variables": {},
    "resources": [
        {
            "apiVersion": "2018-02-14",
            "name": "[parameters('name')]",
            "location": "[parameters('location')]",
            "type": "Microsoft.KeyVault/vaults",
            "properties": {
                "enabledForDeployment": "[parameters('enabledForDeployment')]",
                "enabledForTemplateDeployment": "[parameters('enabledForTemplateDeployment')]",
                "enabledForDiskEncryption": "[parameters('enabledForDiskEncryption')]",
                "enableRbacAuthorization": "[parameters('enableRbacAuthorization')]",
                "accessPolicies": "[parameters('accessPolicies')]",
                "tenantId": "[parameters('tenant')]",
                "sku": {
                    "name": "[parameters('sku')]",
                    "family": "A"
                },
                "enableSoftDelete": "[parameters('enableSoftDelete')]",
                "softDeleteRetentionInDays": "[parameters('softDeleteRetentionInDays')]",
                "networkAcls": "[parameters('networkAcls')]"
            },
            "tags": {},
            "dependsOn": []
        }
    ],
    "outputs": {}
}
```

**Comment by r4hulp** [comment]
> @r4hulp If you create the vault on Portal, and in last step click "download template", you can see it is created via "2018-02-14" api-version, which does not contain this `publicNetworkAccess` property/feature in the first place.
> 
> ```
> {
>     "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
>     "contentVersion": "1.0.0.0",
>     "parameters": {
>         "name": {
>             "type": "string"
>         },
>         "location": {
>             "type": "string"
>         },
>         "sku": {
>             "type": "string"
>         },
>         "accessPolicies": {
>             "type": "array"
>         },
>         "tenant": {
>             "type": "string"
>         },
>         "enabledForDeployment": {
>             "type": "bool"
>         },
>         "enabledForTemplateDeployment": {
>             "type": "bool"
>         },
>         "enabledForDiskEncryption": {
>             "type": "bool"
>         },
>         "enableRbacAuthorization": {
>             "type": "bool"
>         },
>         "enableSoftDelete": {
>             "type": "bool"
>         },
>         "softDeleteRetentionInDays": {
>             "type": "int"
>         },
>         "networkAcls": {
>             "type": "object"
>         }
>     },
>     "variables": {},
>     "resources": [
>         {
>             "apiVersion": "2018-02-14",
>             "name": "[parameters('name')]",
>             "location": "[parameters('location')]",
>             "type": "Microsoft.KeyVault/vaults",
>             "properties": {
>                 "enabledForDeployment": "[parameters('enabledForDeployment')]",
>                 "enabledForTemplateDeployment": "[parameters('enabledForTemplateDeployment')]",
>                 "enabledForDiskEncryption": "[parameters('enabledForDiskEncryption')]",
>                 "enableRbacAuthorization": "[parameters('enableRbacAuthorization')]",
>                 "accessPolicies": "[parameters('accessPolicies')]",
>                 "tenantId": "[parameters('tenant')]",
>                 "sku": {
>                     "name": "[parameters('sku')]",
>                     "family": "A"
>                 },
>                 "enableSoftDelete": "[parameters('enableSoftDelete')]",
>                 "softDeleteRetentionInDays": "[parameters('softDeleteRetentionInDays')]",
>                 "networkAcls": "[parameters('networkAcls')]"
>             },
>             "tags": {},
>             "dependsOn": []
>         }
>     ],
>     "outputs": {}
> }
> ```

Understood, but then `apiVersion` in the code below should be consistent with the API version the resource was created.
```
IGenericResource resource = client.GenericResources.GetById(resourceId);
string apiVersion = resource.ApiVersion
```

I created a new Key Vault in Portal, went to export template, it has API Version `2021-04-01-preview` (see the image below) - 
![image](https://user-images.githubusercontent.com/292704/129870513-26292abb-5371-40fe-bcb5-44b5138f6a2f.png)

However the `client.GenericResources.GetById(resourceId);` has API Version `2021-06-01-preview`

![image](https://user-images.githubusercontent.com/292704/129870474-bed05eec-8fea-439f-8c4a-8e62be026c8a.png)

Does `GetById(resourceId)` always returns latest and greatest ApiVersion? If yes, is there any way to know which API Version the resource was created with?

**Comment by weidongxu-microsoft** [comment]
@r4hulp This is the reason I was suggesting to provide the `apiVersion` to `GetById` in the first place (or provide it to `Update` later).

Without user providing the `api-verison`, SDK would had to go find one. Generally it has only one choice: take the latest version, which is "2021-06-01-preview" for vault. (Some later version of API would have another option to take a default version, which is "2019-09-01" for vault).

If you are using the `GenericResource` API, generally it is up to you to provide the `api-version` to SDK.

If you know it is vault, you can go with `Vault` API, which do know the `api-version`.

**Comment by r4hulp** [comment]
> @r4hulp This is the reason I was suggesting to provide the `apiVersion` to `GetById` in the first place (or provide it to `Update` later).
> 
> Without user providing the `api-verison`, SDK would had to go find one. Generally it has only one choice: take the latest version, which is "2021-06-01-preview" for vault. (Some later version of API would have another option to take a default version, which is "2019-09-01" for vault).
> 
> If you are using the `GenericResource` API, generally it is up to you to provide the `api-version` to SDK.
> 
> If you know it is vault, you can go with `Vault` API, which do know the `api-version`.

That's a problem, we don't know if it is a vault, we loop through all the available resources in the resource group and apply one custom tag to them dynamically.

Since the `GenericResource` API started returning `2021-06-01-preview`, it is breaking while updating the key-vault resource because we are deploying the resource using the default API version. What would you suggest in this case?

**Comment by weidongxu-microsoft** [comment]
@r4hulp 
When the new SDK gets out, you should be able to do the tagging on the dedicated APIs. https://docs.microsoft.com/en-us/rest/api/resources/tags

**Comment by weidongxu-microsoft** [comment]
If you still need to stick with current SDK for some time, you can try this (which do a PATCH):

```
            var ret = azure.GenericResources.Manager.Inner.Resources.UpdateByIdAsync(resource.Id, resource.ApiVersion, new GenericResourceInner()
            {
                Tags = new Dictionary<String, String> {
                    { "a", "b" }
                }
            }).Result;
```

**Comment by r4hulp** [comment]
> If you still need to stick with the current SDK for some time, you can try this (which do a PATCH):
> 
> ```
>             var ret = azure.GenericResources.Manager.Inner.Resources.UpdateByIdAsync(resource.Id, resource.ApiVersion, new GenericResourceInner()
>             {
>                 Tags = new Dictionary<String, String> {
>                     { "a", "b" }
>                 }
>             }).Result;
> ```

The patch method also expects the `PublicNetworkAccess` property (which is weird in my opinion).

```{"error":{"code":"BadRequest","message":"The 'PublicNetworkAccess' property can not be empty. Please specify an authorized value."}}```

**Comment by weidongxu-microsoft** [comment]
@RandalliLama, @schaabs, @jlichwa
Please help check on keyvault service. A PATCH to key vault which only update tags should not cause this kind of 400 BadRequest. Even ARM would do this to update resource tag.

```
Request: PATCH https://management.azure.com/subscriptions/###/resourceGroups/rg-weidxu1/providers/Microsoft.KeyVault/vaults/kvweidxu112321?api-version=2021-06-01-preview
  body: {
  "tags": {
    "a": "b"
  }
}

Response:
{
  "error": {
    "code": "BadRequest",
    "message": "The 'PublicNetworkAccess' property can not be empty. Please specify an authorized value."
  }
}
```

**Comment by weidongxu-microsoft** [comment]
1.38.0 released
