### ISSUE TITLE
How to export the template of one resource?

### ISSUE THREAD

**Issue by StannieV** [Azure/azure-libraries-for-net#1271]
https://github.com/Azure/azure-libraries-for-net/blob/151496e1f28cad3759cb6861b975994aeb1e8196/src/ResourceManagement/ResourceManager/ResourceGroup/ResourceGroupImpl.cs#L99

Hi All,

I want to export all templates of my resource groups. My resource groups have more than 200 resources and returns the following error: **'Export template is not supported for resource groups that have more than '200' resources.'**

When I look into the Azure API documentation (https://docs.microsoft.com/en-us/rest/api/resources/resource-groups/export-template) it states that it is also possible to provide the: 'The IDs of the resources to filter the export by.'. Unfortunately, specifying the IDs is not supported in the library because it always specifies '*' in the code.

How can I export, with this library, a template per resource?

**Comment by weidongxu-microsoft** [comment]
For .NET, the development focus has shifted to the next generation of Azure SDKs which follows the new SDK guideline and introduces a set of important new features. Those new packages are currently in preview state and we are actively working on making it production ready. You can visit this link here to see the latest .NET packages:
https://devblogs.microsoft.com/azure-sdk/october-2020-management-ga/

We have also published a few blog posts on why we are doing this:
https://devblogs.microsoft.com/azure-sdk/introducing-new-previews-for-azure-management-libraries/

With this background, .NET Fluent is currently in a low maintenance mode, and we mostly do security and bug fixes. It is subject to deprecation in the future when the new set of .NET packages become Generally Available (GA). Please let us know if there are further questions, thanks!

**Comment by weidongxu-microsoft** [comment]
@StannieV 

You can call
```
azure.GenericResources.Manager.Inner.ResourceGroups.ExportTemplateAsync
```

This gives you all flexibility to the request object.

**Comment by StannieV** [comment]
> For .NET, the development focus has shifted to the next generation of Azure SDKs which follows the new SDK guideline and introduces a set of important new features. Those new packages are currently in preview state and we are actively working on making it production ready. You can visit this link here to see the latest .NET packages:
> https://devblogs.microsoft.com/azure-sdk/october-2020-management-ga/
> 
> We have also published a few blog posts on why we are doing this:
> https://devblogs.microsoft.com/azure-sdk/introducing-new-previews-for-azure-management-libraries/
> 
> With this background, .NET Fluent is currently in a low maintenance mode, and we mostly do security and bug fixes. It is subject to deprecation in the future when the new set of .NET packages become Generally Available (GA). Please let us know if there are further questions, thanks!

Thanks for pointing me in this direction. I would like to use the new library. While using it, I ran into an issue. When getting all resources in the resource group, I get the following exception:

System.ArgumentOutOfRangeException: Unknown SkuTier value. (Parameter 'value')
Actual value was Regional.
   at Azure.ResourceManager.Models.SkuTierExtensions.ToSkuTier(String value)
   at Azure.ResourceManager.Models.Sku.DeserializeSku(JsonElement element)
   at Azure.ResourceManager.Resources.GenericResourceData.DeserializeGenericResource(JsonElement element)
   at Azure.ResourceManager.Resources.Models.ResourceListResult.DeserializeResourceListResult(JsonElement element)
   at Azure.ResourceManager.Resources.ResourcesRestOperations.ListByResourceGroup(String resourceGroupName, String filter, String expand, Nullable`1 top, CancellationToken cancellationToken)
   at Azure.ResourceManager.Resources.GenericResourceContainer.<>c__DisplayClass14_0.<GetByResourceGroup>g__FirstPageFunc|0(Nullable`1 pageSizeHint)
   at Azure.Core.PageableHelpers.<>c__DisplayClass0_0`1.<CreateEnumerable>b__0(String continuationToken, Nullable`1 pageSizeHint)
   at Azure.Core.PageableHelpers.FuncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext()
   at Azure.Pageable`1.GetEnumerator()+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ConsoleApp20.Program.Main(String[] args) in ...

Is this a bug or is it something that I do wrong?:

According the [SkuTierExtensions file](https://github.com/Azure/azure-sdk-for-net/blob/cb614713c172609ff1680434042d962ada4d1e59/sdk/resourcemanager/Azure.ResourceManager/src/Generated/Models/SkuTier.Serialization.cs#L23), the value 'Regional' cannot be handled, But I don't think that I can control that.

My Code:              
```
ArmClient armClient = new ArmClient(credential);
Subscription subscription = await armClient.GetSubscriptions().GetAsync(subscriptionId);
ResourceGroup resourceGroup = await subscription.GetResourceGroups().GetAsync(resourceGroupName);

var genericResourcesByResourceGroup = subscription.GetGenericResources().GetByResourceGroup(resourceGroupName);

//The next line will produce an exception:
var temp = genericResourcesByResourceGroup.ToList();

foreach (var resource in temp)
{
	var export = await resourceGroup.ExportTemplateAsync(new ExportTemplateRequest { Resources = { resource.Id }, Options = "IncludeParameterDefaultValue,IncludeComments" });

	var templateJson = JsonConvert.SerializeObject(export.Value.Template, Formatting.Indented);
	Console.WriteLine(templateJson);
}
```

I use the following libraries:

    <PackageReference Include="Azure.Identity" Version="1.4.1" />
    <PackageReference Include="Azure.ResourceManager.Compute" Version="1.0.0-beta.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />

**Comment by StannieV** [comment]
Hi @weidongxu-microsoft, did you have time to look at my issue?

**Comment by weidongxu-microsoft** [comment]
@fengzhou-msft 

Hi Feng, could you take a look on the error above? It is the track2 SDK on resources.

If you want I can move it to azure-sdk-for-net.

**Comment by fengzhou-msft** [comment]
Please move to azure-sdk-for-net and we will triage the issue.
