### ISSUE TITLE
[BUG] NullReferenceExpcetion when removing user assigned identity

### ISSUE THREAD

**Issue by lklusek** [Azure/azure-libraries-for-net#1317]
**Describe the bug**
AppService has SystemAssignedIdentity and only one UserAssigned identity. When trying to remove SDK throws NullReferenceException.

***Exception or Stack Trace***
   at Microsoft.Azure.Management.AppService.Fluent.WebAppMsiHandler`5.HandleRemoveAllExternalIdentitiesCase(SitePatchResource siteUpdate)
   at Microsoft.Azure.Management.AppService.Fluent.WebAppMsiHandler`5.HandleExternalIdentities(SitePatchResource siteUpdate)
   at Microsoft.Azure.Management.AppService.Fluent.WebAppBaseImpl`5.<CreateResourceInternalAsync>d__279.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Azure.Management.AppService.Fluent.WebAppBaseImpl`5.<CreateResourceAsync>d__280.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.<Microsoft-Azure-Management-ResourceManager-Fluent-Core-ResourceActions-IResourceCreator<IResourceT>-CreateResourceAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.<ExecuteAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.<ExecuteNodeTaskAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.CreatableUpdatable`5.<ApplyAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApp1.Program.<Main>d__12.MoveNext() in C:\Users\lklusek\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 132

**To Reproduce**
1. Set SystemAssigned identity on AppService
2. Add UserAssigned identity
3. Try to remove identity using latest SDK 1.38.1 with the fluent `await appService.Update().WithoutUserAssignedManagedServiceIdentity(identity.Id).ApplyAsync()`

**Expected behavior**
Identity removed with success.

**Screenshots**
![image](https://user-images.githubusercontent.com/50724828/172179936-efc6cc5a-08cc-4321-8698-da5b31549c6f.png)

**Comment by weidongxu-microsoft** [comment]
It seems the code does not handle the system+user MSI type. I will see if I can fix. However the lib is in maintenance mode, we do not know when the next release will be.

Please plan migration to https://aka.ms/azsdk/dotnet/mgmt
The AppService SDK is not released yet.

**Comment by lklusek** [comment]
There is a workaround for this issue. Below you can find some sample code:

`        private async Task<bool> UnassignUserAssignedManagedServiceIdentityWorkaroundAsync(IAppServiceManager manager, SiteInner siteInner, IIdentity identity)
        {
            if (siteInner.Identity.UserAssignedIdentities.Count == 1)
            {
                siteInner.Identity.UserAssignedIdentities = null;

                if (siteInner.Identity.Type.Equals(ManagedServiceIdentityType.SystemAssignedUserAssigned))
                {
                    siteInner.Identity.Type = ManagedServiceIdentityType.SystemAssigned;
                }
            }
            else
            {
                var identityToRemove = siteInner.Identity.UserAssignedIdentities.Single(x =>
                    x.Key.Equals(identity.Id, StringComparison.OrdinalIgnoreCase));

                siteInner.Identity.UserAssignedIdentities.Remove(identityToRemove);
            }

            SiteInner result =
                await manager.WebApps.Inner.CreateOrUpdateAsync(siteInner.ResourceGroup,
                    siteInner.Name, siteInner);

            return result.Identity.UserAssignedIdentities.Any(x =>
                !x.Key.Equals(identity.Id, StringComparison.OrdinalIgnoreCase));
        }`

**Comment by weidongxu-microsoft** [comment]
Actually the new AppService is previewed
https://azure.github.io/azure-sdk/releases/latest/mgmt/dotnet.html
