### ISSUE TITLE
[BUG] Failed to get list of supported orchestrators

### ISSUE THREAD

**Issue by xinfli** [Azure/azure-libraries-for-net#1325]
**Describe the bug**
Code below raised exception "Microsoft.Rest.Azure.CloudException: Failed to get list of supported orchestrators"
```csharp
private Version getVersionList(IAzure client, IKubernetesCluster cluster )
{
    // ...
    var kubernetesVersions = client.KubernetesClusters.ListKubernetesVersions(cluster.Region);
    // ...
}
```
It started failing several days ago.

***Exception or Stack Trace***
```
Microsoft.Rest.Azure.CloudException: Failed to get list of supported orchestrators
   at Microsoft.Azure.Management.ContainerService.Fluent.ContainerServicesOperations.ListOrchestratorsWithHttpMessagesAsync(String location, String resourceType, Dictionary'2 customHeaders, CancellationToken cancellati onToken)
   at Microsoft.Azure.Management.ContainerService.Fluent.ContainerServicesOperationsExtensions.ListOrchestratorsAsync(IContainerServicesOperations operations, String location, String resourceType, CancellationToken can cellationToken)
   at Microsoft.Azure.Management.ContainerService.Fluent.KubernetesClustersImpl.ListKubernetesVersionsAsync(Region region, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func'l function)
   at Microsoft.Azure.Management.ContainerService.Fluent.KubernetesClustersImpl.ListKubernetesVersions(Region region)
   at Microsoft.Azure.Management.ContainerService.Fluent.KubernetesClustersImpl.Microsoft.Azure.Management.ContainerService.Fluent.IKubernetesClusters.ListKubernetesVersions(Region region)
   at XxxCompany.YyyProduct.Core.Services.UpgradeKubernetesControlnane.getLatestMinorVersionList(IAzure client, IKubernetesCluster cluster) in /home/vsts/work/l/s/XxxCompany.YyyProduct.Core/Services/NpgradeKubernetesControlPlane.cs
   at XxxCompany.YyyProduct.Core.Services.UpgradeKubernetesControlnane.Upgrade(IHangfireOutput output, IAzure client, String clusterName) in /home/vsts/work/1/s/XxxCompany.YyyProduct.Core/Services/UpgradeKubernetesControlPlane.cs
   at XxxCompany.YyyProduct.Core.Systemlobs.MaintainKubernetesClusterslob.RunWaitForNodeRoolsToBeCreated(PerformContext context, IHangfireOutput hangfireOutput, IAzure azureClient, MaintainKubernetesClustersjobParameters input) in /home/vsts/work/l/s/XxxCompany.YyyProduct.Core/Systemlobs/MaintainKubernetesClustersJob.cs

```

**Expected behavior**
Should get valid kubernetes versions

**Additional context**
Here is solution for the problem: https://docs.microsoft.com/en-us/answers/questions/932362/failed-to-get-list-of-supported-orchestrators-erro.html

It works when invoke the API directly, but the parameter "resource-type" is not public accessible with the Fluent library.

**Comment by xinfli** [comment]
Just noticed "This SDK is in maintenance mode"...

**Comment by weidongxu-microsoft** [comment]
https://github.com/Azure/azure-libraries-for-net/issues/1302

Seems the behavior of the service changed? Previously if no `"managedClusters"` provided, it will still have a list returned but not exactly for AKS.

**Comment by weidongxu-microsoft** [comment]
new lib here https://aka.ms/azsdk/dotnet/mgmt

**Comment by xinfli** [comment]
@weidongxu-microsoft  Yes, I think it's caused by changes of the API behavior, maybe the Azure SDK for .NET can handle it.

But migration to the new lib is too expensive for us, we changed the code to use API directly to fix the problem in our code.

And what does "maintenance mode" mean? will bug like this be fixed?

Thanks!

**Comment by weidongxu-microsoft** [comment]
@xinfli 
The linked issue above https://github.com/Azure/azure-libraries-for-net/issues/1302 should be the workaround for you, for this problem.

Currently it is "maintenance mode", we would still fix bugs (but this one seems do not have a satisfactory fix, as the API as it is no longer work, and if we change the parameters the API behavior would change).

It is likely get to "deprecated" in this year, and you may need to plan the migration sooner or later.
