### ISSUE TITLE
UWP - Cannot connect a second time

### ISSUE THREAD

**Issue by MystK** [Azure/azure-libraries-for-net#139]
When I first connect to Azure, everything works fine.

When I try to connect again, I get a "Value cannot be null" error.
![image](https://user-images.githubusercontent.com/7399140/35305572-9a93b476-004e-11e8-8cb1-484a9321d142.png)

````
            var client = "";
            var key = "";
            var tenant = "";
            var creds = new AzureCredentialsFactory()
                .FromServicePrincipal(
                client,
                key,
                tenant,
                AzureEnvironment.AzureGlobalCloud);

            var azure = Azure.Configure().Authenticate(creds).WithDefaultSubscription();

            var list = await azure.ResourceGroups.ListAsync();
            foreach (var item in list)
            {
                InfoTextBlock.Text = item.Name;
            }
````

**Comment by MystK** [comment]
Looks like if I clear the cache before, it works.

````
await ApplicationData.Current.ClearAsync();
````

**Comment by MystK** [comment]
I'm getting some odd but consistent behavior. Clearing the appdata using the command above allows it to work when I restart the app, but when I try it again in the same instance, I get the same error as my first message.

**Comment by AndrewJByrne** [comment]
I'm hitting the same issue. @MystK your tip about clearing the AppData, while not practical in production, helped to narrow this down for  me a little. It definitely seems as if something stored in the LocalSettings, in the **ActiveDirectoryAuthenticationLibrary**  ApplicationDataContainer instance is causing the issue when you try to connect a second time. 


I get the same ArgumentNullException and the stack trace doesn't reveal a whole lot to me:

This all happens locally. Using Fiddler, nothing goes across the wire when this happens. 
 ```
  at System.StubHelpers.HStringMarshaler.ConvertToNativeReference(String managed, HSTRING_HEADER* hstringHeader)
   at Windows.Security.Cryptography.CryptographicBuffer.ConvertStringToBinary(String value, BinaryStringEncoding encoding)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.CryptographyHelper.CreateSha256Hash(String input)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.LogReturnedToken(AuthenticationResult result)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.PostRunAsync(AuthenticationResult result)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.RunAsync()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenForClientCommonAsync(String resource, ClientKey clientKey)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenAsync(String resource, ClientCredential clientCredential)
   at Microsoft.Rest.Azure.Authentication.Internal.MemoryApplicationAuthenticationProvider.AuthenticateAsync(String clientId, String audience, AuthenticationContext context)
   at Microsoft.Rest.Azure.Authentication.ApplicationTokenProvider.LoginSilentAsync(String domain, String clientId, IApplicationAuthenticationProvider authenticationProvider, ActiveDirectoryServiceSettings settings, TokenCache cache)
   at Microsoft.Rest.Azure.Authentication.ApplicationTokenProvider.LoginSilentAsync(String domain, ClientCredential credential, ActiveDirectoryServiceSettings settings, TokenCache cache)
   at Microsoft.Rest.Azure.Authentication.ApplicationTokenProvider.LoginSilentAsync(String domain, String clientId, String secret, ActiveDirectoryServiceSettings settings, TokenCache cache)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourceGroupsOperations.ListWithHttpMessagesAsync(ODataQuery`1 odataQuery, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourceGroupsOperationsExtensions.ListAsync(IResourceGroupsOperations operations, ODataQuery`1 odataQuery, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourceGroupsImpl.<>c__DisplayClass19_0.<<ListAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.PagedCollection`2.LoadPageWithWrapModelAsync(Func`2 listInnerAsync, Func`3 listInnerNext, Func`3 wrapModelAsync, Boolean loadAllPages, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.PagedCollection`2.LoadPage(Func`2 listInnerAsync, Func`3 listInnerNext, Func`2 wrapModel, Boolean loadAllPages, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourceGroupsImpl.ListAsync(Boolean loadAllPages, CancellationToken cancellationToken)
   at utility_belt.Azure.AzureModel.ConnectAsync()


```
This is a UWP app using Microsoft.Azure.Management.Fluent **1.17.0** and Microsoft.Azure.Management.ResourceManager.Fluent **1.17.0**

I've tried WithDefaultSubscription(), although that value seems to always be null, and I've tried WithSubscription.  Once I Authenticate, I can't again until after a period of time (an hour?) 


If I'm using the API incorrectly, let me know. Otherwise, please advise on whether this is something we already know about and have a fix in mind.
