### ISSUE TITLE
Creating a SQL reource fails on macOS

### ISSUE THREAD

**Issue by wis3guy** [Azure/azure-libraries-for-net#209]
In a netcore1.1  console app, this snippet:

```c#
azure.SqlServers.Define(n)
   .WithRegion(region)
   .WithExistingResourceGroup(rg)
   .WithAdministratorLogin(sqlLogin)
   .WithAdministratorPassword(sqlPassword)
   .Create()
```
... works as advertised when run on Windows (f.ex. from Visual Studio), but on macOS the following exception is thrown:

```
Microsoft.Rest.SerializationException: Unable to deserialize the response. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
   at Microsoft.Azure.Management.Sql.Fluent.FirewallRulesOperations.<CreateOrUpdateWithHttpMessagesAsync>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Management.Sql.Fluent.FirewallRulesOperations.<CreateOrUpdateWithHttpMessagesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.Sql.Fluent.FirewallRulesOperationsExtensions.<CreateOrUpdateAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.Sql.Fluent.SqlFirewallRuleImpl.<CreateResourceAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.Sql.Fluent.SqlServerImpl.<>c__DisplayClass100_0.<<AfterPostRunAsync>b__4>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Management.Sql.Fluent.SqlServerImpl.<AfterPostRunAsync>d__100.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Management.Sql.Fluent.SqlServerImpl.<CreateResourceAsync>d__99.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.<Microsoft-Azure-Management-ResourceManager-Fluent-Core-ResourceActions-IResourceCreator<IResourceT>-CreateResourceAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.<ExecuteNodeTaskAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.Create()
   at ZooqBooq.Provisioning.Program.<>c__DisplayClass0_0.<Main>b__1(String n) in /Users/wis3guy/Projects/zooqbooq/src/netcore/Zooqbooq.Provisioning/Program.cs:line 80
   at ZooqBooq.Provisioning.Program.ProvisionResource[T](String name, Func`2 resourceFactory) in /Users/wis3guy/Projects/zooqbooq/src/netcore/Zooqbooq.Provisioning/Program.cs:line 217
```

The formatted response, received from Azure looks like this:

```xml


<?xml version="1.0" encoding="UTF-8"?>
<entry xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:georss="http://www.georss.org/georss" xmlns:gml="http://www.opengis.net/gml" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xml:base="https://management.westeurope.control.database.windows.net/v2/ManagementService.Trusted.svc/modules/ServerManagement/">
   <id>https://management.westeurope.control.database.windows.net/v2/ManagementService.Trusted.svc/modules/ServerManagement/firewallRules/AllowAllWindowsAzureIps</id>
   <category term="Microsoft.SqlServer.Management.Service.Domain.ArmResourceProvider.ServerFirewallRule" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
   <link rel="edit" title="ServerFirewallRule" href="firewallRules/AllowAllWindowsAzureIps" />
   <title />
   <updated>2018-03-08T12:30:34Z</updated>
   <author>
      <name />
   </author>
   <content type="application/xml">
      <m:properties>
         <d:id>/subscriptions/REDACTED/resourceGroups/zqbq-prod-1520512179-rg/providers/Microsoft.Sql/servers/zqbq-prod-1520512179-sql/firewallRules/AllowAllWindowsAzureIps</d:id>
         <d:name>AllowAllWindowsAzureIps</d:name>
         <d:type>Microsoft.Sql/servers/firewallRules</d:type>
         <d:location>West Europe</d:location>
         <d:kind>v12.0</d:kind>
         <d:properties m:type="Microsoft.SqlServer.Management.Service.Domain.ArmResourceProvider.ServerFirewallRule_ServerFirewallRuleProperties">
            <d:startIpAddress>0.0.0.0</d:startIpAddress>
            <d:endIpAddress>0.0.0.0</d:endIpAddress>
         </d:properties>
      </m:properties>
   </content>
</entry>


```

Obviously, the issue is that the response is `xml` rather than `json`.

**Comment by alxbog** [comment]
Experiencing the same behaviour.
.NET Core 2.

**Comment by alxbog** [comment]
It's also happens for `db.FirewallRules.List()` request.

**Comment by milismsft** [comment]
@alxbog I was able to reproduce the issue as well. I've contacted the SQL service team about this issue and I'm waiting on a resolution. So far it only reproduces when SQL Firewall rules respective REST API's are invoked.
@jaredmoo @nathannfan FYI this is the same issue we run into while running the SQL tests in a Docker container using .NET core.

**Comment by alxbog** [comment]
@milismsft Why is it working on Windows (full framework)? Is there any workaround?

**Comment by milismsft** [comment]
@alxbog I'm not sure at this moment... It could be that it works on Windows because the default is to use the 4.52 .NET runtime instead of the .NET Core. And though I checked the HTTP payloads that we send over to the service I was not able to notice any difference between the 2. It's puzzling why we run into this issue.

**Comment by milismsft** [comment]
I should add that at the core of this issue is that when making a REST call to the SQL Firewall Rule endpoints when using .NET core, the service returns the "body" result in XML format rather than the JSON format the SDK expects.

**Comment by alxbog** [comment]
@milismsft Yes, I understand the root cause of the issue. But may be if we figure out what's the difference between .NET Core and .NET 4.5.2 here, then we could try to workaround it.

**Comment by alxbog** [comment]
@hovsepm Tried to add latest Newtonsoft.Json 11.0.2 to the project. Same exception.

**Comment by hovsepm** [comment]
Fix is merged. Will be available in release 1.9.

**Comment by alxbog** [comment]
Thanks. When is it going to be released to Nuget?

**Comment by hovsepm** [comment]
@alxbog should be out early next week.

**Comment by alxbog** [comment]
1.9 is not yet in Nuget. I'll check it as soon as it will be there.

**Comment by alxbog** [comment]
@hovsepm It not on the Releases tab in Github also.

**Comment by hovsepm** [comment]
I had to unlist 1.9 from nuget due to a critical bug found after release. We are on the final stages of publishing 1.9.1. Sorry for false statement :)

**Comment by hovsepm** [comment]
@alxbog now it is available on Nuget.org.
