### ISSUE TITLE
Cannot create a Function App with a name, longer than 24 chars

### ISSUE THREAD

**Issue by wis3guy** [Azure/azure-libraries-for-net#211]
The below code fails if the _name_ of the function is longer than or exactly 24 chars. 

```c#
azure.AppServices.FunctionApps.Define("123456789_123456789_1234")
        .WithExistingAppServicePlan(asp)
        .WithExistingResourceGroup(rg)
        .WithoutPhp()
        .WithAppSetting("AzureWebJobsDashboard", storageConnectionString)
        .WithAppSetting("AzureWebJobsStorage", storageConnectionString)
        .WithAppSetting("ASPNETCORE_ENVIRONMENT", options.AspNetCoreEnvironment)
        .WithAppSetting("APPINSIGHTS_INSTRUMENTATIONKEY", instrumentationKey)
        .Create();
```

The thrown exception however implies that the account name of the storage account is longer than that limit, but that is _absolutely_ not the case.

```
'accountName' exceeds maximum length of '24'.
```

```
   at Microsoft.Azure.Management.Storage.Fluent.StorageAccountsOperations.<BeginCreateWithHttpMessagesAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Storage.Fluent.StorageAccountsOperations.<CreateWithHttpMessagesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Storage.Fluent.StorageAccountsOperationsExtensions.<CreateAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Storage.Fluent.StorageAccountImpl.<CreateResourceAsync>d__141.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.<Microsoft-Azure-Management-ResourceManager-Fluent-Core-ResourceActions-IResourceCreator<IResourceT>-CreateResourceAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.<ExecuteNodeTaskAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.AppService.Fluent.FunctionAppImpl.<CreateAsync>d__217.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)
   at ... my code goes here
```

**Comment by luthus** [comment]
I believe that's because a storage account will be created with the same name when that code is run. Storage account names allow a maximum of 24 characters. 

A possible work around could be to create a storage account separately with a name less than 24 characters in length. 

```csharp

var storageAccount = azure.StorageAccounts.Define("someStorageAccount")
    .WithRegion(region)
    .WithExistingResourceGroup(rg)
    .Create();

azure.AppServices.FunctionApps.Define("123456789_123456789_1234")
    .WithExistingAppServicePlan(asp)
    .WithExistingResourceGroup(rg)
    .WithExistingStorageAccount(storageAccount)
    .WithoutPhp()
    .WithAppSetting("AzureWebJobsDashboard", storageConnectionString)
    .WithAppSetting("AzureWebJobsStorage", storageConnectionString)
    .WithAppSetting("ASPNETCORE_ENVIRONMENT", options.AspNetCoreEnvironment)
    .WithAppSetting("APPINSIGHTS_INSTRUMENTATIONKEY", instrumentationKey)
    .Create();

```

**Comment by gorillapower** [comment]
I think this is the message when trying to provision a storage account for the related Function? AFAIK the Function name limit is 60 characters. I suspect there is an internal process that is creating a storage account for the function using the function name, and hence the error.

**Comment by gorillapower** [comment]
Any update on this? Is there a work around?

**Comment by gorillapower** [comment]
Hi guys, is there no response on this? We need this functionality.

**Comment by acehenry** [comment]
I am also having this issue, where my function app name is exactly 24 characters and I get the  "'accountName' exceeds maximum length of '24'" error message.  I will have to manually create sites until this is fixed. Thanks.

**Comment by JohnDoeKyrgyz** [comment]
I ran into the same issue with a functionapp that had a 24 character name. When I changed the name to something less than 24 characters it worked.
