### ISSUE TITLE
Support for Deployment Slots for Azure Functions

### ISSUE THREAD

**Issue by wis3guy** [Azure/azure-libraries-for-net#212]
It would be great to have deployment slots (preview) support for Azure functions.

**Comment by gorillapower** [comment]
Ive been following the samples for the WebApp to create a staging slot and it doesnt seem to be working for Azure Functions. Everytime i try and create a staging slot im gettting the following exception.

Ive tried this with the preview flag enabled for Azure Functions. Ive also tried creating a staging slot with and without AutoSwap enabled. Is there a workaround for this?

```
await funcApp
                .DeploymentSlots
                .Define(slotName)
                .WithConfigurationFromParent()
                //.WithAutoSwapSlotName("production")
                .CreateAsync();
```

`   at Microsoft.Azure.Management.AppService.Fluent.WebAppBaseImpl'5.<>c__DisplayClass230_0.<CreateResourceAsync>b__3(Task'1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask'2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.AppService.Fluent.WebAppBaseImpl'5.<CreateResourceAsync>d__230.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable'4.<Microsoft-Azure-Management-ResourceManager-Fluent-Core-ResourceActions-IResourceCreator<IResourceT>-CreateResourceAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem'1.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase'1.<ExecuteNodeTaskAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult()
   at EFframework.Azure.Management.MyApp.<CreateSlot>d__2.MoveNext() in C:\dev\EF\feature_em_functions\EFframework\Azure\Management\Provisioner.cs:line 77`

**Comment by gorillapower** [comment]
Any update on this? We want to start moving forward with our app development and this would be needed for our production version.

**Comment by gorillapower** [comment]
Is there no word on this or workaround?
