### ISSUE TITLE
The string '00:30:00' is not a valid TimeSpan value.

### ISSUE THREAD

**Issue by Edmund3** [Azure/azure-libraries-for-net#25]
When using the ISchedulerManager to work with Azure Scheduler and Collections and Jobs an error is raised when you provide a RetryPolicy.RetryInterval with an invalid TimeSpan on deserialisation from Azure. The actual operation is successful so this seems to just be an error during transit of the data.

Here is the stack trace:

```   
at System.Xml.XmlConvert.ToTimeSpan(String s)
   at Microsoft.Rest.Serialization.Iso8601TimeSpanConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
   at Microsoft.Azure.Management.Scheduler.Fluent.JobsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Scheduler.Fluent.JobsOperationsExtensions.<CreateOrUpdateAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at My code calling ISchedulerManager.Inner.Jobs.CreateOrUpdateAsync(...)
```

Here's some test code I setup which provides the error:

```
var client = Microsoft.Azure.Management.Scheduler.Fluent.SchedulerManager(AzureCreds, SubscriptionID);
var collection = await client.Inner.JobCollections.CreateOrUpdateAsync("rsg", "collection-1", new JobCollectionDefinitionInner()
                {
                    Location = "UK South",
                    Name = "collection-1",
                    Properties = new JobCollectionProperties()
                    {
                        Sku = new Sku(SkuDefinition.Standard),
                        State = JobCollectionState.Enabled
                    }
                });
                var job = await client.Inner.Jobs.CreateOrUpdateAsync("rsg", "collection-1", "job-1", new JobPropertiesInner()
                {
                    State = JobState.Enabled,
                    Action = new JobAction()
                    {
                        Type = JobActionType.Https,
                        Request = new HttpRequest()
                        {
                            Headers = new Dictionary<string, string>() { { "User-Agent", "Azure Scheduler" } },
                            Method = "POST",
                            Uri = "https://www.example.com"
                        },
                        RetryPolicy = new RetryPolicy()
                        {
                            RetryType = RetryType.Fixed,
                            RetryCount = 12,
                            RetryInterval = new TimeSpan(0, 30, 0)
                        },
                        ErrorAction = new JobErrorAction()
                        {
                            Type = JobActionType.Https,
                            Request = new HttpRequest()
                            {
                                Headers = new Dictionary<string, string>() { { "User-Agent", "Azure Scheduler" } },
                                Method = "POST",
                                Uri = "https://www.example.com"
                            }
                        }
                    },
                    Recurrence = new JobRecurrence()
                    {
                        Frequency = RecurrenceFrequency.Day
                    },
                    StartTime = message.StartDate
                });
```

**Comment by TimLovellSmith** [comment]
I bet this is because it expects a XML format timespan value like PT1M

**Comment by TimLovellSmith** [comment]
The REST API seems to state it works with ISO8601 though, so it is very strange? 
 https://docs.microsoft.com/en-us/rest/api/scheduler/Jobs/CreateOrUpdate

**Comment by milismsft** [comment]
The RetryInterval class type is Period (see org.joda.time.Period) and not TimeSpan. Can you try using an object of that type when initializing the RetryPolicy and see if the exception goes away?

**Comment by Edmund3** [comment]
This is strongly typed in the Microsoft.Azure.Management.Scheduler.Fluent.Models and there is no way for me to provide any other format

**Comment by hovsepm** [comment]
We do not support Microsoft.Azure.Management.Scheduler.Fluent anymore.

**Comment by TimLovellSmith** [comment]
@hovsepm are there other apis with type TimeSpan which would be affected by this though?

**Comment by Edmund3** [comment]
Why is the scheduler not being included in the fluent management API's? Is there some alternative I should be using?

**Comment by hovsepm** [comment]
please use - https://www.nuget.org/packages/Microsoft.Azure.Management.Scheduler
