### ISSUE TITLE
Use ConcurrentDictionary for credentialsCache

### ISSUE THREAD

**Issue by karataliu** [Azure/azure-libraries-for-net#255]
I'm operating with several different client using single AzureCredentials class instance.

Following error often come up when different clients make request in parallerl.
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.<ProcessHttpRequestAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourceGroupsOperations.<GetWithHttpMessagesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

If I turn to create new AzureCredentials  per client, then everything goes well.

Looks like the root cause is the dictionary in use is not thread safe:
https://github.com/Azure/azure-libraries-for-net/blob/Fluent-v1.8/src/ResourceManagement/ResourceManager/Authentication/AzureCredentials.cs#L71

Using ConcurrentDictionary should help.

**Comment by karataliu** [comment]
This even happens when using single client, but with concurrent call.

For example, If calling following function in two threads, the error may appear.
resourceGroup.GetByNameAsync

Similar issue logged: https://github.com/Azure/azure-libraries-for-net/issues/206

**Comment by hovsepm** [comment]
@karataliu this is by design - Azure Fluent SDK is not thread safe.

**Comment by karataliu** [comment]
ok, please also close #206 then

**Comment by ebashmakov** [comment]
@karataliu is there some kind of issue or challenge to make the SDK thread safe?

**Comment by karataliu** [comment]
I'm not the library author, but I think you amy refer to guidelines here:
https://docs.microsoft.com/en-us/dotnet/standard/threading/managed-threading-best-practices#recommendations-for-class-libraries

Basically typical class libaraies are not thread safe.
