### ISSUE TITLE
Help... what is the way to GET per-nic-public IP addresses?

### ISSUE THREAD

**Issue by TimLovellSmith** [Azure/azure-libraries-for-net#332]
Using the 'publicIpAddressConfiguration' property in the VM ScaleSet REST API, I can create IP configuration for my VM ScaleSet where each NIC has a public IP address. After reading the IP configuration, I can get the resource ID of each public IP (which are modeled as type 'SubResource'). But unfortunately I can't see what the actual IP address is.

Here is an example resource id, sub id changed:

`subscriptions/{test sub id}/resourceGroups/wus2_373_1af0ae3422ba4185aaad4a498f55fe5f/providers/Microsoft.Compute/virtualMachineScaleSets/wus2-373-1084808849/virtualMachines/0/networkInterfaces/nic1/ipConfigurations/internalipconfig/publicIPAddresses/pub1`

Should there be a 'list IP addresses' APi on the ip configuration which I get these with? (no such api)

Or am I supposed to be doing 'Get IP address' and pass it this resource ID, could that work?

Tim

**Comment by TimLovellSmith** [comment]
`IGenericResources.GetById(thatId)` to the rescue... not?

NotSupportedException: Get just by resource group and name is not supported. Please use other overloads.
   at Microsoft.Azure.Management.ResourceManager.Fluent.GenericResourcesImpl.GetInnerByGroupAsync(String groupName, String name, CancellationToken cancellation)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.GroupableResources`5.<GetByResourceGroupAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.GroupableResources`5.<GetByIdAsync>d__11.MoveNext()
--- End of stack trace from previous location

Oh come on.. how does that not work?!
