### ISSUE TITLE
[Graph.RBAC] JsonSerializationException on ListMember on AD Group

### ISSUE THREAD

**Issue by avantida** [Azure/azure-libraries-for-net#351]
Hi,

I just upgraded this package from 1.8.0 to 1.11.1 and when running I get this exception on executing `ListMembers` on a AD Group.

```
Newtonsoft.Json.JsonSerializationException
  HResult=0x80131500
  Message=Error setting value in extension data for type 'Microsoft.Azure.Management.Graph.RBAC.Fluent.Models.ServicePrincipalInner'. Path 'homepage', line 1, position 996.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetExtensionData(JsonObjectContract contract, JsonProperty member, JsonReader reader, String memberName, Object o)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
   at Microsoft.Azure.Management.Graph.RBAC.Fluent.ActiveDirectoryGroupImpl.WrapObjectInner(AADObjectInner inner)
   at Microsoft.Azure.Management.Graph.RBAC.Fluent.ActiveDirectoryGroupImpl.<ListMembers>b__22_3(AADObjectInner t)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at ConsoleApp2.Program.GetName(IGraphRbacManager manager, String objectId) in C:\Users\RudiLarno\Source\Repos\ConsoleApp2\ConsoleApp2\Program.cs:line 379
   at ConsoleApp2.Program.AuditKeyVaults(IAzure azure, Boolean executeDelete, TraceWriter log) in C:\Users\RudiLarno\Source\Repos\ConsoleApp2\ConsoleApp2\Program.cs:line 331
   at ConsoleApp2.Program.Main(String[] args) in C:\Users\RudiLarno\Source\Repos\ConsoleApp2\ConsoleApp2\Program.cs:line 55

Inner Exception 1:
ArgumentException: An item with the same key has already been added.
```
Note that when inspecting the AD Group using the Azure Portal UI, there are no duplicate entries as such.

https://github.com/Azure/azure-libraries-for-net/blob/948234d369535b62e3196ae55081e5d82f58efc8/src/ResourceManagement/Graph.RBAC/ActiveDirectoryGroupImpl.cs#L148

**Comment by LockTar** [comment]
We have the same error `An item with the same key has already been added. Key: homepage`. We where on v1.10 and updated it to 1.11.1 but still with the samen result.

We call the members of a group. It's not on every group but with few of them. I can't really figure out what the real problem is but I think it has something to do with service principals in a group. See issue #356 for simular issue with the same error message.

**Comment by olandese** [comment]
Any news about this error? I have the same error, it seems to happen when an AD Application has two keys (secrets) with the same name.

**Comment by anuchandy** [comment]
I think the issue @avantida hit is different from the issue that @LockTar and @olandese are seeing. It just that both issue throws the same exception but the root is different. 


 1. We are working on issue that @LockTar and @olandese are facing.
 2. @avantida we need some help from you, is there any chance you can share the log with us? this seems a deserialization issue and we want a payload to repro and fix this.

**Comment by anuchandy** [comment]
@LockTar hmm re-reading your comment, so the error you described here https://github.com/Azure/azure-libraries-for-net/issues/356 is thrown when we manipulate the de-serialized object [i.e. thrown AFTER DE-SERIALIZATION]. It seems you also hitting the exact same issue that @avantida facing, which happens DURING DE-SERIALIZATION. It will be helpful to have a payload that is causing this DE-SERIALIZATION failure.

**Comment by LockTar** [comment]
I'm not really in the position this week to give you something but what I experienced as well is that a MSI service principal in a group gives errors as well. Maybe related? I really think it has something to do with service principles in general.

**Comment by stefanstranger** [comment]
Hi @anuchandy maybe I can give you some more info on the issue from @LockTar because I'm working on the same project as @LockTar. I'll try to give you more info on the payload that is causing the de-serialization failure.

**Comment by LockTar** [comment]
Hi @anuchandy,
Back from holiday so sorry for the late response.

Here is the request and response of the error:
**Request**
`https://graph.windows.net/TENANTID/groups/GROUPID/members?api-version=1.6`

**Response**
`{
    "odata.metadata": "https://graph.windows.net/TENANTID/$metadata#directoryObjects",
    "value": [
        {
            "odata.type": "Microsoft.DirectoryServices.ServicePrincipal",
            "objectType": "ServicePrincipal",
            "objectId": "de584f4c-0830-41e9-aa74-74d5c38372cc",
            "deletionTimestamp": null,
            "accountEnabled": true,
            "addIns": [],
            "alternativeNames": [
                "isExplicit=False",
                "/subscriptions/SUBSCRIPTIONID/resourcegroups/Foo-ResourceGroup/providers/Microsoft.Web/sites/Foo-WebApp"
            ],
            "appDisplayName": null,
            "appId": "ccd300ea-7df5-4d40-ac4a-bf553dd0754e",
            "appOwnerTenantId": null,
            "appRoleAssignmentRequired": false,
            "appRoles": [],
            "displayName": "Foo-WebApp",
            "errorUrl": null,
            "homepage": null,
            "keyCredentials": [
                {
                    "customKeyIdentifier": null,
                    "endDate": "2018-09-18T21:33:00Z",
                    "keyId": "9fe92c69-d8d9-4fc4-8ff9-49d2a47069c8",
                    "startDate": "2018-06-20T21:33:00Z",
                    "type": "AsymmetricX509Cert",
                    "usage": "Verify",
                    "value": null
                },
                {
                    "customKeyIdentifier": null,
                    "endDate": "2018-08-03T20:14:00Z",
                    "keyId": "db035032-d2a3-420e-a131-573cd1ca6f2c",
                    "startDate": "2018-05-05T20:14:00Z",
                    "type": "AsymmetricX509Cert",
                    "usage": "Verify",
                    "value": null
                },
                {
                    "customKeyIdentifier": null,
                    "endDate": "2018-06-18T14:09:00Z",
                    "keyId": "a42b85de-c30c-43dc-bd32-7dd1d10f27a3",
                    "startDate": "2018-03-20T14:09:00Z",
                    "type": "AsymmetricX509Cert",
                    "usage": "Verify",
                    "value": null
                }
            ],
            "logoutUrl": null,
            "oauth2Permissions": [],
            "passwordCredentials": [],
            "preferredTokenSigningKeyThumbprint": null,
            "publisherName": null,
            "replyUrls": [],
            "samlMetadataUrl": null,
            "servicePrincipalNames": [
                "ccd300ea-7df5-4d40-ac4a-bf553dd0754e",
                "https://identity.azure.net/02WhMSsWHkGlXK/MMeBdl3Z/cBGOVKBfwIu6MuRFekc="
            ],
            "servicePrincipalType": "ServiceAccount",
            "signInAudience": null,
            "tags": [],
            "tokenEncryptionKeyId": null
        }
    ]
}`

**Error**
Newtonsoft.Json.JsonSerializationException: **Error setting value in extension data for type 'Microsoft.Azure.Management.Graph.RBAC.Fluent.Models.ServicePrincipalInner'. Path 'homepage', line 1**, position 1002. ---> System.ArgumentException: An item with the same key has already been added. Key: homepage
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary2.Add(TKey key, TValue value)
   at lambda_method(Closure , Object , Object[] )
   at Newtonsoft.Json.Serialization.DefaultContractResolver.<>c__DisplayClass32_1.<SetExtensionDataDelegates>b__0(Object o, String key, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetExtensionData(JsonObjectContract contract, JsonProperty member, JsonReader reader, String memberName, Object o)


The service principal is a **MSI** of App Service.

**Comment by hovsepm** [comment]
fix has been merged. Will be shipped as part of release 1.13.

**Comment by LockTar** [comment]
Any idea when this will be released? In #356 you said mid July... Thank you for all the good work!

**Comment by avantida** [comment]
@anuchandy 
Sorry for the late reply, holidays...

So how do I best take the log that you require?

**Comment by hovsepm** [comment]
@LockTar should be out mid next week.
@avantida the fix is merged actually but if you can post here the response JSON message (excluding all the sensitive data) that would be great for double-checking.

**Comment by avantida** [comment]
@hovsepm Attached the response of the ListMembers call.
[listmembers-response.log](https://github.com/Azure/azure-libraries-for-net/files/2196879/listmembers-response.log)

**Comment by hovsepm** [comment]
@avantida thanks for sharing the logs. I did run the test on your payload and the fix looks good - no exceptions anymore :).

**Comment by hovsepm** [comment]
Release 1.13 is out. Please upgrade your references.
