### ISSUE TITLE
Applying Acces Policiy for Key Vault fails with Forbidden

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-libraries-for-net#367]
Applying Acces Policiy for Key Vault fails with following exception:
> Operation returned an invalid status code 'Forbidden'

I'm curious to know what permissions are required because the service principle that is used to authenticate with was Contributor. After switching to Owner it still fails with the same error.

Service Principle that is being added does not have access to the resource group but this is not a requirement.

Some remarks/thoughts:
- Is this exception because it wants to query the Graph API of the Azure AD that it is part of because it does not have permissions for this?
- Can we document what permissions are required here, now one can only guess.

## Version
1.11.1

## Request Uri
`https://graph.windows.net/{removed}/servicePrincipals?$filter=displayName eq '{removed}'&api-version=1.6
```

## Response
```json
{
  "odata.error": {
    "code": "Authorization_RequestDenied",
    "message": {
      "lang": "en",
      "value": "Insufficient privileges to complete the operation."
    }
  }
}
```

## Stack Trace
Inner exception:
>    at Microsoft.Azure.Management.Graph.RBAC.Fluent.ServicePrincipalsOperations.<ListWithHttpMessagesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Graph.RBAC.Fluent.ServicePrincipalsOperationsExtensions.<ListAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Graph.RBAC.Fluent.ServicePrincipalsImpl.<GetByNameAsync>d__8.MoveNext()

Exception:
>   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Azure.Management.KeyVault.Fluent.VaultImpl.<>c__DisplayClass64_0.<PopulateAccessPolicies>b__1(Task`1 servicePrincipal)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.KeyVault.Fluent.VaultImpl.<PopulateAccessPolicies>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.KeyVault.Fluent.VaultImpl.<CreateResourceAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ...

**Comment by tomkerkhove** [comment]
Changed our approach to use `ForObjectId(objectId)` for now until this is resolved

**Comment by divyeshgohil85** [comment]
h

**Comment by ChrisGibson1982** [comment]
Did anyone establish what permissions were required to do this with an SPN?

**Comment by xccc-msft** [comment]
@ChrisGibson1982 Authorization_RequestDenied means you need to add permission for your app in Azure Active Directory Graph(under supported legacy APIs). The suggestion is to add basic Read.All permission for User/Directory/Group/Domain, etc. If these cannot solve your issue, then try to upgrade to ReadWrite.All.

**Comment by xccc-msft** [comment]
@tomkerkhove You can check above info and follow the steps if you still face this issue.

**Comment by tomkerkhove** [comment]
I'm no longer working on this so I can't try it, sorry!

**Comment by xccc-msft** [comment]
@ChrisGibson1982 As no update from your side, I will close this for now. Feel free to reopen if this persists on your end.
