### ISSUE TITLE
AzureCredentialsFactory.FromUser needs documentation/examples

### ISSUE THREAD

**Issue by MaxWilson** [Azure/azure-libraries-for-net#398]
I want to use .NET (F#) to manage Azure, instead of having to use Powershell or the Azure CLI or the Azure portal, and I want to do it as myself with my own permissions instead of having to set up a service principal that has the same permissions as me. It looks like AzureCredentialsFactory.FromUser may be what I'm looking for, but I must be using it wrong because it throws an auth exception. Here's my script snippet:

```  let mytenantId = "72f988bf-86f1-41af-91ab-2d7cd011db47"
  let myClientId = "4aa4d595-fdf3-4271-a995-ba13a7f60f0c" // ApplicationID from Azure portal, see screenshot
  let cred = SdkContext.AzureCredentialsFactory.FromUser("maxw@microsoft.com", pwd, myClientId, mytenantId, AzureEnvironment.AzureGlobalCloud)
  let azure = Azure.Configure().Authenticate(cred)
  printfn "%A" <| azure.ActiveDirectoryUsers.GetByName("coworker@microsoft.com")
```

![image](https://user-images.githubusercontent.com/6829565/42698598-3b198ccc-8673-11e8-9e11-08c9179ecd24.png)

Expected: some information about my coworker.

Actual: GetByName() throws authentication exception

```Unhandled Exception: Microsoft.Rest.Azure.Authentication.AuthenticationException: Authentication error while acquiring token: 'Federated service at https://msft.sts.microsoft.com/adfs/services/trust/13/usernamemixed returned error: ID3242: The security token could not be authenticated or authorized.'. ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: Federated service at https://msft.sts.microsoft.com/adfs/services/trust/13/usernamemixed returned error: ID3242: The security token could not be authenticated or authorized. ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpWebRequestWrapper.<GetResponseSyncOrAsync>d__2.MoveNext()
...
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)
   at Microsoft.Azure.Management.Graph.RBAC.Fluent.ActiveDirectoryUsersImpl.Microsoft.Azure.Management.ResourceManager.Fluent.Core.CollectionActions.ISupportsGettingByName<Microsoft.Azure.Management.Graph.RBAC.Fluent.IActiveDirectoryUser>.GetByName(String name)
   at Program.main(String[] argv) in d:\code\rse\azureManagement\azureManagement\azMan\Program.fs:line 32
```

Firstly, what is the correct usage? Secondly, why doesn't Authenticate() throw instead of waiting for the GetByName() call before throwing?

**Comment by jianghaolu** [comment]
Depending on the environment your code targets, if it's .NET standard you can login through the device code: https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/ResourceManager/Authentication/AzureCredentialsFactory.cs#L46.

@hovsepm Do you know a credentials class that can be used to login interactively on Windows .NET 4.x?

**Comment by hovsepm** [comment]
You will need to provide a delegate that will receive [DeviceCodeResult](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.devicecoderesult?view=azure-dotnet) and according to the provided Message user needs to take actions. it the delegate will return true then authentication will continue to wait until user will take actions described in the Message. Otherwise authentication will be terminated.

**Comment by MaxWilson** [comment]
Thanks! I'm hitting another auth error when I try to actually use the credential so generated, but I will file a separate issue for that and close this issue.
