### ISSUE TITLE
Fluent: NullReferenceException in VirtualMachineScaleSetImpl.LoadCurrentPrimaryLoadBalancersIfAvailable

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-libraries-for-net#44]
_From @TimLovellSmith on September 5, 2017 18:57_

I'm hitting an NRE in Fluent SDK 1.1.3. The scenario involves creating a VMSS with an internal load balancer only (no public facing load balancer), and then trying to update it with a custom script extension

                vmssWithLB = vmssWithVNet
                    .WithoutPrimaryInternetFacingLoadBalancer()
                    .WithExistingPrimaryInternalLoadBalancer(loadBalancer)
                    .WithPrimaryInternalLoadBalancerBackends(LoadBalancerResource.BackendName)
                    .WithPrimaryInternalLoadBalancerInboundNatPools(
                        LoadBalancerResource.NatPool130XXName,
                        LoadBalancerResource.NatPool150XXName,
                        LoadBalancerResource.NatPool160XXName,
                        LoadBalancerResource.NatPool330XXName);
```
vmss.Update().DefineNewExtension(extensionName)
                            .WithPublisher("Microsoft.Compute")
                            .WithType("CustomScriptExtension")
                            .WithVersion("1.8")
                            .WithPublicSetting("fileUris", new string[] { scriptBlobSasUri.AbsoluteUri })
                            .WithProtectedSetting("storageAccountName", tenantStorage.AccountName)
                            .WithProtectedSetting("storageAccountKey", tenantStorage.GetSecretKey())
                            .WithProtectedSetting("commandToExecute", commandToExecute)
                            .Attach().ApplyAsync();
```
Here is the stack trace:

```Exception in context VmScaleSetResource:wus943843. Details: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachineScaleSetImpl.LoadCurrentPrimaryLoadBalancersIfAvailable()
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachineScaleSetImpl.SetPrimaryIPConfigurationBackendsAndInboundNatPools()
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachineScaleSetImpl.<CreateInnerAsync>d__290.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.GroupableParentResource`8.<CreateResourceAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.<Microsoft-Azure-Management-ResourceManager-Fluent-Core-ResourceActions-IResourceCreator<IResourceT>-CreateResourceAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.<ExecuteNodeTaskAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.CreatableUpdatable`5.<ApplyAsync>d__3.MoveNext()```

_Copied from original issue: Azure/azure-sdk-for-net#3659_

**Comment by hovsepm** [comment]
_From @TimLovellSmith on September 5, 2017 19:33_

I am not sure what exactly is null. I do wonder if perhaps GetById using NetworkManager is returning null...

**Comment by hovsepm** [comment]
_From @TimLovellSmith on September 14, 2017 19:56_

Confirmed that this issue still exists in 1.2.0 too.

**Comment by anuchandy** [comment]
Looking at the initial comment, the scenario is - An existing VMSS is updated to use an internal load balancer. Came to know from Tim that this internal Load balancer and VMSS are in different subscriptions. This means application is retrieving the LB using a different Azure Client configured with different subscription.

When we retrieve the VMSS later, we try to retrieve the load balancer as well, since it is in the different subscription SDK return null for this. Trying to operate on this NULL cause NPE.

**Comment by anuchandy** [comment]
Came to know from Tim that the internal Load balancer and VMSS are in different subscriptions.

-- VMSS Create --
The application retrieved the LB using an Azure client configured with subscription1. Application is using another instance of Azure client configured with subscription2 to
create the VMSS. The retrieved fully blown LB is provided during VMSS defintion flow. VMSS creation successfully completed.

-- VMSS Update --
Later user is trying to update the VMSS (using second AzureClient), this time we try to retrieve the load balancer associated with the VMSS. Since LB is in a different subscription
LB GET return null, trying to operate on this NULL cause NPE.

We need to see whether we can avoid GETing LB and perform the logics without having fully blown LB object.
