### ISSUE TITLE
Adding/Removing VMs from Backend Pool in Load Balancer fails

### ISSUE THREAD

**Issue by sitereactor** [Azure/azure-libraries-for-net#492]
I have two load balancing rules (Port 80 + 443) for which I want to add or remove VMs from an Availability Set, but it doesn't appear to work and the result/outcome appears inconsistent.

```
            var vms = new List<IHasNetworkInterfaces>();
            var availabilitySet = azure.AvailabilitySets.GetByResourceGroup(resourceGroupName, availabilitySetName);
            var vmIds = availabilitySet.VirtualMachineIds;
            foreach (var id in vmIds)
            {
                var vm = azure.VirtualMachines.GetById(id);
                vms.Add(vm);
            }

            var lb = azure.LoadBalancers
                .Define(loadbalancerName)
                .WithRegion(Region.EuropeWest)
                .WithExistingResourceGroup(resourceGroupName)
                .DefineLoadBalancingRule(httpLoadBalancerRule)
                    .WithProtocol(TransportProtocol.Tcp)
                    .FromFrontend(frontendName)
                    .FromFrontendPort(80)
                    .ToBackend(httpBackendPool)
                    .WithProbe(httpProbe)
                    .Attach()
                .DefineLoadBalancingRule(httpsLoadBalancerRule)
                    .WithProtocol(TransportProtocol.Tcp)
                    .FromFrontend(frontendName)
                    .FromFrontendPort(443)
                    .ToBackend(httpsBackendPool)
                    .WithProbe(httpsProbe)
                    .Attach()
                .DefinePublicFrontend(frontendName)
                    .WithExistingPublicIPAddress(publicIpAddress)
                    .Attach()
                .DefineHttpProbe(httpProbe)
                    .WithRequestPath("/")
                    .WithPort(80)
                    .Attach()
                .DefineHttpProbe(httpsProbe)
                    .WithRequestPath("/")
                    .WithPort(443)
                    .Attach()
                .DefineBackend(httpBackendPool)
                    .WithExistingVirtualMachines(vms[1])
                    .Attach()
                .DefineBackend(httpsBackendPool)
                    .WithExistingVirtualMachines(vms[1])
                    .Attach()
                .Create();
```

Using this snippet to create everything from scratch works as expected. But as soon as I run this again with the `.WithExistingVirtualMachines(vms[1])` part changed to `.WithExistingVirtualMachines(vms[0])` or `.WithExistingVirtualMachines(vms)` it either changes only one of the Backend pools or fails with an exception.

Is there a different way of doing this or can you help me understand why it fails?
I would have assumed that this work work similar to manually adding/removing VMs to a Backend pool via the Portal.

**Stack trace**
```
InnerException | {"Cannot parse the request."} | System.Exception {Microsoft.Rest.Azure.CloudException}
Message | "One or more errors occurred." 
   at Microsoft.Azure.Management.Network.Fluent.LoadBalancerImpl.AfterCreating()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.GroupableParentResource`8.<CreateResourceAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.<Microsoft-Azure-Management-ResourceManager-Fluent-Core-ResourceActions-IResourceCreator<IResourceT>-CreateResourceAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.<ExecuteNodeTaskAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.Create()
   at AzureMgmtResources.Program.UpdateBackendPoolsInLoadBalancer(IAzure azure) in C:\Temp\Playground\AzureMgmtResources\AzureMgmtResources\Program.cs:line 87
   at AzureMgmtResources.Program.Main(String[] args) in C:\Temp\Playground\AzureMgmtResources\AzureMgmtResources\Program.cs:line 31
```

**Comment by sitereactor** [comment]
Adding one more oddity here:

If I use the same code as above, but update the name of the two Backend pools, it will correctly remove the two previous pools, but in return only adds the VM configuration to one of the two new pools.
(Meaning that the `httpBackendPool` property is updated from `HTTP_80` to `HTTP80` and `HTTP_443` to `HTTP443` ... which seems to me like something isn't working properly).

![image](https://user-images.githubusercontent.com/1398823/47091226-b872ff80-d224-11e8-8d81-d616c782bf03.png)
