### ISSUE TITLE
IMetricDefinition time interval parameter is not properly url-escaped/unescaped

### ISSUE THREAD

**Issue by Rambalac** [Azure/azure-libraries-for-net#610]
**Describe the bug**
Example for metrics is using local DataTime.Now. But it fails with Bad request response.

***Exception or Stack Trace***
_Microsoft.Azure.Management.Monitor.Fluent.Models.ErrorResponseException: 'Operation returned an invalid status code 'BadRequest''_
```
   at Microsoft.Azure.Management.Monitor.Fluent.MetricsOperations.ListWithHttpMessagesAsync(String resourceUri, ODataQuery`1 odataQuery, String timespan, Nullable`1 interval, String metricnames, String aggregation, Nullable`1 top, String orderby, Nullable`1 resultType, String metricnamespace, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Monitor.Fluent.MetricsOperationsExtensions.ListAsync(IMetricsOperations operations, String resourceUri, ODataQuery`1 odataQuery, String timespan, Nullable`1 interval, String metricnames, String aggregation, Nullable`1 top, String orderby, Nullable`1 resultType, String metricnamespace, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Monitor.Fluent.Models.MetricDefinitionImpl.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Monitor.Fluent.Models.MetricDefinitionImpl.Microsoft.Azure.Management.Monitor.Fluent.IWithMetricsQueryExecute.ExecuteAsync(CancellationToken cancellationToken)
   at WppVTuber.BusinessLogic.AzureServersHandler.GetMetricAsync(String id, String metricName, CancellationToken cancellation) in ...
```

**To Reproduce**
Run code for not UTC locale for any suitable metric.
```
           var now = DateTime.Now;

            var metric = await metricDefinition
                              .First(m => m.Name.Value == metricName)
                              .DefineQuery()
                              .StartingFrom(now.AddMinutes(-10))
                              .EndsBefore(now)
                              .WithAggregation("Maximum")
                              .WithInterval(TimeSpan.FromMinutes(1))
                              .ExecuteAsync(cancellation);
```

**Expected behaviour**
No errors.

**Setup (please complete the following information):**
 - Windows 10, Tokyo locale.
 - Version of the Library used: Microsoft.Azure.Management.Fluent 1.19.0

**Additional context**
Response reasonPhrase: Detected invalid time interval input: 2019-02-26T14:39:49.4279862 09:00/2019-02-26T14:49:49.4279862 09:00, violation: String was not recognized as a valid DateTime., supported Iso 8601 time interval format: (Datetime/Datetime, Datetime/Duration, Duration/Datetime, Duration)
Request URI: https://management.azure.com//subscriptions/86b919e5-addb-49d2-be26-b4f1e5ecc42b/resourceGroups/grp_vtuber/providers/Microsoft.Sql/servers/sqsvtuber/databases/dabvtuber/providers/microsoft.insights/metrics?timespan=2019-02-26T14%3A39%3A49.4279862%2B09%3A00%2F2019-02-26T14%3A49%3A49.4279862%2B09%3A00&interval=PT1M&metricnames=dtu_consumption_percent&aggregation=Maximum&api-version=2018-01-01

Looks like +09:00 lost +.

**Workaround**
Use DateTime.UtcNow.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by skyhoshi** [comment]
I have the exact same problem and can validate that this was not fixed in the Microsoft.Azure.Management.Fluent 1.20.0 version of the library.

**Comment by nickzhums** [comment]
@weidongxu-microsoft could you take a quick look, thanks

**Comment by weidongxu-microsoft** [comment]
@Rambalac 

This issue should be fixed around Nov. by this PR.

Now the time in URI should be UTC without timezone.

Let me know if you still having this issue.
