### ISSUE TITLE
[BUG]Receiving Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Rest.ServiceClientCredentials> Microsoft.Rest.Azure.Authentication.UserTokenProvider.LoginSilentAsync 

### ISSUE THREAD

**Issue by ankushbindlish2** [Azure/azure-libraries-for-net#611]
**Describe the bug**
This is the code snippet

.net framework : 4.6.1
 
You can find more information in \\ankushb-dt\SDKTests\StorageSyncDev.v5SDK.Tests\
 
<package id="Microsoft.Rest.ClientRuntime.Azure.Authentication" version="2.3.6" />
    <package id="Microsoft.Rest.ClientRuntime.Azure" version="3.3.18" />
    <package id="Microsoft.Rest.ClientRuntime" version="2.3.18" />
    <package id="Microsoft.IdentityModel.Clients.ActiveDirectory" version="4.5.1" />
    <package id="Microsoft.Azure.Management.Fluent" version="1.19.0" />

          

***Exception or Stack Trace***
Test Name:	TestStorageSyncService_Create_Success
Test FullName:	StorageSyncDev.v5SDK.Tests.StorageSyncServiceTests.TestStorageSyncService_Create_Success
Test Source:	h:\onebranch\Storage\XSync\Dev\src\Kailani\SDKTests\StorageSyncDev.v5SDK.Tests\StorageSyncServiceTests.cs : line 14
Test Outcome:	Failed
Test Duration:	0:00:06.1024683

Result StackTrace:	
at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.<ProcessHttpRequestAsync>d__24.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourceGroupsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourceGroupImpl.<CreateResourceAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.<Microsoft-Azure-Management-ResourceManager-Fluent-Core-ResourceActions-IResourceCreator<IResourceT>-CreateResourceAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.<ExecuteNodeTaskAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)
   at StorageSyncDev.v5SDK.Tests.StorageSyncSdkTestBase.CreateResourceGroup(String resourceGroupName) in h:\onebranch\Storage\XSync\Dev\src\Kailani\SDKTests\StorageSyncDev.v5SDK.Tests\StorageSyncSdkTestBase.cs:line 77
   at StorageSyncDev.v5SDK.Tests.StorageSyncSdkTestBase.Initialize() in h:\onebranch\Storage\XSync\Dev\src\Kailani\SDKTests\StorageSyncDev.v5SDK.Tests\StorageSyncSdkTestBase.cs:line 67
Result Message:	Initialization method StorageSyncDev.v5SDK.Tests.StorageSyncServiceTests.Initialize threw exception. System.MissingMethodException: System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Rest.ServiceClientCredentials> Microsoft.Rest.Azure.Authentication.UserTokenProvider.LoginSilentAsync(System.String, System.String, System.String, System.String, Microsoft.Rest.Azure.Authentication.ActiveDirectoryServiceSettings, Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache)'..

**To Reproduce**

***Code Snippet***
  AzureCredentials azureCredentials = SdkContext.AzureCredentialsFactory.FromFile(@"test.auth");

            TenantId = azureCredentials.TenantId;// "72f988bf-86f1-41af-91ab-2d7cd011db47";
            ApplicationId = azureCredentials.ClientId; //"771cce6f-c352-4876-aac9-e5d02f681807";
            ApplicationSecret = KeyVaultHelper.GetSecretFromKeyVault("TestStorageSyncClient");
            SubscriptionId = azureCredentials.DefaultSubscriptionId; //"8aba3d53-2c5e-4479-bb0d-5a7bed16360e";

            ServiceClientCredentials credentials = ApplicationTokenProvider.LoginSilentAsync(azureCredentials.TenantId, azureCredentials.ClientId, ApplicationSecret)
               .GetAwaiter().GetResult();

            StorageSyncManagementClient = new StorageSyncManagementClient(credentials)
            {
                SubscriptionId = SubscriptionId,
                GenerateClientRequestId = true,
                LongRunningOperationRetryTimeout = 60 * 6
            };

            AzureContext = Azure
                .Configure()
                .WithLogLevel(HttpLoggingDelegatingHandler.Level.BodyAndHeaders)
                .Authenticate(azureCredentials)
                .WithSubscription(SubscriptionId);

            ResourceGroup = AzureContext.ResourceGroups.Define("rgName").WithRegion(DefaultLocation).Create();

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used : 1.19.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by ankushbindlish2** [comment]
Referencing https://github.com/Azure/azure-libraries-for-net/issues/282

**Comment by shahabhijeet** [comment]
@ankushbindlish2 this issue belongs in Fluent repo
https://github.com/Azure/azure-libraries-for-net

**Comment by praries880** [comment]
@ankushbindlish2 Did none of the suggested fixes in https://github.com/Azure/azure-libraries-for-net/issues/282 work for you?

**Comment by praries880** [comment]
What does 
```c#
ApplicationSecret = KeyVaultHelper.GetSecretFromKeyVault("TestStorageSyncClient");
```
return?

**Comment by ankushbindlish2** [comment]
Yes

**Comment by ankushbindlish2** [comment]
I ddint see any suggestion in that issue. Please help me locate and paste it in here

**Comment by praries880** [comment]
I updated my first comment with some additional questions… can you answer those as well?

**Comment by ankushbindlish2** [comment]
Workaround : Worked by changing libraries to 452 instead of 461.

**Comment by praries880** [comment]
The issue here is described in : https://github.com/Azure/azure-sdk-for-net/issues/4316

Seems userTokenAuth is no longer supported. Try using the suggestions in https://github.com/Azure/azure-libraries-for-net/blob/master/AUTH.md
