### ISSUE TITLE
User Managed Identity not working

### ISSUE THREAD

**Issue by krypto92** [Azure/azure-libraries-for-net#635]
**Query/Question**
User Assigned Identity not working

when i try to use user managed identity in **Azure function v2** for authentication and i am getting the error *Cannot perform runtime binding on a null reference*. here is the code piece,

```c#
try {
	AzureCredentialsFactory factory = new AzureCredentialsFactory();
	MSILoginInformation msi = new MSILoginInformation(MSIResourceType.AppService);
	AzureCredentials msiCred = factory.FromMSI(msi, AzureEnvironment.AzureGlobalCloud);
	var azureAuth = Azure.Configure().Authenticate(msiCred);
	IAzure azure = azureAuth.WithSubscription(subcription_id);
	List<string> scaleSetList = new List<string>();
	foreach (var scaleSet in azure.VirtualMachineScaleSets.ListByResourceGroup(resource_group_name))
	{
		log.LogInformation(string.Format("Scale ID : {0} Name : {1}", scaleSet.Id, scaleSet.Name));
	}
}
catch (Exception e)
{
	log.LogInformation(string.Format("Error {0}", e.Message));
}
```
but the same code works for the system managed identity.

**Version of the Library used**
 - Microsoft.Azure.Management.Fluent v1.20.0

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by praries880** [comment]
@krypto92 
Can you kindly provide the full stack trace of the exception or some more detailed info on the exception itself?

**Comment by krypto92** [comment]
here is the stack trace,

```2019-04-04T06:41:34.970 [Information] Error Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.MSITokenProvider.GetAuthenticationHeaderForAppServiceAsync(String resource, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.MSITokenProvider.GetAuthenticationHeaderAsync(CancellationToken cancellationToken)
   at Microsoft.Rest.TokenCredentials.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachineScaleSetsOperations.ListWithHttpMessagesAsync(String resourceGroupName, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachineScaleSetsOperationsExtensions.ListAsync(IVirtualMachineScaleSetsOperations operations, String resourceGroupName, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachineScaleSetsImpl.ListInnerByGroupAsync(String groupName, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.TopLevelModifiableResources`5.ListByResourceGroup(String resourceGroupName)```

@praries880  i followed the steps provided by https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity and my code failing with the above error while using user assigned identity (but works with system assigned identity).

**Comment by DenisaAndreeaA** [comment]
Same problem here:

```
                AzureCredentialsFactory factory = new AzureCredentialsFactory();
                MSILoginInformation msi = new MSILoginInformation(MSIResourceType.AppService);
                AzureCredentials credentials = factory.FromMSI(msi, AzureEnvironment.AzureGlobalCloud);
                var azureAuth = Azure.Configure().Authenticate(credentials);
                IAzure azure = azureAuth.WithSubscription("fa6409ab-6837-40b6-921a-85dd2b3ceab4");
  

                string registryResourceGroup = "omni-test";
                string containerResourceGroup = "denisa-apostol-test";
                string containerRegistry = "cytosmarttestreg";
                string environment = "Test";

                // STEP 2: Access the container registry.
                IRegistry azureRegistry = azure.ContainerRegistries.GetByResourceGroup(registryResourceGroup, containerRegistry);
```


```
Cannot perform runtime binding on a null reference:    at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.MSITokenProvider.GetAuthenticationHeaderForAppServiceAsync(String resource, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.MSITokenProvider.GetAuthenticationHeaderAsync(CancellationToken cancellationToken)
   at Microsoft.Rest.TokenCredentials.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ContainerRegistry.Fluent.RegistriesOperations.GetWithHttpMessagesAsync(String resourceGroupName, String registryName, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ContainerRegistry.Fluent.RegistriesOperationsExtensions.GetAsync(IRegistriesOperations operations, String resourceGroupName, String registryName, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.GroupableResources`5.GetByResourceGroupAsync(String groupName, String name, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.GroupableResources`5.GetByResourceGroup(String groupName, String name)
   at ManagedidentityAzure.Function1.Run(HttpRequest req, ILogger log) in C:\Users\denis\Desktop\ManagedIdentity\ManagedidentityAzure\ManagedidentityAzure\Function1.cs:line 54
```

**Comment by karataliu** [comment]
Should port #143 for appservice and such.
We're also facing this issue, will someone work on this?
