### ISSUE TITLE
Reimage Scaleset Instance fails

### ISSUE THREAD

**Issue by azkamil** [Azure/azure-libraries-for-net#663]
After update from 1.20 to version 1.22 of Compute.Fluent library the Reaimge  function
Microsoft.Azure.Management.Compute.Fluent.VirtualMachineScaleSetsOperationsExtensions.ReimageAsync stopped working properly.
we tried also to set tempDisk  to true/false (see error message) which did not help

***Exception or Stack Trace***
error message is: 
The value of parameter tempDisk is invalid.
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachineScaleSetsOperations.BeginReimageWithHttpMessagesAsync(String resourceGroupName, String vmScaleSetName, VirtualMachineScaleSetReimageParametersInner vmScaleSetReimageInput, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachineScaleSetsOperations.ReimageWithHttpMessagesAsync(String resourceGroupName, String vmScaleSetName, VirtualMachineScaleSetReimageParametersInner vmScaleSetReimageInput, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachineScaleSetsOperationsExtensions.ReimageAsync(IVirtualMachineScaleSetsOperations operations, String resourceGroupName, String vmScaleSetName, VirtualMachineScaleSetReimageParametersInner vmScaleSetReimageInput, CancellationToken cancellationToken)
   at MasterService.Scaleset.ReimageMachineAsync(String machineName) in C:\dwcr\ClusterAPI\master\MasterService\Scaleset.cs:line 157

**To Reproduce**
try to reimage a scalesetVM instance.

***Code Snippet***
var reimageArg = new VirtualMachineScaleSetReimageParametersInner(false, new List<string>(new[] { instanceId }));
                await _azure.VirtualMachineScaleSets.Inner.ReimageAsync(resourceGroup, scalesetName, reimageArg).ConfigureAwait(false);

**Expected behavior**
I expected no exception to be thrown

**Setup (please complete the following information):**
 - OS: Linux in production, windows in IDE. both failed
 - IDE : Visual Stuidio
 - 1.22 failed. Previous version we used and that worked is 1.20

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @praries880

**Comment by azkamil** [comment]
We updated to v1.23 and this bug seems to be resolved.

**Comment by nickzhums** [comment]
@azkamil Since you are no longer experiencing the issue, we will close it for now. Feel free to re-open it
