### ISSUE TITLE
[BUG] Problems when using custom exponential backoff strategy

### ISSUE THREAD

**Issue by orpeti** [Azure/azure-libraries-for-net#672]
**Describe the bug**
Preliminary knowledge for the issue:
We are using the Azure Fluent SDK.
We are using the retry policy of the Fluent SDK.
Incremental strategy: fixed time interval between retries.
Exponential backoff strategy: Progressive delay between retries.
 
In the past we used the incremental strategy of the retry policy, and everything worked fine.
We changed the strategy from incremental to exponential backoff and it caused a bug:
When we try to get a vm or a scale set, in case the scale set does not exist, we should receive null.
But when we are using the exponential backoff strategy we receive an 404 error – not found
When we use the incremental strategy we receive in the same case null as expected.
 
It means that somehow, the change of the retry policy strategy from incremental to exponential backoff, caused an unexpected exception in code which was supposed to return null.
In both cases we used the same error detection strategy. (Error detection strategy is ITransientErrorDetectionStrategy which is responsible for detecting transient conditions.)

in conclusion:
•	The default (default Exponential Backoff) and incremental retry policies are working as expected, as they return Null when no VM ScaleSets are found, and no retries are attempted.
•	 When using your "own" Exponential Backoff strategy, you see 404's when no ScaleSets are found, and there are retries as well.

***Exception or Stack Trace***
   at Microsoft.Rest.RetryDelegatingHandler.<SendAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ProviderRegistrationDelegatingHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.HttpLoggingDelegatingHandler.<SendAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.UserAgentDelegatingHandler.<SendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachineScaleSetsOperations.<GetWithHttpMessagesAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachineScaleSetsOperationsExtensions.<GetAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachineScaleSetsImpl.<GetInnerByGroupAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.GroupableResources`5.<GetByResourceGroupAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Zerto.Zvm.Platform.PublicCloud.AzureProxy.Accessors.ScaleSetConnector.<GetScaleSetAsync>d__13.MoveNext() in C:\projects\zvmm\dev\system\Zvm\Platform\PublicCloud\AzureProxy\Accessors\ScaleSetConnector.cs:line 181
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Zerto.Zvm.Platform.PublicCloud.AzureProxy.Accessors.ScaleSetConnector.<GetScaleSetByNameAndTagsIfExistsAsync>d__10.MoveNext() in C:\projects\zvmm\dev\system\Zvm\Platform\PublicCloud\AzureProxy\Accessors\ScaleSetConnector.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Zerto.Zvm.Platform.PublicCloud.AzureProxy.Accessors.ScaleSetConnector.<IsScaleSetExistsAsync>d__9.MoveNext() in C:\projects\zvmm\dev\system\Zvm\Platform\PublicCloud\AzureProxy\Accessors\ScaleSetConnector.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Zerto.Zvm.Platform.PublicCloud.AzureProxy.Implementation.AzureComputeProxy.<IsScaleSetExistsAsync>d__71.MoveNext() in C:\projects\zvmm\dev\system\Zvm\Platform\PublicCloud\AzureProxy\Implementation\AzureComputeProxy.cs:line 1183
 
source: "Microsoft.Rest.ClientRuntime"
Response status code indicates server error: 404 (NotFound).
HttpRequestWithStatusException: Response status code indicates server error: 404 (NotFound).

**To Reproduce**
use an exponential backoff strategy - not the default one. and try to get a scale set which does not exist. 

***Code Snippet***
Initialize IAzure:
var m_azure = AzureFluentWrapper.Configure()
                .WithLogLevel(HttpLoggingDelegatingHandler.Level.Basic)
                .WithRetryPolicy(retryPolicy)
                .Authenticate(azureCredentials)
                .WithSubscription(SubscriptionId);
 
 
Error detection strategy (In both incremental and exponential backoff strategies):
    public class AzureRetryPolicyErrorDetectionStrategy : ITransientErrorDetectionStrategy
    {
        public bool IsTransient(Exception ex)
        {
            if (ex is Microsoft.Rest.Azure.CloudException || 
                ex is CloudException || 
                ex is StorageException || 
                ex is AdalServiceException || 
                ex is CloudHttpException || 
                ex is HttpRequestWithStatusException || 
                ex is ODataErrorException || 
                ex is ApplicationObjectNotFoundException || 
                ex is TaskCanceledException)
            {
                return true;
            }
 
            return false;
        }
    }
 
 
var ErrorDetectionStrategy = new AzureRetryPolicyErrorDetectionStrategy()
 
 
Create retry policy with incremental strategy:
RetryPolicy retryPolicy =
                    new RetryPolicy(ErrorDetectionStrategy, RetryCount, TimeSpan.FromSeconds(RetryInterval));
 
We used:
RetryCount = 15
RetryInterval = 1 seconds
 
 
Create retry policy with exponential backoff strategy:
RetryPolicy retryPolicy =
                new RetryPolicy(ErrorDetectionStrategy, new ExponentialBackoffRetryStrategy(RetryCount, MinBackoff, MaxBackoff, DeltaBackoff));
 
We used:
RetryCount = 15 
MinBackoff = 0.5 seconds
MaxBackoff = 30 seconds
DeltaBackoff = 0.5 seconds
 
 
Get scale set:
var scaleSet = await m_azure.VirtualMachineScaleSets.GetByResourceGroupAsync(scaleSetRgName, scaleSetName);

The namespace of the preticular retry policy class: Microsoft.Rest.TransientFaultHandling

**Expected behavior**
get null

**Setup (please complete the following information):**
 - IDE : visual studio 2017
- The version of the Azure SDK – 1.17

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by yaohaizh** [comment]
We have updated the run time. @orpeti  please try the latest SDK if the issue still persist. Thakns.

**Comment by Drewm3** [comment]
I am closing this issue. @orpeti, please let us know if it is still a problem.

**Comment by asafzafrany** [comment]
Hi,

We are now using Fluent SDK version 1.36.1 and encountered the following issue:
When using the Exponential Backoff retry policy with low values, it seems that we get the expected response if a scale_set does not exist (null). 
When increasing the values, we get a 404 Not Found exception.

Successful values used:
MinBackoff = 0.5 seconds
MaxBackoff = 30 seconds
DeltaBackoff = 0.5 seconds

Values that cause a 404 Not Found exception:
MinBackoff = 10 seconds
MaxBackoff = 900 seconds
DeltaBackoff = 20 seconds

Example of the exception thrown:
Zerto.Platform.PublicCloud.DTO.CloudComputeException: Failed to check if scale set exists: 'Zerto_a4f88ad8-2c77-4d5a-aad7-069889ef79fc'. Error message: Error Message = Response status code indicates server error: 404 (NotFound)., Response = N/A, Error Code = NotFound, Reason = N/A. ---> Microsoft.Rest.TransientFaultHandling.HttpRequestWithStatusException: Response status code indicates server error: 404 (NotFound).
   at Microsoft.Rest.RetryDelegatingHandler.<SendAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ProviderRegistrationDelegatingHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Zerto.Zvm.Platform.PublicCloud.AzureProxy.Implementation.HttpTracer.<RunAndTraceRequest>d__7.MoveNext() in E:\islay-ci\dev\system\Zvm\Platform\PublicCloud\AzureProxy\Implementation\HttpTracer.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.HttpLoggingDelegatingHandler.<SendAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.UserAgentDelegatingHandler.<SendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachineScaleSetsOperations.<GetWithHttpMessagesAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachineScaleSetsOperationsExtensions.<GetAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachineScaleSetsImpl.<GetInnerByGroupAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.GroupableResources`5.<GetByResourceGroupAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Zerto.Zvm.Platform.PublicCloud.AzureProxy.Accessors.ScaleSetConnector.<GetScaleSetAsync>d__17.MoveNext() in E:\islay-ci\dev\system\Zvm\Platform\PublicCloud\AzureProxy\Accessors\ScaleSetConnector.cs:line 234
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Zerto.Zvm.Platform.PublicCloud.AzureProxy.Accessors.ScaleSetConnector.<GetScaleSetByNameAndTagsAsync>d__8.MoveNext() in E:\islay-ci\dev\system\Zvm\Platform\PublicCloud\AzureProxy\Accessors\ScaleSetConnector.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Zerto.Zvm.Platform.PublicCloud.AzureProxy.Accessors.ScaleSetConnector.<IsScaleSetExistsAsync>d__4.MoveNext() in E:\islay-ci\dev\system\Zvm\Platform\PublicCloud\AzureProxy\Accessors\ScaleSetConnector.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Zerto.Zvm.Platform.PublicCloud.AzureProxy.Implementation.AzureComputeProxy.<IsScaleSetExistsAsync>d__88.MoveNext() in E:\islay-ci\dev\system\Zvm\Platform\PublicCloud\AzureProxy\Implementation\AzureComputeProxy.cs:line 1415
   --- End of inner exception stack trace ---
   at Zerto.Zvm.Platform.PublicCloud.AzureProxy.Implementation.AzureComputeProxy.<IsScaleSetExistsAsync>d__88.MoveNext() in E:\islay-ci\dev\system\Zvm\Platform\PublicCloud\AzureProxy\Implementation\AzureComputeProxy.cs:line 1424
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Zerto.Platform.PublicCloud.ScaleoutJobsOrchestrator.Domain.Scaling.Services.CloudScalingAccessor.<IsScaleSetExistsAsync>d__11.MoveNext() in E:\build-installers\install-Azure\dev\system\Platform\PublicCloud\ScaleoutJobsOrchestrator\Domain\Scaling\Services\CloudScalingAccessor.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Zerto.Platform.PublicCloud.ScaleoutJobsOrchestrator.Domain.Scaling.Services.CloudScalingAccessor.IsScaleSetExists(String scaleSetName, PublicCloudResourceTagsCollection scaleSetTags) in E:\build-installers\install-Azure\dev\system\Platform\PublicCloud\ScaleoutJobsOrchestrator\Domain\Scaling\Services\CloudScalingAccessor.cs:line 80
   at Zerto.Platform.PublicCloud.ScaleoutJobsOrchestrator.Domain.Scaling.Services.CloudScalingOperations.CreateScaleSetIfNotExists() in E:\build-installers\install-Azure\dev\system\Platform\PublicCloud\ScaleoutJobsOrchestrator\Domain\Scaling\Services\CloudScalingOperations.cs:line 149
   at Zerto.Platform.PublicCloud.ScaleoutJobsOrchestrator.Domain.Scaling.Services.CloudScalingOperations.CreateComponentsIfNotExists() in E:\build-installers\install-Azure\dev\system\Platform\PublicCloud\ScaleoutJobsOrchestrator\Domain\Scaling\Services\CloudScalingOperations.cs:line 134
   at Zerto.Platform.PublicCloud.ScaleoutJobsOrchestrator.Domain.Scaling.Services.CloudScalingOperations.CreateCloudServices() in E:\build-installers\install-Azure\dev\system\Platform\PublicCloud\ScaleoutJobsOrchestrator\Domain\Scaling\Services\CloudScalingOperations.cs:line 117"


Expected behavior
get null for any values of the exponential retry policy

Fluent SDK version: 1.36.1

**Comment by gadros** [comment]
@Drewm3 as @asafzafrany commented we've experienced this in 1.36.1. this is important for us as it affects many customers. would you prefer that we'll open a new ticket?
