### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by asehgal123** [Azure/azure-libraries-for-net#693]
**Describe the bug**
Keep getting error "Operation returned an invalid status code 'BadRequest'" trying to set LogAnalytics workspace for a webapp resource using Azure fluent API.

***Exception or Stack Trace***
   at Microsoft.Azure.Management.Monitor.Fluent.DiagnosticSettingsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.Monitor.Fluent.DiagnosticSettingsOperationsExtensions.<CreateOrUpdateAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.Monitor.Fluent.Models.DiagnosticSettingImpl.<CreateResourceAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.<Microsoft-Azure-Management-ResourceManager-Fluent-Core-ResourceActions-IResourceCreator<IResourceT>-CreateResourceAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.<ExecuteNodeTaskAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MyCompany.Azure.Deployment.Deploy.AzureDeploy.<CreateDiagnosticSetting>d__17.MoveNext() in F:\work\Deployment\Deploy\AzureDeploy.DiagnosticSettings.cs:line 48

**To Reproduce**
Execute the attached code snippet to reproduce the issue.

***Code Snippet***
        private async Task CreateDiagnosticSetting(string resourceID, string resourceName, string workspaceName, int retentionDays, int metricTimeSpan)
        {
            try {
                string id = _catalog.GetResourceId(LogAnalytics.AzureResourceType, workspaceName);
                if (String.IsNullOrEmpty(id))
                    return;
                Workspace workspace = await this.Query.GetAzureLogAnalyticsWorkspace(id);
                if (workspace == null)
                    return;

                this.Console.Info($"Enabling diagnostic logging for '{resourceName}'...");
                Stopwatch timer = Stopwatch.StartNew();

                IReadOnlyList<IDiagnosticSettingsCategory> categories = await this.Azure.DiagnosticSettings.ListCategoriesByResourceAsync(resourceID);
                TimeSpan span = new TimeSpan(0, metricTimeSpan, 0);

                IDiagnosticSetting diagnostics = await this.Azure.DiagnosticSettings.Define("Log-" + resourceName)
                    .WithResource(resourceID)
                    .WithLogAnalytics(workspace.Id)
                    .WithLogsAndMetrics(categories, span, retentionDays)
                    .CreateAsync();

                this.Console.Success($"Successfully enabled diagnostic logging for '{resourceName}'.  Elapsed time: {timer.ElapsedTime()}");
            }
            catch (Exception ex) {
                string errMsg = $"Failed to enable diagnostic logging for '{resourceName}': {ex.Message}";
                throw new DeploymentException(errMsg, ex);
            }
        }

**Expected behavior**
Should add LogAnalytics workspace with webapp like it does for other resource types i.e. VirtualMachine, SQL Database etc...

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Visual Studio 2017
 - Microsoft.Azure.Management.ResourceManager.Fluent, Version=1.0.0.60

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by weidongxu-microsoft** [comment]
@asehgal123 

Monitor service got updated around Oct. You can try again.

I've got below sample code working.

```
            IReadOnlyList<IDiagnosticSettingsCategory> categories = azure.DiagnosticSettings.ListCategoriesByResource(RESOURCE_ID_WEBAPP);
            TimeSpan span = new TimeSpan(0, 10, 0);

            azure.DiagnosticSettings.Define("Log-" + RESOURCE_GROUP)
                    .WithResource(RESOURCE_ID_WEBAPP)
                    .WithLogAnalytics(RESOURCE_ID_LOGANALYTICS_WORKSPACE)
                    .WithLogsAndMetrics(categories, span, 1)
                    .Create();
```

**Comment by nickzhums** [comment]
@asehgal123 Let us know if you are still experiencing this issue
