### ISSUE TITLE
[BUG] Unhelpful exception message for missing MSI_ENDPOINT env var

### ISSUE THREAD

**Issue by Eilon** [Azure/azure-libraries-for-net#698]
**Describe the bug**

I'm playing with resource manager APIs and ran into an exception:

```
Value cannot be null.
Parameter name: MSI_ENDPOINT

   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.MSITokenProvider.GetAuthenticationHeaderForAppServiceAsync(String resource, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.MSITokenProvider.GetAuthenticationHeaderAsync(CancellationToken cancellationToken)
   at Microsoft.Rest.TokenCredentials.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.SubscriptionsOperations.ListWithHttpMessagesAsync(Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.SubscriptionsOperationsExtensions.ListAsync(ISubscriptionsOperations operations, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)
   at Microsoft.Azure.Management.ResourceManager.Fluent.SubscriptionsImpl.List()
   at Microsoft.Azure.Management.Fluent.Azure.Authenticated.WithDefaultSubscription()
   at MyNamespace.MyCode()
```

This comes from these checks:

https://github.com/Azure/azure-libraries-for-net/blob/d5a679dc470b6275508997cfb78d2c1187ac00e1/src/ResourceManagement/ResourceManager/Authentication/MSITokenProvider.cs#L80-L81

***Code Snippet***

```c#
                var credentials = SdkContext.AzureCredentialsFactory
                    .FromMSI(
                        new MSILoginInformation(
                            MSIResourceType.AppService)
                        {
                            UserAssignedIdentityClientId = "",
                            UserAssignedIdentityObjectId = "",
                            UserAssignedIdentityResourceId = "",
                        },
                        AzureEnvironment.AzureGlobalCloud);

                var azure = Azure
                    .Configure()
                    .Authenticate(credentials)
                    .WithDefaultSubscription();
```

**Expected behavior**
A different exception type should be thrown. An `ArgumentNullException` should be thrown only if there's a *parameter* (in the C# sense) that is `null`, not if some other thing (such as an env var) is null. A better exception might be `InvalidOperationException` that would indicate what was being done and why it failed. The current exception offers no information about what went wrong or why (let along how to fix it).

**Setup (please complete the following information):**
Library versions used:

```xml
    <PackageReference Include="Microsoft.Azure.Management.Fluent" Version="1.22.2" />
    <PackageReference Include="Microsoft.Azure.Management.ResourceManager.Fluent" Version="1.22.2" />
```

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by xccc-msft** [comment]
@Eilon Thanks for raising this. We will check if InvalidOperationException could be replaced by ArgumentNullException in this situation.

**Comment by xccc-msft** [comment]
Close this as we have no plan to change the exception type now.
