### ISSUE TITLE
[BUG] Generic delete operation fails with 404 NotFound

### ISSUE THREAD

**Issue by xenalite** [Azure/azure-libraries-for-net#775]
**Describe the bug**
1. Have an existing resource
2. Attempt to delete this resource using generic resource delete operation
3. Delete action removes the resource, but throws a `CloudException` with 404 status code.
4. This action does not fail 100% time, but sporadically. Out of an array of 100 resources being deleted, about 12-20 of them throw this error.

**Exception or Stack Trace**
```
2019-09-02T15:36:19.3639608Z System.AggregateException: One or more errors occurred. (Long running operation failed with status 'NotFound'.) (Long running operation failed with status 'NotFound'.) (Long running operation failed with status 'NotFound'.) (Long running operation failed with status 'NotFound'.) (Long running operation failed with status 'NotFound'.) (Long running operation failed with status 'NotFound'.) (Long running operation failed with status 'NotFound'.) (Long running operation failed with status 'NotFound'.) (Long running operation failed with status 'NotFound'.) (Long running operation failed with status 'NotFound'.) (Long running operation failed with status 'NotFound'.) (Long running operation failed with status 'NotFound'.) (Long running operation failed with status 'NotFound'.) (Long running operation failed with status 'NotFound'.) (Long running operation failed with status 'NotFound'.) (Long running operation failed with status 'NotFound'.) (Long running operation failed with status 'NotFound'.) (Long running operation failed with status 'NotFound'.) (Long running operation failed with status 'NotFound'.) (Long running operation failed with status 'NotFound'.) (Long running operation failed with status 'NotFound'.) (Long running operation failed with status 'NotFound'.) (Long running operation failed with status 'NotFound'.) (Long running operation failed with status 'NotFound'.) ---> Microsoft.Rest.Azure.CloudException: Long running operation failed with status 'NotFound'.
2019-09-02T15:36:19.3640347Z    at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.CheckErrorStatusAndThrowAsync(HttpRequestMessage request, HttpResponseMessage response)
2019-09-02T15:36:19.3640559Z    at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.GetRawAsync(Dictionary`2 customHeaders, CancellationToken cancellationToken)
2019-09-02T15:36:19.3641170Z    at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.UpdateResourceFromPollingUri(Dictionary`2 customHeaders, CancellationToken cancellationToken)
2019-09-02T15:36:19.3641368Z    at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.Poll(Dictionary`2 customHeaders, CancellationToken cancellationToken)
2019-09-02T15:36:19.3641502Z    at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.StartPollingAsync()
2019-09-02T15:36:19.3641619Z    at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.BeginLROAsync()
2019-09-02T15:36:19.3641777Z    at Microsoft.Rest.Azure.AzureClientExtensions.GetLongRunningOperationResultAsync[TBody,THeader](IAzureClient client, AzureOperationResponse`2 response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
2019-09-02T15:36:19.3641991Z    at Microsoft.Rest.Azure.AzureClientExtensions.GetLongRunningOperationResultAsync[TBody](IAzureClient client, AzureOperationResponse`1 response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
2019-09-02T15:36:19.3642180Z    at Microsoft.Rest.Azure.AzureClientExtensions.GetLongRunningOperationResultAsync(IAzureClient client, AzureOperationResponse response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
2019-09-02T15:36:19.3642422Z    at Microsoft.Rest.Azure.AzureClientExtensions.GetPostOrDeleteOperationResultAsync(IAzureClient client, AzureOperationResponse response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
2019-09-02T15:36:19.3642659Z    at Microsoft.Azure.Management.ResourceManager.Fluent.ResourcesOperations.DeleteWithHttpMessagesAsync(String resourceGroupName, String resourceProviderNamespace, String parentResourcePath, String resourceType, String resourceName, String apiVersion, Dictionary`2 customHeaders, CancellationToken cancellationToken)
2019-09-02T15:36:19.3643253Z    at Microsoft.Azure.Management.ResourceManager.Fluent.ResourcesOperationsExtensions.DeleteAsync(IResourcesOperations operations, String resourceGroupName, String resourceProviderNamespace, String parentResourcePath, String resourceType, String resourceName, String apiVersion, CancellationToken cancellationToken)
2019-09-02T15:36:19.3645590Z    at Microsoft.Azure.Management.ResourceManager.Fluent.GenericResourcesImpl.DeleteAsync(String resourceGroupName, String resourceProviderNamespace, String parentResourcePath, String resourceType, String resourceName, String apiVersion, CancellationToken cancellationToken)
2019-09-02T15:36:19.3645972Z    --- End of inner exception stack trace ---
2019-09-02T15:36:19.3646361Z    at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
2019-09-02T15:36:19.3646548Z    at WTW.AML.DeploymentTool.Actions.TestInstancesCleanupActions.RemoveInstanceResources() in D:\_Builds\E20-IX-VSBD024P.01\1\s\build\AML.DeploymentTool\WTW.AML.DeploymentTool\Actions\TestInstancesCleanupActions.cs:line 84
2019-09-02T15:36:19.3646810Z    at WTW.AML.DeploymentTool.Actions.TestInstancesCleanupActions.Execute() in D:\_Builds\E20-IX-VSBD024P.01\1\s\build\AML.DeploymentTool\WTW.AML.DeploymentTool\Actions\TestInstancesCleanupActions.cs:line 35
2019-09-02T15:36:19.3647038Z    at WTW.AML.DeploymentTool.Program.Main(String[] args) in D:\_Builds\E20-IX-VSBD024P.01\1\s\build\AML.DeploymentTool\WTW.AML.DeploymentTool\Program.cs:line 30
2019-09-02T15:36:19.3647346Z ---> (Inner Exception #0) Microsoft.Rest.Azure.CloudException: Long running operation failed with status 'NotFound'.
2019-09-02T15:36:19.3647521Z    at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.CheckErrorStatusAndThrowAsync(HttpRequestMessage request, HttpResponseMessage response)
2019-09-02T15:36:19.3647693Z    at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.GetRawAsync(Dictionary`2 customHeaders, CancellationToken cancellationToken)
2019-09-02T15:36:19.3647906Z    at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.UpdateResourceFromPollingUri(Dictionary`2 customHeaders, CancellationToken cancellationToken)
2019-09-02T15:36:19.3648097Z    at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.Poll(Dictionary`2 customHeaders, CancellationToken cancellationToken)
2019-09-02T15:36:19.3648266Z    at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.StartPollingAsync()
2019-09-02T15:36:19.3648407Z    at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.BeginLROAsync()
2019-09-02T15:36:19.3648616Z    at Microsoft.Rest.Azure.AzureClientExtensions.GetLongRunningOperationResultAsync[TBody,THeader](IAzureClient client, AzureOperationResponse`2 response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
2019-09-02T15:36:19.3648827Z    at Microsoft.Rest.Azure.AzureClientExtensions.GetLongRunningOperationResultAsync[TBody](IAzureClient client, AzureOperationResponse`1 response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
2019-09-02T15:36:19.3649066Z    at Microsoft.Rest.Azure.AzureClientExtensions.GetLongRunningOperationResultAsync(IAzureClient client, AzureOperationResponse response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
2019-09-02T15:36:19.3649277Z    at Microsoft.Rest.Azure.AzureClientExtensions.GetPostOrDeleteOperationResultAsync(IAzureClient client, AzureOperationResponse response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
2019-09-02T15:36:19.3649545Z    at Microsoft.Azure.Management.ResourceManager.Fluent.ResourcesOperations.DeleteWithHttpMessagesAsync(String resourceGroupName, String resourceProviderNamespace, String parentResourcePath, String resourceType, String resourceName, String apiVersion, Dictionary`2 customHeaders, CancellationToken cancellationToken)
2019-09-02T15:36:19.3649815Z    at Microsoft.Azure.Management.ResourceManager.Fluent.ResourcesOperationsExtensions.DeleteAsync(IResourcesOperations operations, String resourceGroupName, String resourceProviderNamespace, String parentResourcePath, String resourceType, String resourceName, String apiVersion, CancellationToken cancellationToken)
2019-09-02T15:36:19.3651013Z    at Microsoft.Azure.Management.ResourceManager.Fluent.GenericResourcesImpl.DeleteAsync(String resourceGroupName, String resourceProviderNamespace, String parentResourcePath, String resourceType, String resourceName, String apiVersion, CancellationToken cancellationToken)<---
2019-09-02T15:36:19.3651171Z 
```

***Code Snippet***
```csharp
try
{
  await _connection
    .ResourceManager
    .GenericResources
    .DeleteAsync(
      resource.ResourceGroupName,
      resource.ResourceProviderNamespace,
      resource.ParentResourceId ?? "",
      resource.ResourceType,
      resource.Name,
      apiVersion);
}
catch (CloudException e)
{
  // Sometimes a delete operation throws this exception even though it was successful.
  if (e.Response.StatusCode != HttpStatusCode.NotFound)
    throw;
  Log($"Deleted {resource.Id} with {e.Response.StatusCode} status code.");
}
```

**Expected behavior**
Delete operation to always succeed if the resource is found before the deletion request.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Visual Studio 2017
 - 1.25.0

**Additional context**
This does not seem to be entirely related to the library, but rather to the API itself.
Same issue is reproducible with Azure PowerShell:
https://github.com/Azure/azure-powershell/issues/7119

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by weidongxu-microsoft** [comment]
@xenalite Did you observe which type of resource tend to get the exception? This would facilitate for us to reproduce it.

PS:
1. What is the type of _connection object?
2. What value is apiVersion used in the call?

**Comment by xenalite** [comment]
@weidongxu-microsoft Any resource should do, though we mostly delete: Storage Accounts, App Insights, Service Bus, Key Vault, Function Apps.

1. It's our custom object with these properties:
```csharp
public IAzure Azure { get; }
public IResourceManager ResourceManager => Azure.Deployments.Manager;
```

2. Whatever is the latest api version for each resource type.

**Comment by weidongxu-microsoft** [comment]
@xenalite OK. We will start with 100 storage accounts and delete them via
`azure.Deployments.Manager.GenericResources.DeleteAsync(resource.ResourceGroupName, "Microsoft.Storage", "", "storageAccounts", resource.Name, "2018-11-01");`

So far not encountered.

**Comment by redtaped** [comment]
I also am experiencing this error, specifically when deleting the azure service bus namespace.

It seems like SB returns 201, then that kicks off the polling operation. When calling ```GetPostOrDeleteOperationResultAsync```, to get the result, it returns 404 when the resource is successfully deleted. But the SDK views that as ane exception and causes this problem.

I'm using version 1.34.0 of the Fluent SDK.

```
   at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.<CheckErrorStatusAndThrowAsync>d__51.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.<GetRawAsync>d__49.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.<UpdateResourceFromPollingUri>d__47.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.<Poll>d__46.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.<StartPollingAsync>d__20.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.<BeginLROAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__1`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__0`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetPostOrDeleteOperationResultAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ServiceBus.Fluent.NamespacesOperations.<DeleteWithHttpMessagesAsync>d__9.MoveNext() in D:\a\1\s\src\ResourceManagement\ServiceBus\Generated\NamespacesOperations.cs:line 679
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ServiceBus.Fluent.NamespacesOperationsExtensions.<DeleteAsync>d__4.MoveNext() in D:\a\1\s\src\ResourceManagement\ServiceBus\Generated\NamespacesOperationsExtensions.cs:line 140
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ServiceBus.Fluent.ServiceBusNamespacesImpl.<DeleteInnerByGroupAsync>d__5.MoveNext() in D:\a\1\s\src\ResourceManagement\ServiceBus\ServiceBusNamespacesImpl.cs:line 36
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.GroupableResources`5.<DeleteByResourceGroupAsync>d__14.MoveNext() in D:\a\1\s\src\ResourceManagement\ResourceManager\Core\GroupableResources.cs:line 100
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Thycotic.Azure.Management.Wrappers.ServiceBusWrapper.<DeleteServiceBusNamespace>d__6.MoveNext() in C:\Users\JRhyne\source\repos\Thycotic.Cloud.Manager\src\Thycotic.Azure.Management\Wrappers\ServiceBusWrapper.cs:line 82
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Thycotic.Cloud.Manager.Core.Areas.Provisions.Logic.Azure.ProvisionServiceBusLogic.<Delete>d__14.MoveNext() in C:\Users\JRhyne\source\repos\Thycotic.Cloud.Manager\src\Thycotic.Cloud.Manager.Core\Areas\Provisions\Logic\Azure\ProvisionServiceBusLogic.cs:line 265
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Thycotic.Cloud.Manager.Core.Jobs.Services.SecretServerDeprovisionJobService.<RemoveConnectedResource>d__19.MoveNext() in C:\Users\JRhyne\source\repos\Thycotic.Cloud.Manager\src\Thycotic.Cloud.Manager.Core\Jobs\Services\SecretServerDeprovisionJobService.cs:line 118
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Thycotic.Cloud.Manager.Core.Jobs.DeprovisionJobServiceBase.<PerformDeprovision>d__5.MoveNext() in C:\Users\JRhyne\source\repos\Thycotic.Cloud.Manager\src\Thycotic.Cloud.Manager.Core\Jobs\DeprovisionJobServiceBase.cs:line 64
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Thycotic.Cloud.Manager.Core.Jobs.DeprovisionJob.<ProcessAsync>d__5.MoveNext() in C:\Users\JRhyne\source\repos\Thycotic.Cloud.Manager\src\Thycotic.Cloud.Manager.Core\Jobs\DeprovisionJob.cs:line 45
```
