### ISSUE TITLE
[BUG] System.NullReferenceException in Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.ProcessHttpRequestAsync

### ISSUE THREAD

**Issue by Johan-Lindvall-Stratsys** [Azure/azure-libraries-for-net#824]
**Describe the bug**
We are sometimes seeing a NullReferenceException in Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.ProcessHttpRequestAsync

***Exception or Stack Trace***
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Storage.Fluent.StorageAccountsOperations.ListByResourceGroupWithHttpMessagesAsync(String resourceGroupName, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Storage.Fluent.StorageAccountsOperationsExtensions.ListByResourceGroupAsync(IStorageAccountsOperations operations, String resourceGroupName, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Storage.Fluent.StorageAccountsImpl.ListInnerByGroupAsync(String groupName, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.TopLevelModifiableResources`5.<>c__DisplayClass4_0.<<ListByResourceGroupAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.PagedCollection`2.LoadPageWithWrapModelAsync(Func`2 listInnerAsync, Func`3 listInnerNext, Func`3 wrapModelAsync, Boolean loadAllPages, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.PagedCollection`2.LoadPage(Func`2 listInnerAsync, Func`3 listInnerNext, Func`2 wrapModel, Boolean loadAllPages, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.TopLevelModifiableResources`5.ListByResourceGroupAsync(String resourceGroupName, Boolean loadAllPages, CancellationToken cancellationToken)
   at DeployAzureInfra.Deploy.<>c__DisplayClass6_0`2.<<DeleteTagged>b__0>d.MoveNext() in C:\source\DeployAzureInfra\Deploy.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at DeployAzureInfra.WithLogging.Perform[T](String operation, Func`1 func, Int32 tries) in C:\source\DeployAzureInfra\WithLogging.cs:line 50.
```

**Setup (please complete the following information):**
 - Version of the Library used: 1.26.1

**Additional context**
A suggested fix is in https://github.com/Azure/azure-libraries-for-net/pull/823

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X] Bug Description Added
- [ X] Repro Steps Added
- [X ] Setup information Added

**Comment by Johan-Lindvall-Stratsys** [comment]
Verified fixed in 1.27.0
