### ISSUE TITLE
[BUG] Creating container fails when using .WithGpuResource

### ISSUE THREAD

**Issue by Brhav** [Azure/azure-libraries-for-net#848]
**Describe the bug**
When trying to create a container using ".WithGpuResource(1, GpuSku.K80)", it fails and throws the exception:
"The request content was invalid and could not be deserialized: 'Unexpected token StartObject when parsing enum. Path 'properties.containers[0].properties.resources.requests.gpu.sku', line 14, position 25.'."
It does work when I leave this one line out of my code.

***Exception or Stack Trace***
`   at Microsoft.Azure.Management.ContainerInstance.Fluent.ContainerGroupsOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ContainerInstance.Fluent.ContainerGroupsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ContainerInstance.Fluent.ContainerGroupsOperationsExtensions.<CreateOrUpdateAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ContainerInstance.Fluent.ContainerGroupImpl.<CreateResourceAsync>d__38.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.<Microsoft-Azure-Management-ResourceManager-Fluent-Core-ResourceActions-IResourceCreator<IResourceT>-CreateResourceAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.<ExecuteAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.<ExecuteNodeTaskAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()`

**To Reproduce**
Example in code snippet below.
Note that the container is successfully created when leaving out the line ".WithGpuResource(1, GpuSku.K80)"

***Code Snippet***
await azure.ContainerGroups.Define(containerGroupName)
.WithRegion(azureRegion)
.WithExistingResourceGroup(resourceGroupName)
.WithLinux()
.WithPublicImageRegistryOnly()
.WithoutVolume()
.DefineContainerInstance(containerGroupName + "-1")
.WithImage(containerImage)
.WithoutPorts()
.WithGpuResource(1, GpuSku.K80)
.WithCpuCoreCount(1)
.WithMemorySizeInGB(2)
.Attach()
.WithRestartPolicy(ContainerGroupRestartPolicy.Never)
.CreateAsync();

**Expected behavior**
It should create a container

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Visual Studio 2019
 - Version of the Library used: Microsoft.Azure.Management.ContainerInstance.Fluent, Version=1.0.0.61

**Additional context**
N/A

**Comment by yaohaizh** [comment]
@ChenTanyi could you help take a look at this one?

**Comment by ChenTanyi** [comment]
@Brhav will fix at 1.28.0, on Nov 15th
