### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by orpeti** [Azure/azure-libraries-for-net#862]
Hi Rick,

My name is Or, I work at Zerto in Azure team.
I had a issue while trying to create an Azure application, which did not reproduce in every attempt.
Please find attached the http requests and responses for both the successful operation of application creation, and for the failure case.
Please notice the yellow marked lines in the http response in the failure case – we can see there that we get an error status code of 302 (Redirect) with Reason phrase: Found. 
In the content it is mention that “…Use the following Urls to get the information..” and there is no Url afterwards,
so it is not clear what are those Urls, how are they related to the 302 error we got, and why aren’t they exist?

The http requests and responses for the successful operation, and for the failure:

Successful:
Request:
POST https://graph.windows.net/b57eec65-185d-4b60-83af-b4d1898c3c18/applications?api-version=1.6
Headers:
x-ms-client-request-id: 52796a7d-9396-430c-b73c-99b51764c0b2
accept-language: en-US
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik02cFg3UkhvcmFMc3ByZkplUkNqU3h1VVJoYyIsImtpZCI6Ik02cFg3UkhvcmFMc3ByZkplUkNqU3h1VVJoYyJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLndpbmRvd3MubmV0LyIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0L2I1N2VlYzY1LTE4NWQtNGI2MC04M2FmLWI0ZDE4OThjM2MxOC8iLCJpYXQiOjE1NzIyNTM4NzIsIm5iZiI6MTU3MjI1Mzg3MiwiZXhwIjoxNTcyMjU3NzcyLCJhY3IiOiIxIiwiYWlvIjoiWTJGZ1lGaXE5M3hmMnQyS2RKUEk5ekd2ZFozcmRuNlYzblNKVFducXJscnRpemFWb3NZQSIsImFtciI6WyJwd2QiXSwiYXBwaWQiOiIxOTUwYTI1OC0yMjdiLTRlMzEtYTljZi03MTc0OTU5NDVmYzIiLCJhcHBpZGFjciI6IjAiLCJmYW1pbHlfbmFtZSI6IktlcnIiLCJnaXZlbl9uYW1lIjoiUGV0ZXIiLCJpcGFkZHIiOiIxMy43Mi4zNC4xMyIsIm5hbWUiOiJQZXRlcktlcnIiLCJvaWQiOiJjNzYzYjA2OS02YjM2LTQwMzItYTAwNi05Y2M2ZDA3NWJjZTAiLCJwdWlkIjoiMTAwM0JGRkRBMjVBNzcyOSIsInNjcCI6IjYyZTkwMzk0LTY5ZjUtNDIzNy05MTkwLTAxMjE3NzE0NWUxMCIsInN1YiI6Ijhrdk8wT1J4NHRoc0lVNHJJX1VObi1xQzE5YnBIeDBnMnBOSThUVjdmV0UiLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiVVNHIiwidGlkIjoiYjU3ZWVjNjUtMTg1ZC00YjYwLTgzYWYtYjRkMTg5OGMzYzE4IiwidW5pcXVlX25hbWUiOiJhZG1pbnplcnRvQHplcnRvZ292Lm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6ImFkbWluemVydG9AemVydG9nb3Yub25taWNyb3NvZnQuY29tIiwidXRpIjoiNV9JQVppRFVrRXl0QzBUTGwtOExBQSIsInZlciI6IjEuMCJ9.SRPf-o93GW-IvxMx4PvYkDq0t35nBx_zxWvZhrhVZ8qA60lJGxN3WZFrTL1b5jfV3snkOHJJBBky0Dp_LaBaxUFsEulirB9w_cc-3nKC2_PBmmMli10DujxktGSUpM8PX69f3N39nGbWBqAZXW01QP4ahMFQlRFZoVpNTRN_vj8Ed-2TP_9AKsU69WMfEq0SoV7X4xuP_JeNJZujMyAC6YhPKHgtGRKeBoeCTkzs5pcxxDi1xUOxnZ1Y5LwSShgINJcrUPv0DYZj8z3_nLA-8L0gwhp9fflFT-WGArBXWdiRN9CuKgLWAN1_gBNGTLdfMiO3AC1FhdQZ8Q7HTmGK-Q
User-Agent: FxVersion/4.7.3468.0, OSName/Windows, OSVersion/10.0.17763.0, Microsoft.Azure.Graph.RBAC.GraphRbacManagementClient/3.2.0.0, Zerto/1.0pid-84d2edc4-86bd-439c-8373-e9f04e0f5ad2
Content:
{
  ""availableToOtherTenants"": false,
  ""displayName"": ""Zerto Cloud Appliance"",
  ""homepage"": ""http://www.zerto.com/"",
  ""identifierUris"": [
    ""http://www.zerto.com/installer/c0c62a9b-0f59-4832-bf18-58828576f46c""
  ],
  ""replyUrls"": [],
  ""keyCredentials"": [],
  ""passwordCredentials"": [
    {
      ""startDate"": ""2019-10-26T09:20:04.8301194Z"",
      ""endDate"": ""2029-10-25T09:20:04.8301194Z"",
      ""keyId"": ""986ae554-1b00-4a70-a842-82803c2ba8b5"",
      ""value"": "";oI%6F-uBQ5B&WU0""
    },
    {
      ""startDate"": ""2019-10-26T09:20:04.8301194Z"",
      ""endDate"": ""2029-10-25T09:20:04.8301194Z"",
      ""keyId"": ""f88fb153-73a1-4ae7-80eb-839ccb699a7e"",
      ""value"": ""1@th>X5TMHbYJ&-Y""
    }
  ]
}
End of HTTP request: fe19c8c8-edb9-4c62-8b28-c898d8f1e0a4
",

Response:
,,,2019-10-28 09:20:05.7813,T,18,Zerto.Zvm.Platform.PublicCloud.AzureProxy.Implementation.HttpTracer,MoveNext,"Start of HTTP response: fe19c8c8-edb9-4c62-8b28-c898d8f1e0a4
Status Code: 201 (Created)
Headers:
Pragma: no-cache
ocp-aad-diagnostics-server-name: pVcjMwQ2PgNzulbaYzKH9IAgqs/9vprgs2OnV6f483k=
request-id: 4fd06c54-facd-4bdf-b012-fb6289fade13
client-request-id: 52796a7d-9396-430c-b73c-99b51764c0b2
x-ms-dirapi-data-contract-version: 1.6
ocp-aad-session-key: umRqCjOJaYQCColzqG4rLoMqwzz-AvRa-ls7kH45IzxzGzPK3vCJ_XNu2iKW2BwXBHhQpvf2cc_7ikyHRPQ2Np6QVuBa4t2KLUZKQQ7c7iIMV2mv0M2WnrqdTOk_5NLvVppz9TFs07Lw3gpcgUavdyJ24b5emnioM6iBxiGgdIA.2Y2kmfQkX2KKeWxnJVMk2_DVi2Am3IFmo5v2IJmmWsg
DataServiceVersion: 3.0;
Strict-Transport-Security: max-age=31536000; includeSubDomains
Access-Control-Allow-Origin: *
Duration: 4944822
Cache-Control: no-cache
Date: Mon, 28 Oct 2019 09:20:05 GMT
Location: https://graph.windows.net/b57eec65-185d-4b60-83af-b4d1898c3c18/directoryObjects/bc7f1cc2-e03b-4706-ae0b-012485df68c2/Microsoft.DirectoryServices.Application
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Content:
{""odata.metadata"":""https://graph.windows.net/b57eec65-185d-4b60-83af-b4d1898c3c18/$metadata#directoryObjects/@Element"",""odata.type"":""Microsoft.DirectoryServices.Application"",""objectType"":""Application"",""objectId"":""bc7f1cc2-e03b-4706-ae0b-012485df68c2"",""deletionTimestamp"":null,""acceptMappedClaims"":null,""addIns"":[],""appId"":""1ec4744a-8bfa-41e6-b6a2-156e267496fc"",""applicationTemplateId"":null,""appRoles"":[],""availableToOtherTenants"":false,""displayName"":""Zerto Cloud Appliance"",""errorUrl"":null,""groupMembershipClaims"":null,""homepage"":""http://www.zerto.com/"",""identifierUris"":[""http://www.zerto.com/installer/c0c62a9b-0f59-4832-bf18-58828576f46c""],""informationalUrls"":{""termsOfService"":null,""support"":null,""privacy"":null,""marketing"":null},""isDeviceOnlyAuthSupported"":null,""keyCredentials"":[],""knownClientApplications"":[],""logoutUrl"":null,""logo@odata.mediaEditLink"":""directoryObjects/bc7f1cc2-e03b-4706-ae0b-012485df68c2/Microsoft.DirectoryServices.Application/logo"",""logo@odata.mediaContentType"":""application/json;odata=minimalmetadata; charset=utf-8"",""logoUrl"":null,""oauth2AllowIdTokenImplicitFlow"":true,""oauth2AllowImplicitFlow"":false,""oauth2AllowUrlPathMatching"":false,""oauth2Permissions"":[{""adminConsentDescription"":""Allow the application to access Zerto Cloud Appliance on behalf of the signed-in user."",""adminConsentDisplayName"":""Access Zerto Cloud Appliance"",""id"":""2f197bc1-1c81-4da5-9f0c-1e9e17f570a9"",""isEnabled"":true,""type"":""User"",""userConsentDescription"":""Allow the application to access Zerto Cloud Appliance on your behalf."",""userConsentDisplayName"":""Access Zerto Cloud Appliance"",""value"":""user_impersonation""}],""oauth2RequirePostResponse"":false,""optionalClaims"":null,""orgRestrictions"":[],""parentalControlSettings"":{""countriesBlockedForMinors"":[],""legalAgeGroupRule"":""Allow""},""passwordCredentials"":[{""customKeyIdentifier"":null,""endDate"":""2029-10-25T09:20:04.8301194Z"",""keyId"":""f88fb153-73a1-4ae7-80eb-839ccb699a7e"",""startDate"":""2019-10-26T09:20:04.8301194Z"",""value"":null},{""customKeyIdentifier"":null,""endDate"":""2029-10-25T09:20:04.8301194Z"",""keyId"":""986ae554-1b00-4a70-a842-82803c2ba8b5"",""startDate"":""2019-10-26T09:20:04.8301194Z"",""value"":null}],""publicClient"":null,""publisherDomain"":""zertogov.onmicrosoft.com"",""recordConsentConditions"":null,""replyUrls"":[],""requiredResourceAccess"":[],""samlMetadataUrl"":null,""signInAudience"":""AzureADMyOrg"",""tokenEncryptionKeyId"":null}
End of HTTP response: fe19c8c8-edb9-4c62-8b28-c898d8f1e0a4
",

Failure:
Request:
,,,2019-10-28 09:36:20.6504,T,14,Zerto.Zvm.Platform.PublicCloud.AzureProxy.Implementation.HttpTracer,RunAndTraceRequest,"Start of HTTP request: c7c01c01-5e1b-4a74-a8e7-dcb0d3baaf1d
POST https://graph.windows.net/b57eec65-185d-4b60-83af-b4d1898c3c18/applications?api-version=1.6
Headers:
x-ms-client-request-id: 63822d31-8cea-426c-9dd1-622b2157635b
accept-language: en-US
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik02cFg3UkhvcmFMc3ByZkplUkNqU3h1VVJoYyIsImtpZCI6Ik02cFg3UkhvcmFMc3ByZkplUkNqU3h1VVJoYyJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLndpbmRvd3MubmV0LyIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0L2I1N2VlYzY1LTE4NWQtNGI2MC04M2FmLWI0ZDE4OThjM2MxOC8iLCJpYXQiOjE1NzIyNTQ4NDQsIm5iZiI6MTU3MjI1NDg0NCwiZXhwIjoxNTcyMjU4NzQ0LCJhY3IiOiIxIiwiYWlvIjoiWTJGZ1lPQy8zbExnRzY3VXlMZWo2a3l0cjgzVkpnNGIvZGV5QllzRUQ5cFZTUlJLQ2dJQSIsImFtciI6WyJwd2QiXSwiYXBwaWQiOiIxOTUwYTI1OC0yMjdiLTRlMzEtYTljZi03MTc0OTU5NDVmYzIiLCJhcHBpZGFjciI6IjAiLCJmYW1pbHlfbmFtZSI6IktlcnIiLCJnaXZlbl9uYW1lIjoiUGV0ZXIiLCJpcGFkZHIiOiIxMy43Mi4zNC4xMyIsIm5hbWUiOiJQZXRlcktlcnIiLCJvaWQiOiJjNzYzYjA2OS02YjM2LTQwMzItYTAwNi05Y2M2ZDA3NWJjZTAiLCJwdWlkIjoiMTAwM0JGRkRBMjVBNzcyOSIsInNjcCI6IjYyZTkwMzk0LTY5ZjUtNDIzNy05MTkwLTAxMjE3NzE0NWUxMCIsInN1YiI6Ijhrdk8wT1J4NHRoc0lVNHJJX1VObi1xQzE5YnBIeDBnMnBOSThUVjdmV0UiLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiVVNHIiwidGlkIjoiYjU3ZWVjNjUtMTg1ZC00YjYwLTgzYWYtYjRkMTg5OGMzYzE4IiwidW5pcXVlX25hbWUiOiJhZG1pbnplcnRvQHplcnRvZ292Lm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6ImFkbWluemVydG9AemVydG9nb3Yub25taWNyb3NvZnQuY29tIiwidXRpIjoiNkxtSy15TmpYRTZkZ3lveE01NEtBQSIsInZlciI6IjEuMCJ9.Ov8DRk3SA_B6CyC7ZaJFeDYEt-gdi8dxIOCnCNjaqFtf3owjAZMJj5kEj6IzljUsOsp-rlqBFZiKshjQ0TxHSz2IATjj9OffH4nVlDlSdj8cbpb6O3wolcFj7GdMkzqm0Cyfe0VgJH4Yf6BVyFwiz_T0cglaTGUkvXPkfUkeJZc8AVSREw5HHd3Qm4YonTdBEFoH0DH369mMKDZCVUkzYKA3mryPIT55cPqLMtCKv0QA4vnnIHxOOikicDykZZ2Mmm-I99fAkMrOoDxJjVI-xQLES72XmZLdbdx6HnlhL3ZcM1v69kGrw2effcTU_T41SPyF7rfR1v4Xbqa0qK-hkw
User-Agent: FxVersion/4.7.3468.0, OSName/Windows, OSVersion/10.0.17763.0, Microsoft.Azure.Graph.RBAC.GraphRbacManagementClient/3.2.0.0, Zerto/1.0pid-84d2edc4-86bd-439c-8373-e9f04e0f5ad2
Content:
{
  ""availableToOtherTenants"": false,
  ""displayName"": ""Zerto Cloud Appliance"",
  ""homepage"": ""http://www.zerto.com/"",
  ""identifierUris"": [
    ""http://www.zerto.com/installer/96d932ee-9f84-4735-b6eb-06b4e4be852a""
  ],
  ""replyUrls"": [],
  ""keyCredentials"": [],
  ""passwordCredentials"": [
    {
      ""startDate"": ""2019-10-26T09:36:20.5984521Z"",
      ""endDate"": ""2029-10-25T09:36:20.5984521Z"",
      ""keyId"": ""b5e0295a-8766-4cd5-80e9-40b2d8493b5c"",
      ""value"": ""h1#c&ah&e$F41wUH""
    },
    {
      ""startDate"": ""2019-10-26T09:36:20.5984521Z"",
      ""endDate"": ""2029-10-25T09:36:20.5984521Z"",
      ""keyId"": ""dc6ce269-d65e-4e2c-a77e-0691c45e054c"",
      ""value"": ""(yJx#}6gvMnh3WB=""
    }
  ]
}
End of HTTP request: c7c01c01-5e1b-4a74-a8e7-dcb0d3baaf1d

Response:
,,,2019-10-28 09:36:21.0697,T,14,Zerto.Zvm.Platform.PublicCloud.AzureProxy.Implementation.HttpTracer,MoveNext,"Start of HTTP response: c7c01c01-5e1b-4a74-a8e7-dcb0d3baaf1d
Status Code: 302 (Redirect)
Reason phrase: Found
Headers:
Pragma: no-cache
ocp-aad-diagnostics-server-name: HFGxio4dlffe0IoKJIt7Vjx9d+1k7PqkmEfKx4j79u4=
request-id: 162fc54f-34d9-4ce1-b43e-8c01b9a4f33e
client-request-id: 63822d31-8cea-426c-9dd1-622b2157635b
x-ms-dirapi-data-contract-version: 1.6
DataServiceVersion: 3.0;
Strict-Transport-Security: max-age=31536000; includeSubDomains
Access-Control-Allow-Origin: *
Duration: 192801
Cache-Control: no-cache
Date: Mon, 28 Oct 2019 09:36:20 GMT
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Content:
{""odata.error"":{""code"":""Directory_BindingRedirection"",""message"":{""lang"":""en"",""value"":""Tenant information is not available locally. Use the following Urls to get the information.""},""requestId"":""162fc54f-34d9-4ce1-b43e-8c01b9a4f33e"",""date"":""2019-10-28T09:36:21""}}
End of HTTP response: c7c01c01-5e1b-4a74-a8e7-dcb0d3baaf1d
",
,,,2019-10-28 09:36:21.0697,I,14,Zerto.Zvm.Platform.PublicCloud.AzureProxy.Implementation.AzureGraphProxy,MoveNext,Failed to create application (URI=http://www.zerto.com/installer/96d932ee-9f84-4735-b6eb-06b4e4be852a),"Microsoft.Azure.Graph.RBAC.Models.GraphErrorException Void MoveNext() Microsoft.Azure.Graph.RBAC.Models.GraphErrorException: Operation returned an invalid status code 'Redirect'
   at Microsoft.Azure.Graph.RBAC.ApplicationsOperations.<CreateWithHttpMessagesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Graph.RBAC.ApplicationsOperationsExtensions.<CreateAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Zerto.Zvm.Platform.PublicCloud.AzureProxy.Accessors.ApplicationsAccessor.<CreateApplicationAsync>d__6.MoveNext() in E:\eaglerare_u3\dev\system\Zvm\Platform\PublicCloud\AzureProxy\Accessors\ApplicationsAccessor.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Zerto.Zvm.Platform.PublicCloud.AzureProxy.Implementation.AzureGraphProxy.<CreateApplication>d__11.MoveNext() in E:\eaglerare_u3\dev\system\Zvm\Platform\PublicCloud\AzureProxy\Implementation\AzureGraphProxy.cs:line 181"
,,,2019-10-28 09:36:21.1037,E,14,Zerto.Zvm.Platform.PublicCloud.AzureProxy.Implementation.AzureGraphProxy,MoveNext,Failed to create application. Error message = Failed to create application Zerto Cloud Appliance..,"Zerto.Platform.PublicCloud.DTO.CloudGraphException Void MoveNext() Zerto.Platform.PublicCloud.DTO.CloudGraphException: Failed to create application Zerto Cloud Appliance. ---> Microsoft.Azure.Graph.RBAC.Models.GraphErrorException: Operation returned an invalid status code 'Redirect'
   at Microsoft.Azure.Graph.RBAC.ApplicationsOperations.<CreateWithHttpMessagesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Graph.RBAC.ApplicationsOperationsExtensions.<CreateAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Zerto.Zvm.Platform.PublicCloud.AzureProxy.Accessors.ApplicationsAccessor.<CreateApplicationAsync>d__6.MoveNext() in E:\eaglerare_u3\dev\system\Zvm\Platform\PublicCloud\AzureProxy\Accessors\ApplicationsAccessor.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Zerto.Zvm.Platform.PublicCloud.AzureProxy.Implementation.AzureGraphProxy.<CreateApplication>d__11.MoveNext() in E:\eaglerare_u3\dev\system\Zvm\Platform\PublicCloud\AzureProxy\Implementation\AzureGraphProxy.cs:line 181
   --- End of inner exception stack trace ---
   at Zerto.Zvm.Platform.PublicCloud.AzureProxy.Implementation.AzureGraphProxy.<CreateApplication>d__11.MoveNext() in E:\eaglerare_u3\dev\system\Zvm\Platform\PublicCloud\AzureProxy\Implementation\AzureGraphProxy.cs:line 187
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Zerto.Zvm.Platform.PublicCloud.AzureProxy.Implementation.AzureGraphProxy.<CreateApplicationAsync>d__7.MoveNext() in E:\eaglerare_u3\dev\system\Zvm\Platform\PublicCloud\AzureProxy\Implementation\AzureGraphProxy.cs:line 84"
,,,2019-10-28 09:36:21.1037,E,9,Zerto.Zvm.Configuration.Core.Notification.NotificationBus,AddError,Azure credentials Failed to register application in Azure,"Zerto.Platform.PublicCloud.DTO.CloudGraphException Void MoveNext() Zerto.Platform.PublicCloud.DTO.CloudGraphException: Failed to create application Zerto Cloud Appliance. ---> Microsoft.Azure.Graph.RBAC.Models.GraphErrorException: Operation returned an invalid status code 'Redirect'
   at Microsoft.Azure.Graph.RBAC.ApplicationsOperations.<CreateWithHttpMessagesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Graph.RBAC.ApplicationsOperationsExtensions.<CreateAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Zerto.Zvm.Platform.PublicCloud.AzureProxy.Accessors.ApplicationsAccessor.<CreateApplicationAsync>d__6.MoveNext() in E:\eaglerare_u3\dev\system\Zvm\Platform\PublicCloud\AzureProxy\Accessors\ApplicationsAccessor.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Zerto.Zvm.Platform.PublicCloud.AzureProxy.Implementation.AzureGraphProxy.<CreateApplication>d__11.MoveNext() in E:\eaglerare_u3\dev\system\Zvm\Platform\PublicCloud\AzureProxy\Implementation\AzureGraphProxy.cs:line 181
   --- End of inner exception stack trace ---
   at Zerto.Zvm.Platform.PublicCloud.AzureProxy.Implementation.AzureGraphProxy.<CreateApplication>d__11.MoveNext() in E:\eaglerare_u3\dev\system\Zvm\Platform\PublicCloud\AzureProxy\Implementation\AzureGraphProxy.cs:line 187
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Zerto.Zvm.Platform.PublicCloud.AzureProxy.Implementation.AzureGraphProxy.<CreateApplicationAsync>d__7.MoveNext() in E:\eaglerare_u3\dev\system\Zvm\Platform\PublicCloud\AzureProxy\Implementation\AzureGraphProxy.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Zerto.Zvm.Configuration.Azure.Credentials.AzureCredentialsConfigurator.GetAppCredentials() in E:\eaglerare_u3\dev\system\Zvm\Configuration\Zerto.Zvm.Configuration.Azure\Credentials\AzureCredentialsConfigurator.cs:line 241
   at Zerto.Zvm.Configuration.Azure.Credentials.AzureCredentialsConfigurator.RegisterApplicationInAzure(INotification notification) in E:\eaglerare_u3\dev\system\Zvm\Configuration\Zerto.Zvm.Configuration.Azure\Credentials\AzureCredentialsConfigurator.cs:line 210"

Hope you can help us with this issue,
Thanks,
Or

**Comment by yaohaizh** [comment]
@weidongxu-microsoft please take a look at this issue, thanks.

**Comment by weidongxu-microsoft** [comment]
@orpeti 

Do you have a well-formated log there? You can attach a txt file, or at least use the code block. Is it not possible for me to read above log. And there is certainly no "yellow marked lines".

**Comment by nickzhums** [comment]
@orpeti Let us know if you still need support
